<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrestCreates.Authorization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\CrestCreates.Authorization.Abstractions\CrestCreates.Authorization.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\CrestCreates.Aop.Abstractions\CrestCreates.Aop.Abstractions.csproj" />
    <ProjectReference Include="..\..\Core\CrestCreates.Caching\CrestCreates.Caching.csproj" />
    <ProjectReference Include="..\CrestCreates.Domain\CrestCreates.Domain.csproj" />
    <ProjectReference Include="..\CrestCreates.Domain.Shared\CrestCreates.Domain.Shared.csproj" />
    <ProjectReference Include="..\CrestCreates.Modularity\CrestCreates.Modularity.csproj"/>
    <ProjectReference Include="..\CrestCreates.MultiTenancy.Abstract\CrestCreates.MultiTenancy.Abstract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="InMemoryPermissionStore.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rougamo.Extensions.DependencyInjection.Microsoft" />
  </ItemGroup>

</Project>
