using CrestCreates.Agent.Memory.Projection;
using CrestCreates.Agent.Memory.ReadCore;
using CrestCreates.Capability.Abstractions;
using CrestCreates.Generated;
using CrestCreates.Mcp.Abstractions;
using CrestCreates.Mcp.Memory.Json;
using CrestCreates.Mcp.Memory.Security;
using CrestCreates.Metadata.Abstractions.Bootstrap;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace CrestCreates.Mcp.Memory;

public static class McpMemoryServiceCollectionExtensions
{
    /// <summary>
    /// Registers MCP Memory tools. Requires an MCP-capable
    /// IAgentMemoryAccessScopeProvider to be registered externally.
    /// The host must also call AddCapabilityRuntime() and AddCrestMcpToolProjection().
    /// </summary>
    public static IServiceCollection AddMcpMemoryTools(
        this IServiceCollection services)
    {
        // Security infrastructure (from Projection)
        services.AddAgentMemoryProjectionSecurity();

        // ReadCore
        services.AddAgentMemoryReadCore();

        // MCP Memory Origin Factory
        services.TryAddSingleton<McpMemoryArtifactOriginFactory>();

        // Capability module + handler DI (new composable pattern)
        // Generated by HandlerInvokerSourceGenerator from [CapabilityName] attributes
        services.TryAddEnumerable(
            ServiceDescriptor.Singleton<ICapabilityHandlerModule>(
                GeneratedCapabilityHandlerModule.Instance));
        GeneratedHandlerRegistry.RegisterServices(services);

        // JSON context contributor for MCP Memory tool DTOs
        services.TryAddEnumerable(
            ServiceDescriptor.Singleton<IMcpToolJsonContextContributor, McpMemoryJsonContextContributor>());

        // Bootstrap validator (fail-closed: rejects unknown scope providers)
        services.TryAddEnumerable(
            ServiceDescriptor.Singleton<IBootstrapValidator, McpMemoryScopeProviderValidator>());

        return services;
    }
}
