using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CrestCreates.CodeGenerator.AgentToolGenerator;

internal static class AgentToolProviderEmitter
{
    public static string Emit(AgentToolContainerModel container)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using CrestCreates.Metadata;");
        builder.AppendLine("using CrestCreates.Metadata.Abstractions;");
        builder.AppendLine("using CrestCreates.Metadata.Abstractions.DescriptorCapability;");
        builder.AppendLine("using CrestCreates.Metadata.AgentTool;");
        if (container.Namespace.Length > 0)
            builder.AppendLine("namespace " + container.Namespace + ";");

        builder.AppendLine("internal sealed class " + container.Name + "_GeneratedAgentToolProvider : IDescriptorProvider<AgentCapabilityToolDescriptor>");
        builder.AppendLine("{");
        builder.AppendLine("    public IReadOnlyList<AgentCapabilityToolDescriptor> GetDescriptors() => new AgentCapabilityToolDescriptor[]");
        builder.AppendLine("    {");
        foreach (var spec in container.Specs)
        {
            builder.AppendLine("        new AgentCapabilityToolDescriptor");
            builder.AppendLine("        {");
            builder.AppendLine("            Id = " + Literal(spec.DescriptorId) + ",");
            builder.AppendLine("            Name = " + Literal(spec.SpecName) + ",");
            builder.AppendLine("            Version = " + Invariant(spec.DescriptorVersion) + ",");
            builder.AppendLine("            Capability = new CapabilityProjectionReference(");
            builder.AppendLine("                " + Literal(spec.CapabilityId) + ",");
            builder.AppendLine("                " + Invariant(spec.CapabilityVersion) + ",");
            builder.AppendLine("                VersionSelectionMode." + (spec.CapabilityVersion == 0 ? "Latest" : "Exact") + ",");
            builder.AppendLine("                " + NullableLiteral(spec.ExpectedCapabilityContractHash) + "),");
            builder.AppendLine("            ToolName = " + Literal(spec.ToolName) + ",");
            if (spec.Title is not null)
                builder.AppendLine("            Title = " + Literal(spec.Title) + ",");
            builder.AppendLine("            Description = " + Literal(spec.Description) + ",");
            builder.AppendLine("            SelectionPolicy = AgentToolSelectionPolicy." + SelectionPolicy(spec.SelectionPolicy) + ",");
            builder.AppendLine("            SideEffectKind = AgentToolSideEffectKind." + SideEffectKind(spec.SideEffectKind) + ",");
            builder.AppendLine("            RiskFloor = " + RiskFloor(spec.RiskFloor) + ",");
            builder.AppendLine("            ApprovalMode = AgentToolApprovalMode." + ApprovalMode(spec.ApprovalMode) + ",");
            builder.AppendLine("            Budget = new AgentToolBudgetRequirement");
            builder.AppendLine("            {");
            builder.AppendLine("                Category = " + Literal(spec.BudgetCategory) + ",");
            builder.AppendLine("                CostUnits = " + Invariant(spec.CostUnits) + "L,");
            builder.AppendLine("                MaxCallsPerExecution = " + (spec.MaxCallsPerExecution == 0 ? "null" : Invariant(spec.MaxCallsPerExecution)));
            builder.AppendLine("            },");
            builder.AppendLine("            AuditMode = AgentToolAuditMode." + AuditMode(spec.AuditMode) + ",");
            builder.AppendLine("            AllowedAgentRoles = " + Roles(spec));
            builder.AppendLine("        },");
        }
        builder.AppendLine("    };");
        builder.AppendLine("}");
        builder.AppendLine("internal static class " + container.Name + "_GeneratedAgentToolProviderRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register() => DescriptorProviderRegistry.Register<AgentCapabilityToolDescriptor>(");
        builder.AppendLine("        new " + container.Name + "_GeneratedAgentToolProvider());");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Roles(AgentToolSpecModel spec)
    {
        var builder = new StringBuilder("new string[] { ");
        for (var index = 0; index < spec.AllowedAgentRoles.Length; index++)
        {
            if (index > 0)
                builder.Append(", ");
            builder.Append(Literal(spec.AllowedAgentRoles[index]));
        }
        builder.Append(" }");
        return builder.ToString();
    }

    private static string SelectionPolicy(int value) => value == 2 ? "AutomaticAllowed" : "ExplicitOnly";

    private static string SideEffectKind(int value)
        => value switch
        {
            1 => "ReadOnly",
            2 => "InternalWrite",
            3 => "ExternalWrite",
            4 => "Destructive",
            _ => "Unknown"
        };

    // AgentToolRiskFloor intentionally does not share CapabilityRiskLevel's numeric layout.
    private static string RiskFloor(int value)
        => value switch
        {
            1 => "CapabilityRiskLevel.Low",
            2 => "CapabilityRiskLevel.Medium",
            3 => "CapabilityRiskLevel.High",
            4 => "CapabilityRiskLevel.Critical",
            _ => "null"
        };

    private static string ApprovalMode(int value)
        => value switch
        {
            2 => "Required",
            3 => "None",
            _ => "PolicyDriven"
        };

    private static string AuditMode(int value) => value == 2 ? "BestEffort" : "Required";

    private static string NullableLiteral(string? value) => value is null ? "null" : Literal(value);

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Invariant(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static string Invariant(long value) => value.ToString(CultureInfo.InvariantCulture);
}
