using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CrestCreates.CodeGenerator.AgentToolGenerator;

internal static class AgentToolBindingEmitter
{
    public static string Emit(AgentToolContainerModel container)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization.Metadata;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using CrestCreates.Agent.Tools;");
        if (container.Namespace.Length > 0)
            builder.AppendLine("namespace " + container.Namespace + ";");

        builder.AppendLine("internal static class " + container.Name + "_GeneratedAgentToolBindings");
        builder.AppendLine("{");
        builder.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        for (var index = 0; index < container.Specs.Length; index++)
        {
            var spec = container.Specs[index];
            var methodSuffix = Invariant(index);
            if (spec.InputType is not null)
                builder.AppendLine("        AgentToolJsonContractRegistry.RegisterInputType(typeof(" + spec.InputType + "));");
            if (spec.OutputType is not null)
                builder.AppendLine("        AgentToolJsonContractRegistry.RegisterOutputType(typeof(" + spec.OutputType + "));");
            builder.AppendLine("        AgentToolBindingRegistry.Register(new AgentToolBindingContract");
            builder.AppendLine("        {");
            builder.AppendLine("            ToolDescriptorId = " + Literal(spec.DescriptorId) + ",");
            builder.AppendLine("            ToolDescriptorVersion = " + Invariant(spec.DescriptorVersion) + ",");
            builder.AppendLine("            InputType = " + TypeOf(spec.InputType) + ",");
            builder.AppendLine("            OutputType = " + TypeOf(spec.OutputType) + ",");
            builder.AppendLine("            BindInputAsync = BindInput" + methodSuffix + "Async,");
            builder.AppendLine("            SerializeOutputAsync = SerializeOutput" + methodSuffix + "Async");
            builder.AppendLine("        });");
        }
        builder.AppendLine("    }");

        for (var index = 0; index < container.Specs.Length; index++)
        {
            EmitBinder(builder, container.Specs[index], index);
            EmitSerializer(builder, container.Specs[index], index);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitBinder(StringBuilder builder, AgentToolSpecModel spec, int index)
    {
        builder.AppendLine("    private static ValueTask<object?> BindInput" + Invariant(index) + "Async(");
        builder.AppendLine("        JsonElement arguments, JsonTypeInfo? jsonTypeInfo, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        if (spec.InputType is null)
        {
            builder.AppendLine("        return new ValueTask<object?>((object?)null);");
        }
        else
        {
            builder.AppendLine("        if (jsonTypeInfo is not JsonTypeInfo<" + spec.InputType + "> typedTypeInfo)");
            builder.AppendLine("            throw new InvalidOperationException(\"Agent Tool input JSON contract mismatch.\");");
            builder.AppendLine("        var value = JsonSerializer.Deserialize(arguments, typedTypeInfo);");
            builder.AppendLine("        return new ValueTask<object?>((object?)value);");
        }
        builder.AppendLine("    }");
    }

    private static void EmitSerializer(StringBuilder builder, AgentToolSpecModel spec, int index)
    {
        builder.AppendLine("    private static ValueTask<JsonElement?> SerializeOutput" + Invariant(index) + "Async(");
        builder.AppendLine("        object? output, JsonTypeInfo? jsonTypeInfo, CancellationToken cancellationToken)");
        builder.AppendLine("    {");
        if (spec.OutputType is null)
        {
            builder.AppendLine("        if (output is not null)");
            builder.AppendLine("            throw new InvalidOperationException(\"Agent Tool output contract mismatch.\");");
            builder.AppendLine("        return new ValueTask<JsonElement?>((JsonElement?)null);");
        }
        else
        {
            builder.AppendLine("        if (output is null || output.GetType() != typeof(" + spec.OutputType + "))");
            builder.AppendLine("            throw new InvalidOperationException(\"Agent Tool output contract mismatch.\");");
            builder.AppendLine("        if (jsonTypeInfo is not JsonTypeInfo<" + spec.OutputType + "> typedTypeInfo)");
            builder.AppendLine("            throw new InvalidOperationException(\"Agent Tool output JSON contract mismatch.\");");
            builder.AppendLine("        var element = JsonSerializer.SerializeToElement((" + spec.OutputType + ")output, typedTypeInfo);");
            builder.AppendLine("        return new ValueTask<JsonElement?>((JsonElement?)element);");
        }
        builder.AppendLine("    }");
    }

    private static string TypeOf(string? type) => type is null ? "null" : "typeof(" + type + ")";

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Invariant(int value) => value.ToString(CultureInfo.InvariantCulture);
}
