<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CrestCreates.Mcp.Abstractions/CrestCreates.Mcp.Abstractions.csproj" />
    <ProjectReference Include="../../Metadata/CrestCreates.Metadata/CrestCreates.Metadata.csproj" />
    <ProjectReference Include="../../Metadata/CrestCreates.Schema/CrestCreates.Schema.csproj" />
  </ItemGroup>
</Project>
