<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrestCreates.Agent.Tools</RootNamespace>
    <AssemblyName>CrestCreates.Agent.Tools.Abstractions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CrestCreates.Agent.Abstractions/CrestCreates.Agent.Abstractions.csproj" />
    <ProjectReference Include="../../../Metadata/CrestCreates.Metadata.AgentTool.Abstractions/CrestCreates.Metadata.AgentTool.Abstractions.csproj" />
  </ItemGroup>
</Project>
