using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.EnumDisplayGenerator;

[Generator]
public sealed class EnumDisplaySourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enumInfos = context.CompilationProvider
            .Select((compilation, _) =>
            {
                var results = ImmutableArray.CreateBuilder<EnumDisplayInfo>();
                var processed = new HashSet<string>();

                // Scan the entire compilation (source + metadata) for enums with [EnumDisplay]
                // Only generate for enums in the current assembly to avoid duplicate definitions
                var currentAssembly = compilation.Assembly;
                ScanNamespaceForEnums(compilation.GlobalNamespace, results, processed, currentAssembly);

                return results.ToImmutable();
            })
            .WithTrackingName("EnumDisplay_Extract");

        context.RegisterSourceOutput(enumInfos, GenerateDisplayExtensions);
    }

    private static void ScanNamespaceForEnums(
        INamespaceSymbol ns,
        ImmutableArray<EnumDisplayInfo>.Builder results,
        HashSet<string> processed,
        IAssemblySymbol currentAssembly)
    {
        foreach (var typeMember in ns.GetTypeMembers())
        {
            ScanTypeForEnum(typeMember, results, processed, currentAssembly);
        }

        foreach (var childNs in ns.GetNamespaceMembers())
        {
            ScanNamespaceForEnums(childNs, results, processed, currentAssembly);
        }
    }

    private static void ScanTypeForEnum(
        INamedTypeSymbol type,
        ImmutableArray<EnumDisplayInfo>.Builder results,
        HashSet<string> processed,
        IAssemblySymbol currentAssembly)
    {
        if (type.TypeKind == TypeKind.Enum)
        {
            // Only generate for enums in the current assembly. Each project
            // generates extensions for its own enums to avoid duplicates.
            if (!SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
                return;

            var fullName = type.ToDisplayString();
            if (!processed.Add(fullName))
                return;

            var members = new List<(string Name, string DisplayName)>();
            foreach (var member in type.GetMembers().OfType<IFieldSymbol>())
            {
                var displayAttr = member.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass != null && (
                        a.AttributeClass.Name == "EnumDisplayAttribute" ||
                        a.AttributeClass.Name == "EnumDisplay" ||
                        a.AttributeClass.ToDisplayString().EndsWith(".EnumDisplayAttribute") ||
                        a.AttributeClass.ToDisplayString().EndsWith(".EnumDisplay")));

                if (displayAttr == null)
                    continue;

                var displayName = member.Name;
                if (displayAttr.ConstructorArguments.Length > 0 &&
                    displayAttr.ConstructorArguments[0].Value is string ctorName && ctorName.Length > 0)
                {
                    displayName = ctorName;
                }
                else
                {
                    var namedArg = displayAttr.NamedArguments.FirstOrDefault(a => a.Key == "Name");
                    if (namedArg.Value.Value is string namedName && namedName.Length > 0)
                        displayName = namedName;
                }

                members.Add((member.Name, displayName));
            }

            if (members.Count > 0)
            {
                var ns = type.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : type.ContainingNamespace.ToDisplayString();

                results.Add(new EnumDisplayInfo(
                    TypeName: type.Name,
                    FullTypeName: fullName,
                    Namespace: ns,
                    Members: members
                ));
            }
        }

        // Recurse into nested types
        foreach (var nested in type.GetTypeMembers())
        {
            ScanTypeForEnum(nested, results, processed, currentAssembly);
        }
    }

    private static void GenerateDisplayExtensions(SourceProductionContext context, ImmutableArray<EnumDisplayInfo> infos)
    {
        if (infos.IsDefaultOrEmpty) return;

        var grouped = infos.GroupBy(i => i.Namespace ?? string.Empty);

        foreach (var group in grouped)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");

            var namespaceName = group.Key;
            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName};");
                sb.AppendLine();
            }

            foreach (var info in group)
            {
                WriteEnumExtension(sb, info);
            }

            var fileName = string.IsNullOrEmpty(namespaceName)
                ? "EnumDisplayExtensions.g.cs"
                : $"{namespaceName}.EnumDisplayExtensions.g.cs";

            context.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }

    private static void WriteEnumExtension(StringBuilder sb, EnumDisplayInfo info)
    {
        sb.AppendLine($"public static partial class {info.TypeName}DisplayExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string GetDisplayName(this {info.FullTypeName} value) => value switch");
        sb.AppendLine("    {");

        foreach (var (name, displayName) in info.Members)
        {
            sb.AppendLine($"        {info.FullTypeName}.{name} => \"{EscapeString(displayName)}\",");
        }

        sb.AppendLine($"        _ => value.ToString()");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string EscapeString(string s) => s.Replace("\"", "\\\"");

    private sealed record EnumDisplayInfo(
        string TypeName,
        string FullTypeName,
        string? Namespace,
        List<(string Name, string DisplayName)> Members
    );
}
