<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CrestCreates.JsonContracts.Tool</AssemblyName>
    <RootNamespace>CrestCreates.JsonContracts.BuildTasks</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseAppHost>false</UseAppHost>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CrestCreates.JsonContracts.BuildTasks.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\CrestCreates.Core.Abstractions\CrestCreates.Core.Abstractions.csproj" PrivateAssets="all" />
  </ItemGroup>

</Project>
