using System;
using System.Collections.Immutable;
using CrestCreates.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CrestCreates.CodeAnalyzer
{
    /// <summary>
    /// 通用增量生成器抽象基类
    /// </summary>
    public abstract class CommonIncrementalGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// 获取生成器名称
        /// </summary>
        /// <summary>
        /// Gets the name of the generator.
        /// </summary>
        protected abstract string GeneratorName { get; }

        /// <summary>
        /// Gets the name of the attribute to be generated.
        /// </summary>
        protected abstract string ClassAttributeName { get; }

        /// <summary>
        /// Gets the name of the class to be generated.
        /// </summary>
        protected abstract string GeneratedClassName { get; }

        /// <summary>
        /// 获取生成的属性源代码
        /// </summary>
        protected abstract string GetAttributeSource();

        /// <summary>
        /// 分析类是否满足生成条件
        /// </summary>
        protected abstract ClassAnalysisInfo? AnalyzeClass(GeneratorSyntaxContext context);

        /// <summary>
        /// 过滤出符合条件的类
        /// </summary>
        protected abstract bool FilterClass(ClassAnalysisInfo? info);

        /// <summary>
        /// 生成调试信息
        /// </summary>
        protected abstract string GenerateDebugInfo();

        /// <summary>
        /// 生成调试报告
        /// </summary>
        protected abstract void GenerateDebugReport(Compilation compilation, ImmutableArray<ClassAnalysisInfo?> classes,
            SourceProductionContext context);

        /// <summary>
        /// 执行代码生成
        /// </summary>
        protected abstract void Execute(Compilation compilation, ImmutableArray<ClassAnalysisInfo> classes,
            SourceProductionContext context);

        /// <summary>
        /// 初始化生成器
        /// </summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var attrSource = GetAttributeSource();
            if (!string.IsNullOrEmpty(attrSource))
            {
                // 添加生成的属性
                context.RegisterPostInitializationOutput(ctx =>
                    ctx.AddSource($"{ClassAttributeName}.g.cs", GetAttributeSource()));
            }


#if DEBUG
            var debugInfo = GenerateDebugInfo();
            if (!string.IsNullOrEmpty(debugInfo))
            {
                // 添加调试信息生成
                context.RegisterPostInitializationOutput(ctx =>
                    ctx.AddSource($"{GeneratorName}Debug.g.cs", GenerateDebugInfo()));
            }
#endif

            // 查找所有类并进行分析
            var allClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, ct) => AnalyzeClass(ctx))
                .Where(info => info is not null);

            // 过滤出符合条件的类
            var filteredClasses = allClasses.Where(info => FilterClass(info));

            // 收集编译信息
            var compilationAndClasses = context.CompilationProvider.Combine(filteredClasses.Collect());

#if DEBUG
            // 生成调试报告
            context.RegisterSourceOutput(compilationAndClasses,
                (spc, source) => GenerateDebugReport(source.Left, source.Right!, spc));
#endif

            // 生成代码
            context.RegisterSourceOutput(compilationAndClasses,
                (spc, source) => Execute(source.Left, source.Right!, spc));
        }

        /// <summary>
        /// 生成包含时间戳的调试信息
        /// </summary>
        protected string GenerateDefaultDebugInfo(string namespaceName)
        {
            return $@"// <auto-generated/>
                      // This file contains debug information for the {GeneratorName}
                      
                      using System;
                      
                      namespace {namespaceName}
                      {{
                          public static class {GeneratorName}DebugInfo
                          {{
                              public static readonly string GeneratedAt = ""{DateTimeOffset.Now.ToString()}"";
                              public static readonly string Message = ""{GeneratorName} is working"";
                          }}
                      }}";
        }
    }
}