using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.TenantFilterGenerator
{
    [Generator]
    public class TenantFilterSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var multiTenantEntities = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsMultiTenantCandidate(node),
                    transform: static (ctx, _) => GetMultiTenantClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            context.RegisterSourceOutput(multiTenantEntities, ExecuteGeneration);
        }

        private static bool IsMultiTenantCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetMultiTenantClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null) return null;

            bool hasEntityAttr = symbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "EntityAttribute" || attr.AttributeClass?.Name == "Entity");

            if (!hasEntityAttr) return null;

            bool implementsMultiTenant = ImplementsInterface(symbol, "IMultiTenant");

            if (!implementsMultiTenant) return null;

            return symbol;
        }

        private static bool ImplementsInterface(INamedTypeSymbol symbol, string interfaceName)
        {
            foreach (var iface in symbol.AllInterfaces)
            {
                if (iface.Name == interfaceName)
                    return true;
            }
            return false;
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> entities)
        {
            if (entities.IsDefaultOrEmpty) return;

            var processed = new HashSet<string>();
            var entityList = new List<INamedTypeSymbol>();

            foreach (var entity in entities)
            {
                if (entity == null) continue;
                var fullName = entity.ToDisplayString();
                if (processed.Contains(fullName)) continue;
                processed.Add(fullName);
                entityList.Add(entity);
            }

            if (entityList.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
            sb.AppendLine("using CrestCreates.MultiTenancy.Abstract;");
            sb.AppendLine();
            sb.AppendLine("namespace CrestCreates.OrmProviders.EFCore.MultiTenancy");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class TenantFilterConfiguration");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void ApplyAll(ModelBuilder modelBuilder, ICurrentTenant currentTenant)");
            sb.AppendLine("        {");

            foreach (var entity in entityList)
            {
                sb.AppendLine($"            Configure{entity.Name}Filter(modelBuilder, currentTenant);");
            }

            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var entity in entityList)
            {
                var entityName = entity.Name;
                var entityFullName = entity.ToDisplayString();
                sb.AppendLine($"        private static void Configure{entityName}Filter(ModelBuilder modelBuilder, ICurrentTenant currentTenant)");
                sb.AppendLine("        {");
                sb.AppendLine($"            modelBuilder.Entity<{entityFullName}>().HasQueryFilter(e =>");
                sb.AppendLine("                currentTenant.Id == null || e.TenantId == currentTenant.Id);");
                sb.AppendLine($"            modelBuilder.Entity<{entityFullName}>().HasIndex(e => e.TenantId)");
                sb.AppendLine($"                .HasDatabaseName(\"IX_{entityName}_TenantId\");");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TenantFilter.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
