using CrestCreates.JsonContracts.BuildTasks.Generation;
using CrestCreates.JsonContracts.BuildTasks.Model;
using CrestCreates.JsonContracts.BuildTasks.Tests.Infrastructure;
using FluentAssertions;

namespace CrestCreates.JsonContracts.BuildTasks.Tests.Generation;

/// <summary>Case IDs: C01, C02, B17, B18, F08</summary>
public class JsonContractSourceWriterTests : JsonContractCompilationTestBase
{
    [Fact]
    public void Write_IsByteStable()
    {
        var source = JsonContractTestSources.MinimalContext();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output1 = JsonContractSourceWriter.WriteContextSource(result.Model!);
        var output2 = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output1.Should().Be(output2);
    }

    [Fact]
    public void Write_DoesNotContainPathOrTimestamp()
    {
        var source = JsonContractTestSources.MinimalContext();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().NotContain("Generated on");
        output.Should().NotContain("Timestamp");
        output.Should().NotContain("Path");
        output.Should().NotContain("Version");
    }

    [Fact]
    public void Write_MultipleContextsAreIsolatedAndSorted()
    {
        var source = JsonContractTestSources.MultipleContextProject();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("FirstContext");
        output.Should().Contain("SecondContext");

        var firstIndex = output.IndexOf("FirstContext", StringComparison.Ordinal);
        var secondIndex = output.IndexOf("SecondContext", StringComparison.Ordinal);
        firstIndex.Should().BeLessThan(secondIndex);
    }

    [Fact]
    public void Write_InternalManifestAccessibility()
    {
        var source = JsonContractTestSources.MinimalContext();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("internal static class");
        output.Should().Contain("internal static global::System.Collections.Generic.IReadOnlySet<global::System.Type>");
    }

    [Fact]
    public void Write_PublicManifestAccessibility()
    {
        var source = (Path: "PublicManifest.cs", Text: @"
using System.Text.Json.Serialization;
using CrestCreates.Core.Abstractions.Serialization;
using System.Threading.Tasks;

public record PublicDto(string Value);

public interface IPublicService
{
    Task<PublicDto> GetAsync(System.Threading.CancellationToken ct);
}

[JsonContractSurface(typeof(IPublicService), ManifestAccessibility = ManifestAccessibility.Public)]
public partial class PublicContext : JsonSerializerContext { }");
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var ctx = result.Model!.Contexts[0];
        ctx.ManifestAccessibility = JsonContractManifestAccessibility.Public;

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("public static class");
        output.Should().Contain("public static global::System.Collections.Generic.IReadOnlySet<global::System.Type>");
    }

    [Fact]
    public void Build_NoMarkedContextWritesDeterministicEmptyOutput()
    {
        var source = JsonContractTestSources.NoMarkedContext();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("// <auto-generated />");
        output.Should().Contain("#nullable enable");
        output.Should().NotContain("namespace");
        output.Should().NotContain("class");
    }

    [Fact]
    public void Write_GeneratesJsonSerializableForSurfaceRoots()
    {
        var source = JsonContractTestSources.InheritedSurface();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("[global::System.Text.Json.Serialization.JsonSerializable(typeof(global::System.String))]");
        output.Should().Contain("[global::System.Text.Json.Serialization.JsonSerializable(typeof(global::System.Int32))]");
    }

    [Fact]
    public void Write_DoesNotGenerateJsonSerializableForExplicitExtras()
    {
        var source = (Path: "ExplicitExtraWriter.cs", Text: @"
using System.Text.Json.Serialization;
using CrestCreates.Core.Abstractions.Serialization;
using System.Threading.Tasks;

public record SurfaceDto(string Value);
public record ExtraDto(int Count);

public interface ISurfaceService
{
    Task<SurfaceDto> GetAsync(System.Threading.CancellationToken ct);
}

[JsonContractSurface(typeof(ISurfaceService))]
[JsonSerializable(typeof(ExtraDto))]
public partial class ExplicitExtraWriterContext : JsonSerializerContext { }");
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("JsonSerializable(typeof(global::SurfaceDto))");
        output.Should().NotContain("JsonSerializable(typeof(global::ExtraDto))");
    }

    [Fact]
    public void Write_ContainsManifestWithFrozenSets()
    {
        var source = JsonContractTestSources.MinimalContext();
        var refs = GetDefaultReferences();
        var result = JsonContractTestHelper.BuildModel("TestAssembly", [source], refs);

        var output = JsonContractSourceWriter.WriteContextSource(result.Model!);

        output.Should().Contain("FrozenSet<global::System.Type>");
        output.Should().Contain("SurfaceRootTypes");
        output.Should().Contain("ExplicitRootTypes");
        output.Should().Contain("AllDirectRootTypes");
        output.Should().Contain("RootManifest");
    }
}
