using System.Text;

namespace CrestCreates.CodeGenerator.McpToolGenerator;

internal static class McpToolProviderEmitter
{
    public static string Emit(McpToolContainerModel container)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using CrestCreates.Metadata;");
        builder.AppendLine("using CrestCreates.Metadata.Abstractions;");
        builder.AppendLine("using CrestCreates.Metadata.Mcp;");
        if (container.Namespace.Length > 0)
            builder.AppendLine("namespace " + container.Namespace + ";");
        builder.AppendLine("internal sealed class " + container.Name + "_GeneratedMcpToolProvider : IDescriptorProvider<McpToolDescriptor>");
        builder.AppendLine("{");
        builder.AppendLine("    public IReadOnlyList<McpToolDescriptor> GetDescriptors() => new McpToolDescriptor[]");
        builder.AppendLine("    {");
        foreach (var spec in container.Specs)
        {
            builder.AppendLine("        new McpToolDescriptor");
            builder.AppendLine("        {");
            builder.AppendLine("            Id = \"" + Escape(spec.DescriptorId) + "\",");
            builder.AppendLine("            Name = \"" + Escape(spec.SpecName) + "\",");
            builder.AppendLine("            Version = " + spec.DescriptorVersion + ",");
            builder.AppendLine("            Capability = new McpCapabilityReference(");
            builder.AppendLine("                \"" + Escape(spec.CapabilityId) + "\", " + spec.CapabilityVersion + ", VersionSelectionMode."
                + (spec.CapabilityVersion == 0 ? "Latest" : "Exact") + "),");
            builder.AppendLine("            ToolName = \"" + Escape(spec.ToolName) + "\",");
            if (spec.Title is not null)
                builder.AppendLine("            Title = \"" + Escape(spec.Title) + "\",");
            builder.AppendLine("            Description = \"" + Escape(spec.Description) + "\",");
            builder.AppendLine("            AnnotationOverrides = new McpToolAnnotationOverrides");
            builder.AppendLine("            {");
            builder.AppendLine("                DestructiveHint = " + Hint(spec.DestructiveHint) + ",");
            builder.AppendLine("                IdempotentHint = " + Hint(spec.IdempotentHint) + ",");
            builder.AppendLine("                OpenWorldHint = " + Hint(spec.OpenWorldHint));
            builder.AppendLine("            }");
            builder.AppendLine("        },");
        }
        builder.AppendLine("    };");
        builder.AppendLine("}");
        builder.AppendLine("internal static class " + container.Name + "_GeneratedMcpToolProviderRegistration");
        builder.AppendLine("{");
        builder.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register() => DescriptorProviderRegistry.Register<McpToolDescriptor>(");
        builder.AppendLine("        new " + container.Name + "_GeneratedMcpToolProvider());");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Hint(int value) => value == 1 ? "false" : value == 2 ? "true" : "null";

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
