using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace CrestCreates.BuildTasks;

public class GenerateAggregatedModuleCode : Microsoft.Build.Utilities.Task
{
    [Required]
    public string ModuleManifestFile { get; set; } = string.Empty;

    [Required]
    public string OutputPath { get; set; } = string.Empty;

    [Required]
    public string Namespace { get; set; } = string.Empty;

    public override bool Execute()
    {
        try
        {
            if (!File.Exists(ModuleManifestFile))
            {
                Log.LogError($"Module manifest file not found: {ModuleManifestFile}");
                return false;
            }

            var json = File.ReadAllText(ModuleManifestFile);
            var modules = JsonSerializer.Deserialize<List<ModuleManifest>>(json);
            if (modules == null || modules.Count == 0)
            {
                Log.LogWarning("No modules found in manifest file");
                return true;
            }

            var sortedModules = TopologicalSort(modules);
            var code = GenerateCode(sortedModules);

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(OutputPath, code);
            Log.LogMessage(MessageImportance.High, $"Generated aggregated module code at {OutputPath} with {sortedModules.Count} modules");

            return true;
        }
        catch (Exception ex)
        {
            Log.LogErrorFromException(ex);
            return false;
        }
    }

    private List<ModuleManifest> TopologicalSort(List<ModuleManifest> modules)
    {
        var sorted = new List<ModuleManifest>();
        var visited = new HashSet<string>();
        var visiting = new HashSet<string>();

        foreach (var module in modules.OrderBy(m => m.Order))
        {
            if (!visited.Contains(module.FullName))
            {
                Visit(module, modules, visited, visiting, sorted);
            }
        }

        return sorted;
    }

    private void Visit(ModuleManifest module, List<ModuleManifest> allModules,
        HashSet<string> visited, HashSet<string> visiting, List<ModuleManifest> sorted)
    {
        if (visited.Contains(module.FullName)) return;
        if (visiting.Contains(module.FullName))
        {
            Log.LogWarning($"Circular dependency detected involving {module.FullName}");
            return;
        }

        visiting.Add(module.FullName);

        foreach (var depName in module.DependsOn)
        {
            var dep = allModules.FirstOrDefault(m => m.Name == depName || m.FullName == depName);
            if (dep != null && !visited.Contains(dep.FullName))
            {
                Visit(dep, allModules, visited, visiting, sorted);
            }
        }

        visiting.Remove(module.FullName);
        visited.Add(module.FullName);
        sorted.Add(module);
    }

    private string GenerateCode(List<ModuleManifest> modules)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file is auto-generated by CrestCreates.BuildTasks");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using CrestCreates.Modularity;");
        sb.AppendLine("using CrestCreates.ModuleDiagnostics.Stores;");
        sb.AppendLine("using CrestCreates.ModuleDiagnostics.Timing;");
        sb.AppendLine("using CrestCreates.ModuleDiagnostics.Modules;");
        sb.AppendLine();

        sb.AppendLine("internal static partial class ModuleAutoInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly List<ModuleDescriptor> _registeredModules = new();");
        sb.AppendLine("    private static readonly object _lock = new();");
        sb.AppendLine("    private static bool _isInitialized;");
        sb.AppendLine();
        sb.AppendLine("    private static readonly ModuleDiagnosticsStore _diagnostics = ModuleDiagnosticsServiceCollectionExtensions.Store;");
        sb.AppendLine();

        sb.AppendLine("    public static IHostBuilder RegisterModules(this IHostBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.ConfigureServices((context, services) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            RegisterAllModules(services);");
        sb.AppendLine("        });");
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public static IServiceCollection RegisterAllModules(IServiceCollection services)");
        sb.AppendLine("    {");

        // DI registration (no diagnostics needed — these are instantiated later)
        foreach (var module in modules)
        {
            sb.AppendLine($"        services.AddSingleton<{module.FullName}>();");
        }

        sb.AppendLine();

        // ConfigureServices phase — wrapped with diagnostics
        for (var i = 0; i < modules.Count; i++)
        {
            var module = modules[i];
            if (module.AutoRegisterServices)
            {
                var moduleName = module.FullName;
                sb.AppendLine($"        // ModuleDiagnostics: {moduleName} → ConfigureServices");
                sb.AppendLine($"        var _csTimer{i} = ModulePhaseTimer.StartNew(\"{moduleName}\", \"ConfigureServices\");");
                sb.AppendLine($"        try");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            new {moduleName}().OnConfigureServices(services);");
                sb.AppendLine($"            _diagnostics.Record(_csTimer{i}.Stop(ModulePhaseStatus.Success));");
                sb.AppendLine($"        }}");
                sb.AppendLine($"        catch (System.Exception ex)");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            _diagnostics.Record(_csTimer{i}.StopFailed(ex));");
                sb.AppendLine($"            throw;");
                sb.AppendLine($"        }}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        lock (_lock)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_isInitialized)");
        sb.AppendLine("                return services;");
        sb.AppendLine();
        sb.AppendLine("            _registeredModules.Clear();");

        foreach (var module in modules)
        {
            sb.AppendLine($"            _registeredModules.Add(new ModuleDescriptor(typeof({module.FullName}), {module.Order}, {(module.AutoRegisterServices ? "true" : "false")}));");
        }

        sb.AppendLine();
        sb.AppendLine("            _isInitialized = true;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public static IReadOnlyList<ModuleDescriptor> RegisteredModules => _registeredModules;");
        sb.AppendLine();
        sb.AppendLine("    public static async Task InitializeAllModulesAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("    {");

        // PreInit phase — resolve from DI and call with diagnostics
        for (var i = 0; i < modules.Count; i++)
        {
            var module = modules[i];
            var moduleName = module.FullName;
            sb.AppendLine($"        // ModuleDiagnostics: {moduleName} → PreInit");
            sb.AppendLine($"        var _preInitTimer{i} = ModulePhaseTimer.StartNew(\"{moduleName}\", \"PreInit\");");
            sb.AppendLine($"        var _preInitModule{i} = serviceProvider.GetService<{moduleName}>();");
            sb.AppendLine($"        try");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            if (_preInitModule{i} != null) await _preInitModule{i}.OnPreInitializeAsync();");
            sb.AppendLine($"            _diagnostics.Record(_preInitTimer{i}.Stop(ModulePhaseStatus.Success));");
            sb.AppendLine($"        }}");
            sb.AppendLine($"        catch (System.Exception ex)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            _diagnostics.Record(_preInitTimer{i}.StopFailed(ex));");
            sb.AppendLine($"            throw;");
            sb.AppendLine($"        }}");
        }

        sb.AppendLine();
        sb.AppendLine("        var sortedModules = _registeredModules.OrderBy(m => m.Order).ToList();");

        // Init phase
        for (var i = 0; i < modules.Count; i++)
        {
            var module = modules[i];
            var moduleName = module.FullName;
            sb.AppendLine($"        // ModuleDiagnostics: {moduleName} → Init");
            sb.AppendLine($"        var _initTimer{i} = ModulePhaseTimer.StartNew(\"{moduleName}\", \"Init\");");
            sb.AppendLine($"        try");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            if (_preInitModule{i} != null) await _preInitModule{i}.OnInitializeAsync();");
            sb.AppendLine($"            _diagnostics.Record(_initTimer{i}.Stop(ModulePhaseStatus.Success));");
            sb.AppendLine($"        }}");
            sb.AppendLine($"        catch (System.Exception ex)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            _diagnostics.Record(_initTimer{i}.StopFailed(ex));");
            sb.AppendLine($"            throw;");
            sb.AppendLine($"        }}");
        }

        sb.AppendLine();

        // PostInit phase — uses sortedModules
        sb.AppendLine("        foreach (var module in sortedModules)");
        sb.AppendLine("        {");
        sb.AppendLine("            // ModuleDiagnostics: module.ModuleType.Name → PostInit");
        sb.AppendLine("            var _postInitTimer = ModulePhaseTimer.StartNew(module.ModuleType.Name, \"PostInit\");");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                if (serviceProvider.GetService(module.ModuleType) is IModule moduleInstance)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await moduleInstance.OnPostInitializeAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("                _diagnostics.Record(_postInitTimer.Stop(ModulePhaseStatus.Success));");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (System.Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _diagnostics.Record(_postInitTimer.StopFailed(ex));");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public static async Task<IHost> InitializeModulesAsync(this IHost host)");
        sb.AppendLine("    {");
        sb.AppendLine("        var logger = host.Services.GetService<ILogger<IModule>>();");
        sb.AppendLine("        await InitializeAllModulesAsync(host.Services);");
        sb.AppendLine();

        // AppInit phase
        sb.AppendLine("        foreach (var module in _registeredModules.OrderBy(m => m.Order))");
        sb.AppendLine("        {");
        sb.AppendLine("            // ModuleDiagnostics: module.ModuleType.Name → AppInit");
        sb.AppendLine("            var _appInitTimer = ModulePhaseTimer.StartNew(module.ModuleType.Name, \"AppInit\");");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                if (host.Services.GetService(module.ModuleType) is IModule moduleInstance)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await moduleInstance.OnApplicationInitializationAsync(host);");
        sb.AppendLine("                }");
        sb.AppendLine("                _diagnostics.Record(_appInitTimer.Stop(ModulePhaseStatus.Success));");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (System.Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                _diagnostics.Record(_appInitTimer.StopFailed(ex));");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Summary log output
        sb.AppendLine("        // ModuleDiagnostics Summary");
        sb.AppendLine("        if (logger != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var diag in _diagnostics.GetAll())");
        sb.AppendLine("            {");
        sb.AppendLine("                var status = diag.Status == ModulePhaseStatus.Success ? \"OK\" : \"FAILED\";");
        sb.AppendLine("                if (diag.Status == ModulePhaseStatus.Failed)");
        sb.AppendLine("                {");
        sb.AppendLine("                    logger.LogError(\"[ModuleDiagnostics] {Module} → {Phase}: {Status} ({Elapsed}ms) Error: {Error}\",");
        sb.AppendLine("                        diag.ModuleName, diag.Phase, status, diag.Elapsed.TotalMilliseconds.ToString(\"F2\"), diag.ErrorMessage);");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine("                    logger.LogInformation(\"[ModuleDiagnostics] {Module} → {Phase}: {Status} ({Elapsed}ms)\",");
        sb.AppendLine("                        diag.ModuleName, diag.Phase, status, diag.Elapsed.TotalMilliseconds.ToString(\"F2\"));");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        return host;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public class ModuleManifest
    {
        public string FullName { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string Namespace { get; set; } = string.Empty;
        public List<string> DependsOn { get; set; } = new();
        public int Order { get; set; }
        public bool AutoRegisterServices { get; set; }
    }
}
