using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

namespace CrestCreates.CodeGenerator.EntityGenerator
{
    /// <summary>
    /// 模板管理器，用于加载和处理代码生成模板
    /// </summary>
    public static class TemplateManager
    {
        private static readonly Dictionary<string, string> _templates = new();

        static TemplateManager()
        {
            LoadTemplates();
        }

        private static void LoadTemplates()
        {
            try
            {
                var assembly = Assembly.GetExecutingAssembly();
                var templateNames = new[]
                {
                    "RepositoryInterfaceTemplate.cs",
                    "EfCoreRepositoryTemplate.cs", 
                    "EfCoreMappingTemplate.cs",
                    "QueryExtensionsTemplate.cs"
                };

                foreach (var templateName in templateNames)
                {
                    var resourceName = $"CrestCreates.CodeGenerator.Templates.{templateName}";
                    using var stream = assembly.GetManifestResourceStream(resourceName);
                    if (stream != null)
                    {
                        using var reader = new StreamReader(stream);
                        _templates[templateName] = reader.ReadToEnd();
                    }
                }
            }
            catch
            {
                // 如果无法从资源加载，则使用内置模板
                LoadFallbackTemplates();
            }
        }

        private static void LoadFallbackTemplates()
        {
            _templates["RepositoryInterfaceTemplate.cs"] = GetRepositoryInterfaceTemplate();
            _templates["EfCoreRepositoryTemplate.cs"] = GetEfCoreRepositoryTemplate();
            _templates["EfCoreMappingTemplate.cs"] = GetEfCoreMappingTemplate();
            _templates["QueryExtensionsTemplate.cs"] = GetQueryExtensionsTemplate();
        }

        public static string GetTemplate(string templateName)
        {
            return _templates.TryGetValue(templateName, out var template) ? template : string.Empty;
        }

        public static string ProcessTemplate(string template, Dictionary<string, string> replacements)
        {
            var result = template;
            foreach (var replacement in replacements)
            {
                result = result.Replace($"{{{{{replacement.Key}}}}}", replacement.Value);
            }
            return result;
        }

        private static string GetRepositoryInterfaceTemplate()
        {
            return @"#nullable enable
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using CrestCreates.Domain.Repositories;
using {{NAMESPACE}};

namespace {{NAMESPACE}}.Repositories
{
    /// <summary>
    /// {{ENTITY_NAME}} 实体的仓储接口
    /// </summary>
    public partial interface I{{ENTITY_NAME}}Repository : IRepository<{{ENTITY_NAME}}, {{ID_TYPE}}>
    {
        {{QUERY_METHODS}}

        // 分页查询方法
        Task<(List<{{ENTITY_NAME}}> Items, int TotalCount)> GetPagedListAsync(
            int pageNumber, 
            int pageSize, 
            Expression<Func<{{ENTITY_NAME}}, bool>>? predicate = null,
            Expression<Func<{{ENTITY_NAME}}, object>>? orderBy = null,
            bool ascending = true,
            CancellationToken cancellationToken = default);

        {{SOFT_DELETE_METHODS}}
    }
}";
        }

        private static string GetEfCoreRepositoryTemplate()
        {
            return @"#nullable enable
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CrestCreates.Infrastructure.Providers.EFCore.Repositories;
using CrestCreates.Infrastructure.Providers.EFCore.DbContexts;
using {{NAMESPACE}};
using {{NAMESPACE}}.Repositories;

namespace {{NAMESPACE}}.EntityFrameworkCore.Repositories
{
    /// <summary>
    /// {{ENTITY_NAME}} 实体的 EF Core 仓储实现
    /// </summary>
    public class EfCore{{ENTITY_NAME}}Repository : EfCoreRepository<{{ENTITY_NAME}}, {{ID_TYPE}}>, I{{ENTITY_NAME}}Repository
    {
        public EfCore{{ENTITY_NAME}}Repository(CrestCreatesDbContext dbContext) 
            : base(dbContext)
        {
        }

        {{REPOSITORY_METHODS}}
    }
}";
        }

        private static string GetEfCoreMappingTemplate()
        {
            return @"#nullable enable
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using {{NAMESPACE}};

namespace {{NAMESPACE}}.EntityFrameworkCore.Mappings
{
    /// <summary>
    /// {{ENTITY_NAME}} 实体的 EF Core 映射配置
    /// </summary>
    public class {{ENTITY_NAME}}Mapping : IEntityTypeConfiguration<{{ENTITY_NAME}}>
    {
        public void Configure(EntityTypeBuilder<{{ENTITY_NAME}}> builder)
        {
            builder.ToTable(""{{TABLE_NAME}}"");
            
            builder.HasKey(e => e.Id);
            
            {{PROPERTY_MAPPINGS}}
            
            {{AUDIT_MAPPINGS}}
            
            {{INDEX_MAPPINGS}}
        }
    }
}";
        }

        private static string GetQueryExtensionsTemplate()
        {
            return @"#nullable enable
// <auto-generated />
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq.Expressions;
using {{NAMESPACE}};

namespace {{NAMESPACE}}.Extensions
{
    /// <summary>
    /// {{ENTITY_NAME}} 实体的查询扩展方法
    /// </summary>
    public static class {{ENTITY_NAME}}QueryExtensions
    {
        /// <summary>
        /// 分页查询
        /// </summary>
        public static IQueryable<{{ENTITY_NAME}}> PageBy(this IQueryable<{{ENTITY_NAME}}> query, int pageNumber, int pageSize)
        {
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 10;
            return query.Skip((pageNumber - 1) * pageSize).Take(pageSize);
        }
        
        /// <summary>
        /// 条件查询
        /// </summary>
        public static IQueryable<{{ENTITY_NAME}}> WhereIf(this IQueryable<{{ENTITY_NAME}}> query, bool condition, Expression<Func<{{ENTITY_NAME}}, bool>> predicate)
        {
            return condition ? query.Where(predicate) : query;
        }

        {{AUDIT_EXTENSIONS}}

        {{SOFT_DELETE_EXTENSIONS}}

        {{PROPERTY_EXTENSIONS}}
    }
}";
        }
    }
}