using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.EntityGenerator
{
    [Generator]
    public class EntitySourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 创建增量数据源：查找带有EntityAttribute的类
            var entityClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsEntityCandidate(node),
                    transform: static (ctx, _) => GetEntityClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            // 注册源代码生成
            context.RegisterSourceOutput(entityClasses, ExecuteGeneration);
        }

        private static bool IsEntityCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetEntityClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && HasEntityAttribute(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private static bool HasEntityAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "EntityAttribute" ||
                attr.AttributeClass?.Name == "Entity");
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> entityClasses)
        {
            if (entityClasses.IsDefaultOrEmpty)
                return;

            // 去重处理
            var processedEntities = new HashSet<string>();

            foreach (var entityClass in entityClasses)
            {
                if (entityClass == null) continue;

                var entityFullName = entityClass.ToDisplayString();
                if (processedEntities.Contains(entityFullName))
                    continue;

                processedEntities.Add(entityFullName);

                try
                {
                    // 生成仓储接口和实现
                    if (HasAttribute(entityClass, "EntityAttribute") &&
                        GetAttributeProperty(entityClass, "GenerateRepository", true))
                    {
                        GenerateRepositoryInterface(context, entityClass);
                        GenerateRepositoryImplementation(context, entityClass);
                    }

                    // 生成查询扩展
                    GenerateQueryExtensions(context, entityClass);

                    // 生成ORM映射
                    GenerateOrmMappings(context, entityClass);

                    // 生成DTO映射
                    GenerateDtoMappings(context, entityClass);

                    // 生成实体扩展方法
                    GenerateEntityExtensions(context, entityClass);

                    // 生成验证规则
                    GenerateValidationRules(context, entityClass);
                }
                catch (Exception ex)
                {
                    // 记录错误但继续处理其他实体
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("CCCG001", "Code generation error",
                            $"Error generating code for {entityFullName}: {ex.Message}",
                            "CodeGeneration", DiagnosticSeverity.Warning, true),
                        Location.None));
                }
            }
        }        private void GenerateRepositoryInterface(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var idType = GetEntityIdType(entityClass);
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();

            var sourceCode = $@"
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using CrestCreates.Domain.Repositories;
using {namespaceName};

namespace {namespaceName}.Repositories
{{
    /// <summary>
    /// {entityName} 实体的仓储接口
    /// </summary>
    public partial interface I{entityName}Repository : IRepository<{entityName}, {idType}>
    {{
        // 基于实体属性的查询方法
        {GenerateRepositoryQueryMethods(entityClass)}

        // 分页查询方法
        Task<(List<{entityName}> Items, int TotalCount)> GetPagedListAsync(
            int pageNumber, 
            int pageSize, 
            Expression<Func<{entityName}, bool>>? predicate = null,
            Expression<Func<{entityName}, object>>? orderBy = null,
            bool ascending = true,
            CancellationToken cancellationToken = default);

        // 软删除相关方法（如果支持）
        {(IsFullyAudited(entityClass) ? GenerateSoftDeleteMethods(entityName, idType) : string.Empty)}
    }}
}}";

            context.AddSource($"I{entityName}Repository.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        private void GenerateRepositoryImplementation(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var idType = GetEntityIdType(entityClass);
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var ormProvider = GetAttributeProperty(entityClass, "OrmProvider", "EfCore");

            if (ormProvider == "EfCore")
            {
                var sourceCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using CrestCreates.Infrastructure.Providers.EFCore.Repositories;
using CrestCreates.Infrastructure.Providers.EFCore.DbContexts;
using {namespaceName};
using {namespaceName}.Repositories;

namespace {namespaceName}.EntityFrameworkCore.Repositories
{{
    public class EfCore{entityName}Repository : EfCoreRepository<{entityName}, {idType}>, I{entityName}Repository
    {{
        public EfCore{entityName}Repository(CrestCreatesDbContext dbContext) 
            : base(dbContext)
        {{
        }}
        
        // 可以实现自定义扩展方法
    }}
}}";

                context.AddSource($"EfCore{entityName}Repository.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            else if (ormProvider == "SqlSugar")
            {
                var sourceCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using SqlSugar;
using CrestCreates.Infrastructure.Providers.SqlSugar.Repositories;
using {namespaceName};
using {namespaceName}.Repositories;

namespace {namespaceName}.SqlSugar.Repositories
{{
    public class SqlSugar{entityName}Repository : SqlSugarRepository<{entityName}, {idType}>, I{entityName}Repository
    {{
        public SqlSugar{entityName}Repository(ISqlSugarClient sqlSugarClient) 
            : base(sqlSugarClient)
        {{
        }}
        
        // 可以实现自定义扩展方法
    }}
}}";

                context.AddSource($"SqlSugar{entityName}Repository.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            else if (ormProvider == "FreeSql")
            {
                var sourceCode = $@"
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using FreeSql;
using CrestCreates.Infrastructure.Providers.FreeSql.Repositories;
using {namespaceName};
using {namespaceName}.Repositories;

namespace {namespaceName}.FreeSql.Repositories
{{
    public class FreeSql{entityName}Repository : FreeSqlRepository<{entityName}, {idType}>, I{entityName}Repository
    {{
        public FreeSql{entityName}Repository(IFreeSql freeSql) 
            : base(freeSql)
        {{
        }}
        
        // 可以实现自定义扩展方法
    }}
}}";

                context.AddSource($"FreeSql{entityName}Repository.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
        }

        private void GenerateQueryExtensions(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetEntityProperties(entityClass);

            var sourceCode = $@"
// <auto-generated />
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq.Expressions;
using {namespaceName};

namespace {namespaceName}.Extensions
{{
    /// <summary>
    /// {entityName} 实体的查询扩展方法
    /// </summary>
    public static class {entityName}QueryExtensions
    {{
        /// <summary>
        /// 分页查询
        /// </summary>
        public static IQueryable<{entityName}> PageBy(this IQueryable<{entityName}> query, int pageNumber, int pageSize)
        {{
            if (pageNumber < 1) pageNumber = 1;
            if (pageSize < 1) pageSize = 10;
            return query.Skip((pageNumber - 1) * pageSize).Take(pageSize);
        }}
        
        /// <summary>
        /// 条件查询
        /// </summary>
        public static IQueryable<{entityName}> WhereIf(this IQueryable<{entityName}> query, bool condition, Expression<Func<{entityName}, bool>> predicate)
        {{
            return condition ? query.Where(predicate) : query;
        }}

        /// <summary>
        /// 按创建时间排序（如果支持审计）
        /// </summary>
        {(IsAudited(entityClass) ? GenerateAuditQueryExtensions(entityName) : string.Empty)}

        /// <summary>
        /// 软删除过滤（如果支持）
        /// </summary>
        {(IsFullyAudited(entityClass) ? GenerateSoftDeleteQueryExtensions(entityName) : string.Empty)}

        // 基于属性的查询扩展
        {GeneratePropertyQueryExtensions(entityName, properties)}
    }}
}}";

            context.AddSource($"{entityName}QueryExtensions.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }        private void GenerateOrmMappings(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var ormProvider = GetAttributeProperty(entityClass, "OrmProvider", "EfCore");
            var tableName = GetAttributeProperty<string?>(entityClass, "TableName", null) ?? $"{entityName}s";

            if (ormProvider == "EfCore")
            {
                var sourceCode = $@"
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using {namespaceName};

namespace {namespaceName}.EntityFrameworkCore.Mappings
{{
    /// <summary>
    /// {entityName} 实体的 EF Core 映射配置
    /// </summary>
    public class {entityName}Mapping : IEntityTypeConfiguration<{entityName}>
    {{
        public void Configure(EntityTypeBuilder<{entityName}> builder)
        {{
            builder.ToTable(""{tableName}"");
            
            builder.HasKey(e => e.Id);
            
            // 属性映射配置
            {GeneratePropertyMappings(entityClass, "EfCore")}
            
            // 审计字段映射
            {(IsAudited(entityClass) ? GenerateEfCoreAuditMappings() : string.Empty)}
            
            // 索引配置
            {GenerateIndexMappings(entityClass, "EfCore")}
        }}
    }}
}}";

                context.AddSource($"{entityName}Mapping.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            else if (ormProvider == "SqlSugar")
            {
                var sourceCode = $@"
// <auto-generated />
using SqlSugar;
using {namespaceName};

namespace {namespaceName}.SqlSugar.Mappings
{{
    /// <summary>
    /// {entityName} 实体的 SqlSugar 映射配置
    /// </summary>
    public static class {entityName}SugarMapping
    {{
        public static void Configure(CodeFirstProvider codeFirst)
        {{
            codeFirst.InitTables(typeof({entityName}));
        }}
        
        public static void ConfigureTable(ISqlSugarClient db)
        {{
            db.CodeFirst.InitTables<{entityName}>();
        }}

        public static void ConfigureEntity(EntityInfo entityInfo)
        {{
            if (entityInfo.EntityName == typeof({entityName}).Name)
            {{
                entityInfo.DbTableName = ""{tableName}"";
                
                // 属性映射配置
                {GeneratePropertyMappings(entityClass, "SqlSugar")}
            }}
        }}
    }}
}}";

                context.AddSource($"{entityName}SugarMapping.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            else if (ormProvider == "FreeSql")
            {
                var sourceCode = $@"
// <auto-generated />
using FreeSql;
using FreeSql.DataAnnotations;
using {namespaceName};

namespace {namespaceName}.FreeSql.Mappings
{{
    /// <summary>
    /// {entityName} 实体的 FreeSql 映射配置
    /// </summary>
    public static class {entityName}FreeSqlMapping
    {{
        public static void Configure(ICodeFirst codeFirst)
        {{
            codeFirst.Entity<{entityName}>(eb =>
            {{
                eb.ToTable(""{tableName}"");
                eb.HasKey(e => e.Id);
                
                // 属性映射配置
                {GeneratePropertyMappings(entityClass, "FreeSql")}
                
                // 审计字段映射
                {(IsAudited(entityClass) ? GenerateFreeSqlAuditMappings() : string.Empty)}
                
                // 索引配置
                {GenerateIndexMappings(entityClass, "FreeSql")}
            }});
        }}
    }}
}}";

                context.AddSource($"{entityName}FreeSqlMapping.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
        }

        private string GenerateAuditMappings()
        {
            return @"
            // 审计字段
            builder.Property(e => e.CreationTime).IsRequired();
            builder.Property(e => e.CreatorId).IsRequired(false);
            builder.Property(e => e.LastModificationTime).IsRequired(false);
            builder.Property(e => e.LastModifierId).IsRequired(false);";
        }

        private string GenerateEfCoreAuditMappings()
        {
            return @"
            // 审计字段映射
            builder.Property(e => e.CreationTime)
                .IsRequired()
                .HasDefaultValueSql(""GETUTCDATE()"");
                
            builder.Property(e => e.CreatorId)
                .IsRequired(false);
                
            builder.Property(e => e.LastModificationTime)
                .IsRequired(false);
                
            builder.Property(e => e.LastModifierId)
                .IsRequired(false);";
        }

        private string GenerateFreeSqlAuditMappings()
        {
            return @"
                // 审计字段映射
                eb.Property(e => e.CreationTime).IsRequired().HasDefaultValue(DateTime.UtcNow);
                eb.Property(e => e.CreatorId).IsRequired(false);
                eb.Property(e => e.LastModificationTime).IsRequired(false);
                eb.Property(e => e.LastModifierId).IsRequired(false);";
        }

        private bool IsAudited(INamedTypeSymbol entityClass)
        {
            // 检查实体是否继承了审计接口
            return entityClass.AllInterfaces.Any(i => i.Name == "IAuditedEntity" || i.Name == "IFullyAuditedEntity")
                   || GetAttributeProperty(entityClass, "GenerateAuditing", true);
        }

        private bool IsFullyAudited(INamedTypeSymbol entityClass)
        {
            // 检查实体是否继承了完全审计接口
            return entityClass.AllInterfaces.Any(i => i.Name == "IFullyAuditedEntity")
                   || entityClass.BaseType?.Name == "FullyAuditedEntity"
                   || entityClass.BaseType?.Name == "FullyAuditedAggregateRoot";
        }

        private string GetEntityIdType(INamedTypeSymbol entityClass)
        {
            // 尝试从Entity<TId>或AggregateRoot<TId>获取泛型参数
            var baseType = entityClass.BaseType;
            while (baseType != null)
            {
                if ((baseType.Name == "Entity" || baseType.Name == "AggregateRoot" ||
                     baseType.Name == "AuditedEntity" || baseType.Name == "AuditedAggregateRoot" ||
                     baseType.Name == "FullyAuditedEntity" || baseType.Name == "FullyAuditedAggregateRoot")
                    && baseType.TypeArguments.Length > 0)
                {
                    return baseType.TypeArguments[0].ToDisplayString();
                }

                baseType = baseType.BaseType;
            }

            // 默认返回int
            return "int";
        }

        private bool HasAttribute(ISymbol symbol, string attributeName)
        {
            return symbol.GetAttributes()
                .Any(attr => attr.AttributeClass?.Name == attributeName ||
                             attr.AttributeClass?.Name == attributeName + "Attribute");
        }

        private T GetAttributeProperty<T>(ISymbol symbol, string propertyName, T defaultValue)
        {
            var attr = symbol.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.Name == "EntityAttribute" ||
                                        attr.AttributeClass?.Name == "Entity");

            if (attr == null)
                return defaultValue;

            var namedArg = attr.NamedArguments
                .FirstOrDefault(arg => arg.Key == propertyName);

            if (namedArg.Key == propertyName && namedArg.Value.Value is T value)
                return value;

            return defaultValue;
        }

        // 新增的辅助方法
        private string GenerateRepositoryQueryMethods(INamedTypeSymbol entityClass)
        {
            var properties = GetEntityProperties(entityClass);
            var methods = new StringBuilder();

            foreach (var prop in properties)
            {
                if (prop.Type.SpecialType == SpecialType.System_String)
                {
                    methods.AppendLine($@"
        /// <summary>
        /// 根据 {prop.Name} 查找实体
        /// </summary>
        Task<List<{entityClass.Name}>> FindBy{prop.Name}Async(string {prop.Name.ToLowerInvariant()}, CancellationToken cancellationToken = default);");
                }
                else if (prop.Type.SpecialType != SpecialType.None)
                {
                    methods.AppendLine($@"
        /// <summary>
        /// 根据 {prop.Name} 查找实体
        /// </summary>
        Task<List<{entityClass.Name}>> FindBy{prop.Name}Async({prop.Type.ToDisplayString()} {prop.Name.ToLowerInvariant()}, CancellationToken cancellationToken = default);");
                }
            }

            return methods.ToString();
        }

        private string GenerateSoftDeleteMethods(string entityName, string idType)
        {
            return $@"
        /// <summary>
        /// 软删除实体
        /// </summary>
        Task SoftDeleteAsync({idType} id, CancellationToken cancellationToken = default);

        /// <summary>
        /// 恢复软删除的实体
        /// </summary>
        Task RestoreAsync({idType} id, CancellationToken cancellationToken = default);

        /// <summary>
        /// 获取未删除的实体列表
        /// </summary>
        Task<List<{entityName}>> GetNotDeletedAsync(CancellationToken cancellationToken = default);";
        }

        private string GenerateAuditQueryExtensions(string entityName)
        {
            return $@"
        public static IQueryable<{entityName}> OrderByCreationTime(this IQueryable<{entityName}> query, bool descending = false)
        {{
            return descending ? query.OrderByDescending(x => x.CreationTime) : query.OrderBy(x => x.CreationTime);
        }}

        public static IQueryable<{entityName}> CreatedAfter(this IQueryable<{entityName}> query, DateTime dateTime)
        {{
            return query.Where(x => x.CreationTime > dateTime);
        }}

        public static IQueryable<{entityName}> CreatedBefore(this IQueryable<{entityName}> query, DateTime dateTime)
        {{
            return query.Where(x => x.CreationTime < dateTime);
        }}";
        }

        private string GenerateSoftDeleteQueryExtensions(string entityName)
        {
            return $@"
        public static IQueryable<{entityName}> NotDeleted(this IQueryable<{entityName}> query)
        {{
            return query.Where(x => !x.IsDeleted);
        }}

        public static IQueryable<{entityName}> OnlyDeleted(this IQueryable<{entityName}> query)
        {{
            return query.Where(x => x.IsDeleted);
        }}";
        }

        private List<IPropertySymbol> GetEntityProperties(INamedTypeSymbol entityClass)
        {
            return entityClass.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                           !p.IsStatic &&
                           p.CanBeReferencedByName &&
                           p.Name != "Id") // 排除主键
                .ToList();
        }

        private string GeneratePropertyQueryExtensions(string entityName, List<IPropertySymbol> properties)
        {
            var extensions = new StringBuilder();

            foreach (var prop in properties)
            {
                if (prop.Type.SpecialType == SpecialType.System_String)
                {
                    extensions.AppendLine($@"
        public static IQueryable<{entityName}> By{prop.Name}(this IQueryable<{entityName}> query, string {prop.Name.ToLowerInvariant()})
        {{
            return query.Where(x => x.{prop.Name} == {prop.Name.ToLowerInvariant()});
        }}

        public static IQueryable<{entityName}> By{prop.Name}Contains(this IQueryable<{entityName}> query, string {prop.Name.ToLowerInvariant()})
        {{
            return query.Where(x => x.{prop.Name}.Contains({prop.Name.ToLowerInvariant()}));
        }}");
                }
                else if (prop.Type.SpecialType != SpecialType.None)
                {
                    extensions.AppendLine($@"
        public static IQueryable<{entityName}> By{prop.Name}(this IQueryable<{entityName}> query, {prop.Type.ToDisplayString()} {prop.Name.ToLowerInvariant()})
        {{
            return query.Where(x => x.{prop.Name} == {prop.Name.ToLowerInvariant()});
        }}");
                }
            }

            return extensions.ToString();
        }

        private string GeneratePropertyMappings(INamedTypeSymbol entityClass, string ormProvider)
        {
            var properties = GetEntityProperties(entityClass);
            var mappings = new StringBuilder();

            foreach (var prop in properties)
            {
                if (ormProvider == "EfCore")
                {
                    if (prop.Type.SpecialType == SpecialType.System_String)
                    {
                        mappings.AppendLine($@"
            builder.Property(e => e.{prop.Name})
                .HasMaxLength(255)
                .IsRequired({prop.NullableAnnotation != NullableAnnotation.Annotated});");
                    }
                }
            }

            return mappings.ToString();
        }

        private string GenerateIndexMappings(INamedTypeSymbol entityClass, string ormProvider)
        {
            // 为常用查询字段生成索引
            var properties = GetEntityProperties(entityClass);
            var indexes = new StringBuilder();

            if (ormProvider == "EfCore")
            {
                foreach (var prop in properties.Take(3)) // 只为前几个属性生成索引
                {
                    if (prop.Type.SpecialType == SpecialType.System_String)
                    {
                        indexes.AppendLine($@"
            builder.HasIndex(e => e.{prop.Name}).HasDatabaseName(""IX_{entityClass.Name}_{prop.Name}"");");
                    }
                }
            }

            return indexes.ToString();
        }

        // 生成DTO映射
        private void GenerateDtoMappings(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();

            var sourceCode = $@"
// <auto-generated />
using AutoMapper;
using {namespaceName};

namespace {namespaceName}.DTOs.Mappings
{{
    /// <summary>
    /// {entityName} 实体的 DTO 映射配置
    /// </summary>
    public class {entityName}MappingProfile : Profile
    {{
        public {entityName}MappingProfile()
        {{
            CreateMap<{entityName}, {entityName}Dto>().ReverseMap();
            CreateMap<{entityName}, Create{entityName}Dto>().ReverseMap();
            CreateMap<{entityName}, Update{entityName}Dto>().ReverseMap();
        }}
    }}
}}";

            context.AddSource($"{entityName}MappingProfile.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        // 生成实体扩展方法
        private void GenerateEntityExtensions(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();

            var sourceCode = $@"
// <auto-generated />
using System;
using {namespaceName};

namespace {namespaceName}.Extensions
{{
    /// <summary>
    /// {entityName} 实体的扩展方法
    /// </summary>
    public static class {entityName}Extensions
    {{
        /// <summary>
        /// 转换为摘要信息
        /// </summary>
        public static string ToSummary(this {entityName} entity)
        {{
            if (entity == null) return string.Empty;
            return $""{{entity.Id}} - {{entity.GetType().Name}}"";
        }}

        /// <summary>
        /// 克隆实体（不包含ID）
        /// </summary>
        public static {entityName} CloneWithoutId(this {entityName} entity)
        {{
            if (entity == null) return null;
            
            // 这里可以根据实际需要实现深拷贝逻辑
            throw new NotImplementedException(""Clone method needs to be implemented manually"");
        }}

        {(IsAudited(entityClass) ? GenerateAuditExtensions(entityName) : string.Empty)}
    }}
}}";

            context.AddSource($"{entityName}Extensions.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        private string GenerateAuditExtensions(string entityName)
        {
            return $@"
        /// <summary>
        /// 设置创建审计信息
        /// </summary>
        public static void SetCreationAudit(this {entityName} entity, Guid? userId = null)
        {{
            entity.CreationTime = DateTime.UtcNow;
            entity.CreatorId = userId;
        }}

        /// <summary>
        /// 设置修改审计信息
        /// </summary>
        public static void SetModificationAudit(this {entityName} entity, Guid? userId = null)
        {{
            entity.LastModificationTime = DateTime.UtcNow;
            entity.LastModifierId = userId;
        }}";
        }

        // 生成验证规则
        private void GenerateValidationRules(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetEntityProperties(entityClass);

            var validationRules = new StringBuilder();
            foreach (var prop in properties)
            {
                if (prop.Type.SpecialType == SpecialType.System_String)
                {
                    validationRules.AppendLine($@"
            RuleFor(x => x.{prop.Name})
                .NotEmpty().WithMessage(""{prop.Name} 不能为空"")
                .MaximumLength(255).WithMessage(""{prop.Name} 长度不能超过255个字符"");");
                }
            }

            var sourceCode = $@"
// <auto-generated />
using FluentValidation;
using {namespaceName};

namespace {namespaceName}.Validators
{{
    /// <summary>
    /// {entityName} 实体的验证规则
    /// </summary>
    public class {entityName}Validator : AbstractValidator<{entityName}>
    {{
        public {entityName}Validator()
        {{
            RuleFor(x => x.Id)
                .NotEmpty().WithMessage(""ID 不能为空"");
                
            {validationRules}
        }}
    }}
}}";

            context.AddSource($"{entityName}Validator.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }
}