using System.Text;

namespace CrestCreates.CodeGenerator.CapabilityEndpointGenerator;

internal static class CapabilityEndpointProviderEmitter
{
    // Maps from CapabilityEndpointHttpMethod int values to enum member names
    private static readonly string[] HttpMethodNames =
        { "None", "Get", "Post", "Put", "Patch", "Delete" };

    // Maps from CapabilityEndpointAuthorizationMode int values to enum member names
    private static readonly string[] AuthModeNames =
        { "InheritCapability", "RequireAuthenticated", "AllowAnonymous" };

    /// <summary>
    /// Emits the _Provider.g.cs source for a container class with its endpoint specs.
    /// </summary>
    public static string EmitProviderSource(ContainerEndpointGroup group)
    {
        var sb = new StringBuilder();
        var safeClassName = SanitizeClassName(group.ContainerClassName);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CrestCreates.DynamicApi;");
        sb.AppendLine("using CrestCreates.Metadata;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();

        var ns = group.ContainerNamespace;
        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        // --- Provider Class ---
        sb.AppendLine($"internal sealed class {safeClassName}_GeneratedCapabilityEndpointProvider");
        sb.AppendLine("    : ICapabilityEndpointDescriptorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public IReadOnlyList<CapabilityEndpointDescriptor> GetDescriptors()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new CapabilityEndpointDescriptor[]");
        sb.AppendLine("        {");

        foreach (var spec in group.Specs)
        {
            EmitDescriptor(sb, spec);
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // --- ModuleInitializer ---
        sb.AppendLine($"internal static class {safeClassName}_GeneratedProviderRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        DescriptorProviderRegistry.Register<CapabilityEndpointDescriptor>(");
        sb.AppendLine($"            new {safeClassName}_GeneratedCapabilityEndpointProvider());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitDescriptor(StringBuilder sb, CapabilityEndpointSpecRecord spec)
    {
        var endpointId = $"endpoint:{spec.CapabilityId}";
        var version = spec.CapabilityVersion > 0 ? spec.CapabilityVersion : 1;
        var httpMethodName = ResolveHttpMethodName(spec.HttpMethodValue);
        var authModeName = ResolveAuthModeName(spec.AuthorizationModeValue);
        var successStatusCode = ResolveSuccessStatusCode(spec.SuccessStatusCode, spec.HttpMethodValue);
        var tagsStr = EmitTagsArray(spec.Tags);

        sb.AppendLine("            new CapabilityEndpointDescriptor");
        sb.AppendLine("            {");
        sb.AppendLine($"                Id = \"{Escape(endpointId)}\",");
        sb.AppendLine($"                Name = \"{Escape(spec.SpecClassName)}\",");
        sb.AppendLine($"                Version = {version},");
        sb.AppendLine($"                State = DescriptorState.Active,");
        if (spec.CapabilityVersion == 0)
        {
            sb.AppendLine($"                Capability = new VersionedDescriptorRef<CapabilityDescriptor>(");
            sb.AppendLine($"                    \"{Escape(spec.CapabilityId)}\",");
            sb.AppendLine($"                    0, VersionSelectionMode.Latest),");
        }
        else
        {
            sb.AppendLine($"                Capability = new VersionedDescriptorRef<CapabilityDescriptor>(");
            sb.AppendLine($"                    \"{Escape(spec.CapabilityId)}\",");
            sb.AppendLine($"                    {spec.CapabilityVersion}),");
        }
        sb.AppendLine($"                HttpMethod = CapabilityEndpointHttpMethod.{httpMethodName},");
        sb.AppendLine($"                RoutePattern = \"{Escape(spec.RoutePattern)}\",");
        sb.AppendLine($"                AuthorizationMode = CapabilityEndpointAuthorizationMode.{authModeName},");

        EmitInputBindings(sb, spec.Inputs);
        EmitOutputMapping(sb, successStatusCode);
        EmitProjection(sb, spec, tagsStr);

        sb.AppendLine("            },");
    }

    private static void EmitInputBindings(
        StringBuilder sb,
        System.Collections.Immutable.ImmutableArray<CapabilityEndpointInputRecord> inputs)
    {
        if (inputs.IsEmpty)
        {
            sb.AppendLine("                InputBindings = Array.Empty<CapabilityEndpointInputBinding>(),");
            return;
        }

        sb.AppendLine("                InputBindings = new CapabilityEndpointInputBinding[]");
        sb.AppendLine("                {");

        foreach (var input in inputs)
        {
            var sourceName = ResolveParameterSourceName(input.SourceValue);
            var capInputPath = input.CapabilityInputPath is not null
                ? $"\"{Escape(input.CapabilityInputPath)}\""
                : "null";

            sb.AppendLine("                    new CapabilityEndpointInputBinding");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"{Escape(input.Name)}\",");
            sb.AppendLine($"                        Source = CapabilityEndpointParameterSource.{sourceName},");
            sb.AppendLine($"                        CapabilityInputPath = {capInputPath},");
            sb.AppendLine($"                        Required = {input.Required.ToString().ToLowerInvariant()}");
            sb.AppendLine("                    },");
        }

        sb.AppendLine("                },");
    }

    private static void EmitOutputMapping(StringBuilder sb, int successStatusCode)
    {
        sb.AppendLine("                OutputMapping = new CapabilityEndpointOutputMapping");
        sb.AppendLine("                {");
        sb.AppendLine($"                    SuccessStatusCode = {successStatusCode}");
        sb.AppendLine("                },");
    }

    private static void EmitProjection(
        StringBuilder sb,
        CapabilityEndpointSpecRecord spec,
        string tagsStr)
    {
        sb.AppendLine("                Projection = new CapabilityEndpointProjectionMetadata");
        sb.AppendLine("                {");

        var opId = spec.OperationId;
        if (!string.IsNullOrEmpty(opId))
            sb.AppendLine($"                    OperationId = \"{Escape(opId)}\",");
        var grpName = spec.GroupName;
        if (!string.IsNullOrEmpty(grpName))
            sb.AppendLine($"                    GroupName = \"{Escape(grpName)}\",");
        if (!string.IsNullOrEmpty(tagsStr))
            sb.AppendLine($"                    Tags = {tagsStr},");
        var summary = spec.Summary;
        if (!string.IsNullOrEmpty(summary))
            sb.AppendLine($"                    Summary = \"{Escape(summary)}\",");
        var description = spec.Description;
        if (!string.IsNullOrEmpty(description))
            sb.AppendLine($"                    Description = \"{Escape(description)}\",");
        if (spec.Deprecated)
            sb.AppendLine("                    Deprecated = true,");

        sb.AppendLine("                },");
    }

    private static string EmitTagsArray(System.Collections.Immutable.ImmutableArray<string> tags)
    {
        if (tags.IsDefaultOrEmpty)
            return string.Empty;

        var items = new System.Text.StringBuilder();
        items.Append("new[] { ");
        for (var i = 0; i < tags.Length; i++)
        {
            if (i > 0) items.Append(", ");
            items.Append($"\"{Escape(tags[i])}\"");
        }
        items.Append(" }");
        return items.ToString();
    }

    private static string ResolveHttpMethodName(int value)
    {
        if (value >= 1 && value <= 5)
            return HttpMethodNames[value];
        return "Get"; // Default
    }

    private static string ResolveAuthModeName(int value)
    {
        if (value >= 0 && value < AuthModeNames.Length)
            return AuthModeNames[value];
        return "InheritCapability"; // Default
    }

    private static string ResolveParameterSourceName(int value)
    {
        var names = new[] { "Route", "Query", "Header", "Body" };
        if (value >= 0 && value < names.Length)
            return names[value];
        return "Body";
    }

    /// <summary>
    /// Auto-rule: SuccessStatusCode == 0 → POST: 201, others: 200.
    /// </summary>
    private static int ResolveSuccessStatusCode(int statusCode, int httpMethodValue)
    {
        if (statusCode > 0)
            return statusCode;

        // POST (value 2) → 201
        if (httpMethodValue == 2)
            return 201;

        return 200;
    }

    private static string SanitizeClassName(string name) => name.Replace(".", "_");

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
