using System.Collections.Immutable;
using System.Text;

namespace CrestCreates.CodeGenerator.CapabilityEndpointGenerator;

internal static class CapabilityEndpointBindingEmitter
{
    // Maps from CapabilityEndpointParameterSource int values to enum member names
    private static readonly string[] SourceNames = { "Route", "Query", "Header", "Body" };

    // Maps from CapabilityEndpointHttpMethod int values to method name strings
    private static readonly string[] HttpMethodNames =
        { "None", "Get", "Post", "Put", "Patch", "Delete" };

    // Maps source int to HttpContext.Request member name
    // 0=Route → "RouteValues", 1=Query → "Query", 2=Header → "Headers"
    private static readonly string[] SourceCollectionNames =
        { "RouteValues", "Query", "Headers" };

    /// <summary>
    /// Emits the _Bindings.g.cs source for a container class with its endpoint specs.
    /// </summary>
    public static string EmitBindingSource(ContainerEndpointGroup group)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using CrestCreates.DynamicApi;");
        sb.AppendLine();

        var ns = string.IsNullOrEmpty(group.ContainerNamespace) ? "<global>" : group.ContainerNamespace;
        if (!string.IsNullOrEmpty(group.ContainerNamespace))
        {
            sb.AppendLine($"namespace {group.ContainerNamespace};");
            sb.AppendLine();
        }

        var containerName = group.ContainerClassName;
        var safeClassName = SanitizeClassName(containerName);

        sb.AppendLine($"internal static class {safeClassName}_GeneratedCapabilityEndpointBindings");
        sb.AppendLine("{");

        foreach (var spec in group.Specs)
        {
            var methodName = $"Bind_{SanitizeClassName(spec.SpecClassName)}_Async";
            EmitBindingMethod(sb, spec, methodName);
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Module initializer for binding registration
        sb.AppendLine($"internal static class {safeClassName}_GeneratedBindingsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var spec in group.Specs)
        {
            var endpointId = !string.IsNullOrEmpty(spec.EndpointId) ? spec.EndpointId : $"endpoint:{spec.CapabilityId}";
            var version = spec.EndpointVersion > 0 ? spec.EndpointVersion
                : (spec.CapabilityVersion > 0 ? spec.CapabilityVersion : 1);
            var methodName = $"Bind_{SanitizeClassName(spec.SpecClassName)}_Async";

            sb.AppendLine($"        CapabilityEndpointBindingRegistry.Register(");
            sb.AppendLine($"            new CapabilityEndpointBindingContract(");
            sb.AppendLine($"                \"{Escape(endpointId)}\",");
            sb.AppendLine($"                {version},");
            sb.AppendLine($"                {safeClassName}_GeneratedCapabilityEndpointBindings.{methodName}));");
        }

        foreach (var spec in group.Specs)
        {
            var bodyInput = FindBodyInput(spec.Inputs);
            if (bodyInput is not null)
            {
                // Use TypeOfExpression which correctly handles nullable value types (int? → Nullable<int>)
                // and nullable reference types (BookDto? → BookDto)
                sb.AppendLine($"        CapabilityEndpointJsonContractRegistry.RegisterBodyType(typeof({bodyInput.TypeOfExpression}));");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitBindingMethod(
        StringBuilder sb, CapabilityEndpointSpecRecord spec, string methodName)
    {
        sb.AppendLine($"    internal static async ValueTask<object?> {methodName}(");
        sb.AppendLine("        HttpContext context, CancellationToken ct)");
        sb.AppendLine("    {");

        var bodyInput = FindBodyInput(spec.Inputs);
        var routeInputs = FindRouteInputs(spec.Inputs);
        var queryInputs = FindQueryInputs(spec.Inputs);
        var headerInputs = FindHeaderInputs(spec.Inputs);

        if (bodyInput is not null && (routeInputs.Length > 0 || queryInputs.Length > 0 || headerInputs.Length > 0))
        {
            // Body + Scalars (Route/Query/Header): Read body first, then assign scalar values to properties
            EmitBodyWithScalarBinding(sb, bodyInput, routeInputs, queryInputs, headerInputs);
        }
        else if (bodyInput is not null)
        {
            // Body only
            EmitBodyOnlyBinding(sb, bodyInput);
        }
        else if (routeInputs.Length > 0 || queryInputs.Length > 0 || headerInputs.Length > 0)
        {
            // Scalars only (any mix of Route/Query/Header)
            EmitScalarOnlyBinding(sb, spec, routeInputs, queryInputs, headerInputs);
        }
        else
        {
            // No inputs
            sb.AppendLine("        return null;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitBodyOnlyBinding(StringBuilder sb, CapabilityEndpointInputRecord bodyInput)
    {
        var typeOfExpr = bodyInput.TypeOfExpression;
        var optional = !bodyInput.Required;

        sb.AppendLine($"        var jsonTypeInfo = CapabilityEndpointJsonTypeInfoResolver.Resolve<{typeOfExpr}>(context)");
        sb.AppendLine($"            ?? throw new InvalidOperationException(");
        sb.AppendLine($"                \"No JsonTypeInfo registered for {typeOfExpr}. Add [JsonSerializable(typeof({typeOfExpr}))] to your JsonSerializerContext.\");");
        sb.AppendLine($"        var result = await CapabilityEndpointBodyReader.ReadNativeBodyAsync<{typeOfExpr}>(");
        sb.AppendLine($"            context, jsonTypeInfo, {optional.ToString().ToLowerInvariant()}, ct);");
        sb.AppendLine("        return result;");
    }

    private static void EmitBodyWithScalarBinding(
        StringBuilder sb,
        CapabilityEndpointInputRecord bodyInput,
        ImmutableArray<CapabilityEndpointInputRecord> routeInputs,
        ImmutableArray<CapabilityEndpointInputRecord> queryInputs,
        ImmutableArray<CapabilityEndpointInputRecord> headerInputs)
    {
        var typeOfExpr = bodyInput.TypeOfExpression;
        var optional = !bodyInput.Required;

        sb.AppendLine($"        var jsonTypeInfo = CapabilityEndpointJsonTypeInfoResolver.Resolve<{typeOfExpr}>(context)");
        sb.AppendLine($"            ?? throw new InvalidOperationException(");
        sb.AppendLine($"                \"No JsonTypeInfo registered for {typeOfExpr}. Add [JsonSerializable(typeof({typeOfExpr}))] to your JsonSerializerContext.\");");
        sb.AppendLine($"        var model = await CapabilityEndpointBodyReader.ReadNativeBodyAsync<{typeOfExpr}>(");
        sb.AppendLine($"            context, jsonTypeInfo, {optional.ToString().ToLowerInvariant()}, ct);");
        sb.AppendLine();

        // Assign route values to model properties
        foreach (var input in routeInputs)
            EmitScalarPropertyAssignment(sb, input, 0);

        // Assign query values to model properties
        foreach (var input in queryInputs)
            EmitScalarPropertyAssignment(sb, input, 1);

        // Assign header values to model properties
        foreach (var input in headerInputs)
            EmitScalarPropertyAssignment(sb, input, 2);

        sb.AppendLine("        return model;");
    }

    /// <summary>
    /// Emits a property assignment for a scalar input (Route/Query/Header) onto the model DTO.
    /// </summary>
    /// <param name="sourceValue">
    /// 0=Route → <c>context.Request.RouteValues</c>,
    /// 1=Query → <c>context.Request.Query</c>,
    /// 2=Header → <c>context.Request.Headers</c>.
    /// </param>
    private static void EmitScalarPropertyAssignment(
        StringBuilder sb,
        CapabilityEndpointInputRecord input,
        int sourceValue)
    {
        var sourceCollection = sourceValue switch
        {
            0 => "RouteValues",
            1 => "Query",
            2 => "Headers",
            _ => "RouteValues"
        };

        var sourceKey = input.Name;
        var propAssignmentName = !string.IsNullOrEmpty(input.TargetProperty)
            ? input.TargetProperty
            : !string.IsNullOrEmpty(sourceKey)
                ? char.ToUpperInvariant(sourceKey[0]) + sourceKey.Substring(1)
                : sourceKey;
        var varName = SanitizeVarName(sourceKey);

        // Route returns string?, so use ?.ToString(). Query and Header return StringValues (struct),
        // so use .ToString() directly (no null-conditional).
        string valueExpr;
        string tryGetValueExpr;
        if (sourceValue == 0)
        {
            // Route: TryGetValue returns out string?, parse with ?.ToString()
            tryGetValueExpr = $"context.Request.{sourceCollection}.TryGetValue(\"{sourceKey}\", out var {varName})";
            valueExpr = $"{varName}?.ToString()";
        }
        else
        {
            // Query or Header: TryGetValue returns out StringValues, parse with .ToString()
            tryGetValueExpr = $"context.Request.{sourceCollection}.TryGetValue(\"{sourceKey}\", out var {varName})";
            valueExpr = $"{varName}.ToString()";
        }

        var parseCode = GetScalarParseCode(input, valueExpr);

        if (parseCode is not null)
        {
            sb.AppendLine($"        if (model is not null && {tryGetValueExpr})");
            sb.AppendLine("        {");
            sb.AppendLine($"            model.{propAssignmentName} = {parseCode};");
            sb.AppendLine("        }");
        }
        else
        {
            sb.AppendLine($"        // CEP012: Cannot bind {sourceCollection.ToLowerInvariant()} '{sourceKey}' — unsupported type '{input.TypeName}'");
        }
        sb.AppendLine();
    }

    private static void EmitScalarOnlyBinding(
        StringBuilder sb,
        CapabilityEndpointSpecRecord spec,
        ImmutableArray<CapabilityEndpointInputRecord> routeInputs,
        ImmutableArray<CapabilityEndpointInputRecord> queryInputs,
        ImmutableArray<CapabilityEndpointInputRecord> headerInputs)
    {
        var allInputs = routeInputs
            .AddRange(queryInputs)
            .AddRange(headerInputs);

        if (allInputs.Length == 1
            && (IsScalarTypeName(allInputs[0].TypeName) || allInputs[0].IsEnum))
        {
            // Single scalar/enum param (Route, Query, or Header) — parse and return directly
            var input = allInputs[0];
            var sourceExpr = GetSourceReadExpression(input);
            var parseCode = GetScalarParseCode(input, sourceExpr);
            if (parseCode is not null)
            {
                sb.AppendLine($"        var value = {parseCode};");
                sb.AppendLine("        return value;");
            }
            else
            {
                sb.AppendLine($"        // CEP012: Unsupported type '{input.TypeName}' for scalar binding");
                sb.AppendLine("        return null;");
            }
        }
        else
        {
            // Multiple scalar params without body — fail-closed (CEP013 prevents this at compile time)
            sb.AppendLine("        throw new InvalidOperationException(");
            sb.AppendLine("            \"CEP013: Multiple scalar inputs without a body/input DTO are not supported.\");");
        }
    }

    private static CapabilityEndpointInputRecord? FindBodyInput(
        ImmutableArray<CapabilityEndpointInputRecord> inputs)
    {
        foreach (var input in inputs)
        {
            if (input.SourceValue == 3) // Body
                return input;
        }

        return null;
    }

    private static ImmutableArray<CapabilityEndpointInputRecord> FindRouteInputs(
        ImmutableArray<CapabilityEndpointInputRecord> inputs)
    {
        var builder = ImmutableArray.CreateBuilder<CapabilityEndpointInputRecord>();
        foreach (var input in inputs)
        {
            if (input.SourceValue == 0) // Route
                builder.Add(input);
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<CapabilityEndpointInputRecord> FindQueryInputs(
        ImmutableArray<CapabilityEndpointInputRecord> inputs)
    {
        var builder = ImmutableArray.CreateBuilder<CapabilityEndpointInputRecord>();
        foreach (var input in inputs)
        {
            if (input.SourceValue == 1) // Query
                builder.Add(input);
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<CapabilityEndpointInputRecord> FindHeaderInputs(
        ImmutableArray<CapabilityEndpointInputRecord> inputs)
    {
        var builder = ImmutableArray.CreateBuilder<CapabilityEndpointInputRecord>();
        foreach (var input in inputs)
        {
            if (input.SourceValue == 2) // Header
                builder.Add(input);
        }

        return builder.ToImmutable();
    }

    /// <summary>
    /// Returns the C# expression that reads the raw string value from the HTTP source
    /// for a scalar input (Route, Query, or Header).
    /// Route values return string? so use ?.ToString().
    /// Query and Header return StringValues (struct) so use .ToString() directly.
    /// </summary>
    private static string GetSourceReadExpression(CapabilityEndpointInputRecord input)
    {
        var sourceCollection = input.SourceValue switch
        {
            0 => "RouteValues",
            1 => "Query",
            2 => "Headers",
            _ => "RouteValues"
        };

        // Route returns string?, use null-conditional. Query/Header return StringValues (struct).
        var toStringOperator = input.SourceValue == 0 ? "?.ToString()" : ".ToString()";
        return $"context.Request.{sourceCollection}[\"{input.Name}\"]{toStringOperator}";
    }

    /// <summary>
    /// Generates the parse code for a scalar or enum type value from a route value string expression.
    /// Returns null when the type is not a known scalar and is not an enum (unsupported for route binding).
    /// </summary>
    private static string? GetScalarParseCode(CapabilityEndpointInputRecord input, string valueExpr)
    {
        var typeName = input.TypeName;

        // Strip nullable annotation for parsing
        var cleanType = typeName.EndsWith("?") ? typeName.Substring(0, typeName.Length - 1) : typeName;

        // Check for fully-qualified format: global::Namespace.Type
        var shortName = ExtractShortName(cleanType);

        switch (shortName)
        {
            case "String":
                return $"{valueExpr} ?? string.Empty";
            case "Int32":
                return $"int.Parse({valueExpr} ?? \"0\")";
            case "Int64":
                return $"long.Parse({valueExpr} ?? \"0\")";
            case "Guid":
                return $"Guid.Parse({valueExpr} ?? Guid.Empty.ToString())";
            case "Boolean":
                return $"bool.Parse({valueExpr} ?? \"false\")";
            case "Double":
                return $"double.Parse({valueExpr} ?? \"0\")";
            case "Single":
                return $"float.Parse({valueExpr} ?? \"0\")";
            case "Decimal":
                return $"decimal.Parse({valueExpr} ?? \"0\")";
            case "DateTime":
                return $"DateTime.Parse({valueExpr} ?? DateTime.MinValue.ToString())";
            case "DateTimeOffset":
                return $"DateTimeOffset.Parse({valueExpr} ?? DateTimeOffset.MinValue.ToString())";
            case "Int16":
                return $"short.Parse({valueExpr} ?? \"0\")";
            case "UInt16":
                return $"ushort.Parse({valueExpr} ?? \"0\")";
            case "UInt32":
                return $"uint.Parse({valueExpr} ?? \"0\")";
            case "UInt64":
                return $"ulong.Parse({valueExpr} ?? \"0\")";
            case "Byte":
                return $"byte.Parse({valueExpr} ?? \"0\")";
            case "SByte":
                return $"sbyte.Parse({valueExpr} ?? \"0\")";
            default:
                // Enum or unsupported custom type
                if (!input.IsEnum)
                    return null; // CEP012 catches this at compile time
                return $"({cleanType})Enum.Parse(typeof({cleanType}), {valueExpr} ?? \"0\")";
        }
    }

    private static bool IsScalarTypeName(string typeName)
    {
        var cleanType = typeName.EndsWith("?") ? typeName.Substring(0, typeName.Length - 1) : typeName;
        var shortName = ExtractShortName(cleanType);
        return shortName switch
        {
            "String" or "Int32" or "Int64" or "Guid" or "Boolean" or "Double"
                or "Single" or "Decimal" or "DateTime" or "DateTimeOffset"
                or "Int16" or "UInt16" or "UInt32" or "UInt64" or "Byte" or "SByte"
                => true,
            _ => false,
        };
    }

    private static string ExtractShortName(string fullyQualifiedName)
    {
        // global::System.Int32 → Int32
        var lastDot = fullyQualifiedName.LastIndexOf('.');
        if (lastDot >= 0 && lastDot < fullyQualifiedName.Length - 1)
            return fullyQualifiedName.Substring(lastDot + 1);
        return fullyQualifiedName;
    }

    private static string SanitizeClassName(string name) => name.Replace(".", "_");

    /// <summary>
    /// Sanitizes a name for use as a C# local variable identifier (e.g., replaces hyphens
    /// and other non-alphanumeric characters with underscores).
    /// </summary>
    private static string SanitizeVarName(string name)
    {
        if (string.IsNullOrEmpty(name))
            return "_";

        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }

    /// <summary>
    /// Returns true when <paramref name="name"/> is a valid C# identifier
    /// (starts with a letter or underscore, contains only letters, digits, or underscores).
    /// </summary>
    internal static bool IsValidCSharpIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
            return false;
        if (!char.IsLetter(name[0]) && name[0] != '_')
            return false;
        foreach (var c in name)
        {
            if (!char.IsLetterOrDigit(c) && c != '_')
                return false;
        }
        return true;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
