<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CrestCreates.Framework.Abstractions</RootNamespace>
    <AssemblyName>CrestCreates.Framework.Abstractions</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
