using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CrestCreates.CodeGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CrestCreates.CodeGenerator.SchemaCapabilityGenerator;

[Generator]
public sealed class HandlerInvokerSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds
                    && cds.BaseList?.Types.Count > 0,
                transform: static (ctx, ct) => GetHandlerInfo(ctx))
            .Where(static x => x is not null)
            .Collect();

        var compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(
            handlerClasses.Combine(compilationProvider),
            static (spc, source) =>
            {
                GenerateHandlerRegistrations(spc, source.Left, source.Right);
            });
    }

    private static HandlerInvokerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol == null) return null;

        var handlerType = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName("CrestCreates.Capability.Abstractions.ICapabilityHandler`2");
        if (handlerType == null) return null;

        var genericHandler = symbol.AllInterfaces
            .FirstOrDefault(i => i.IsGenericType
                && i.OriginalDefinition.Equals(handlerType, SymbolEqualityComparer.Default));

        if (genericHandler == null) return null;

        var inputType = genericHandler.TypeArguments[0];
        var outputType = genericHandler.TypeArguments[1];

        var capabilityName = GetCapabilityName(symbol);

        return new HandlerInvokerInfo
        {
            HandlerTypeName = symbol.Name,
            HandlerNamespace = symbol.ContainingNamespace?.ToDisplayString() ?? string.Empty,
            CapabilityName = capabilityName,
            InputTypeName = inputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            OutputTypeName = outputType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
        };
    }

    private static string GetCapabilityName(INamedTypeSymbol symbol)
    {
        var attr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "CapabilityNameAttribute" or "CapabilityName");
        if (attr != null && attr.ConstructorArguments.Length > 0)
            return attr.ConstructorArguments[0].Value?.ToString() ?? string.Empty;

        return symbol.Name
            .Replace("Handler", "")
            .Replace("AppService", "")
            .ToLowerInvariant();
    }

    private static void GenerateHandlerRegistrations(
        SourceProductionContext spc,
        ImmutableArray<HandlerInvokerInfo?> handlers,
        Compilation compilation)
    {
        var hasCapability = compilation.ReferencedAssemblyNames
            .Any(a => a.Name == "CrestCreates.Capability.Abstractions");
        if (!hasCapability) return;

        var validHandlers = handlers.Where(h => h != null && !string.IsNullOrEmpty(h!.CapabilityName)).ToList();
        if (validHandlers.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CrestCreates.Capability;");
        sb.AppendLine("using CrestCreates.Capability.Abstractions;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedHandlerRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine("        var resolver = new CapabilityHandlerResolver();");

        foreach (var handler in validHandlers)
        {
            if (handler == null) continue;
            var fullName = string.IsNullOrEmpty(handler.HandlerNamespace)
                ? handler.HandlerTypeName
                : $"{handler.HandlerNamespace}.{handler.HandlerTypeName}";
            var invokerClassName = $"{handler.HandlerTypeName}_Invoker";

            sb.AppendLine();
            sb.AppendLine($"        // Handler: {fullName}");
            sb.AppendLine($"        resolver.Register(\"{handler.CapabilityName}\",");
            sb.AppendLine($"            new {invokerClassName}());");
        }

        sb.AppendLine();
        sb.AppendLine("        CapabilityHandlerResolverProvider.SetResolver(resolver);");
        sb.AppendLine("    }");

        // Emit invoker wrapper classes
        foreach (var handler in validHandlers)
        {
            if (handler == null) continue;
            var fullName = string.IsNullOrEmpty(handler.HandlerNamespace)
                ? handler.HandlerTypeName
                : $"{handler.HandlerNamespace}.{handler.HandlerTypeName}";
            var invokerClassName = $"{handler.HandlerTypeName}_Invoker";

            sb.AppendLine();
            sb.AppendLine($"    internal sealed class {invokerClassName} : ICapabilityHandlerInvoker");
            sb.AppendLine("    {");
            sb.AppendLine("        public async Task<object?> InvokeAsync(object? input, CancellationToken ct)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var handler = new {fullName}();");
            sb.AppendLine($"            var typedInput = ({handler.InputTypeName})input!;");
            sb.AppendLine("            var result = await handler.ExecuteAsync(typedInput, ct).ConfigureAwait(false);");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        spc.AddSource("GeneratedHandlerRegistry.g.cs", sb.ToString());
    }
}
