using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CrestCreates.Data.SourceGenerator
{
    /// <summary>
    /// 仓储注册源代码生成器
    /// </summary>
    [Generator]
    public class RepositoryRegistrationGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
#if DEBUG
            // 添加调试信息生成
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("RepositoryRegistrationGeneratorDebug.g.cs", GenerateDebugInfo()));
#endif

            // 查找所有接口并进行分析
            var interfaceProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                    transform: static (ctx, _) => AnalyzeInterface(ctx))
                .Where(static info => info is not null);

            // 收集编译信息
            var compilationAndInterfaces = context.CompilationProvider.Combine(interfaceProvider.Collect());

#if DEBUG
            // 生成调试报告
            context.RegisterSourceOutput(compilationAndInterfaces,
                static (spc, source) => GenerateDebugReport(source.Left, source.Right, spc));
#endif

            // 生成代码
            context.RegisterSourceOutput(compilationAndInterfaces,
                static (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static RepositoryInterfaceInfo? AnalyzeInterface(GeneratorSyntaxContext context)
        {
            // 我们处理的是接口，检查是否为接口声明
            if (context.Node is not InterfaceDeclarationSyntax interfaceDeclaration)
            {
                return null;
            }

            // 获取语义模型和符号
            var semanticModel = context.SemanticModel;
            if (semanticModel.GetDeclaredSymbol(interfaceDeclaration) is not INamedTypeSymbol interfaceSymbol)
            {
                return null;
            }

            // 检查接口是否继承了 IRepository<> 或相关接口
            var isRepositoryInterface = interfaceSymbol.AllInterfaces.Any(i => 
                i.IsGenericType && 
                i.ConstructedFrom.ToDisplayString() == "CrestCreates.Data.Repository.IRepository<T>");

            if (!isRepositoryInterface)
            {
                // 检查是否是自定义仓储接口（以Repository结尾或包含Repository）
                var interfaceName = interfaceSymbol.Name;
                if (!interfaceName.Contains("Repository") && !interfaceName.EndsWith("Repository"))
                {
                    return null;
                }
            }

            // 获取实体类型
            string? entityType = null;
            if (isRepositoryInterface)
            {
                var repositoryInterface = interfaceSymbol.AllInterfaces.FirstOrDefault(i => 
                    i.IsGenericType && 
                    i.ConstructedFrom.ToDisplayString() == "CrestCreates.Data.Repository.IRepository<T>");
                
                if (repositoryInterface != null && repositoryInterface.TypeArguments.Length > 0)
                {
                    entityType = repositoryInterface.TypeArguments[0].ToDisplayString();
                }
            }

            return new RepositoryInterfaceInfo(
                interfaceSymbol.ToDisplayString(),
                interfaceSymbol.Name,
                interfaceSymbol.ContainingNamespace.ToDisplayString(),
                entityType,
                isRepositoryInterface
            );
        }

        private static void Execute(Compilation compilation, ImmutableArray<RepositoryInterfaceInfo?> infos, SourceProductionContext context)
        {
            var validInfos = infos.Where(i => i != null).Cast<RepositoryInterfaceInfo>().ToArray();
            
            if (!validInfos.Any())
            {
                return;
            }

            var source = GenerateRepositoryRegistrationCode(validInfos);
            context.AddSource("RepositoryRegistrationExtensions.g.cs", source);
        }

        private static string GenerateRepositoryRegistrationCode(RepositoryInterfaceInfo[] repositoryInfos)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using CrestCreates.Data.Repository;");
            sb.AppendLine("using CrestCreates.Data.UnitOfWork;");
            sb.AppendLine("using CrestCreates.Data.Adapters;");
            sb.AppendLine("using CrestCreates.Data.Providers;");
            sb.AppendLine();
            
            sb.AppendLine("namespace CrestCreates.Data.Extensions");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 自动生成的仓储注册扩展");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class GeneratedRepositoryRegistrationExtensions");
            sb.AppendLine("    {");
            
            // 生成注册所有仓储的方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 注册所有发现的仓储接口");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static IServiceCollection AddGeneratedRepositories(this IServiceCollection services)");
            sb.AppendLine("        {");
            
            foreach (var repo in repositoryInfos)
            {
                if (repo.IsGenericRepository)
                {
                    sb.AppendLine($"            // 注册 {repo.InterfaceName}");
                    sb.AppendLine($"            services.AddScoped<{repo.FullName}>(provider =>");
                    sb.AppendLine("            {");
                    sb.AppendLine("                var databaseProvider = provider.GetRequiredService<IDatabaseProvider>();");
                    sb.AppendLine("                var dbContext = databaseProvider.CreateDbContext();");
                    sb.AppendLine($"                return databaseProvider.Adapter.CreateRepository<{repo.EntityType}>(dbContext);");
                    sb.AppendLine("            });");
                    sb.AppendLine();
                }
            }
            
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 生成获取所有仓储接口类型的方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 获取所有发现的仓储接口类型");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static Type[] GetRepositoryInterfaceTypes()");
            sb.AppendLine("        {");
            sb.AppendLine("            return new Type[]");
            sb.AppendLine("            {");
            
            foreach (var repo in repositoryInfos)
            {
                sb.AppendLine($"                typeof({repo.FullName}),");
            }
            
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // 生成检查仓储是否已注册的方法
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 检查指定类型是否为已发现的仓储接口");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static bool IsRepositoryInterface(Type type)");
            sb.AppendLine("        {");
            sb.AppendLine("            var repositoryTypes = GetRepositoryInterfaceTypes();");
            sb.AppendLine("            return repositoryTypes.Contains(type);");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");
            
            return sb.ToString();
        }

        private static string GenerateDebugInfo()
        {
            return $@"// <auto-generated/>
// This file contains debug information for the RepositoryRegistrationGenerator

using System;

namespace CrestCreates.Generated.Data
{{
    public static class RepositoryRegistrationGeneratorDebugInfo
    {{
        public static readonly string GeneratedAt = ""{DateTimeOffset.Now}"";
        public static readonly string Message = ""RepositoryRegistrationGenerator is working"";
    }}
}}";
        }

        private static void GenerateDebugReport(Compilation compilation, ImmutableArray<RepositoryInterfaceInfo?> infos, SourceProductionContext context)
        {
            var validInfos = infos.Where(c => c != null).Cast<RepositoryInterfaceInfo>().ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Debug report for repository registration generator");
            sb.AppendLine();
            sb.AppendLine("/*");
            sb.AppendLine($"Total interfaces analyzed: {infos.Length}");
            sb.AppendLine($"Repository interfaces found: {validInfos.Count}");
            sb.AppendLine();
            sb.AppendLine("Repository interfaces:");

            foreach (var repoInfo in validInfos)
            {
                sb.AppendLine($"  - {repoInfo.InterfaceName} ({repoInfo.FullName})");
                sb.AppendLine($"    Namespace: {repoInfo.Namespace}");
                sb.AppendLine($"    Entity Type: {repoInfo.EntityType ?? "Unknown"}");
                sb.AppendLine($"    Is Generic Repository: {repoInfo.IsGenericRepository}");
                sb.AppendLine();
            }

            sb.AppendLine("*/");

            context.AddSource("RepositoryRegistrationGeneratorDebugReport.g.cs", sb.ToString());
        }
    }

    /// <summary>
    /// 仓储接口信息
    /// </summary>
    public class RepositoryInterfaceInfo
    {
        public string FullName { get; }
        public string InterfaceName { get; }
        public string Namespace { get; }
        public string? EntityType { get; }
        public bool IsGenericRepository { get; }

        public RepositoryInterfaceInfo(string fullName, string interfaceName, string namespaceName, 
            string? entityType, bool isGenericRepository)
        {
            FullName = fullName;
            InterfaceName = interfaceName;
            Namespace = namespaceName;
            EntityType = entityType;
            IsGenericRepository = isGenericRepository;
        }
    }
}
