<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrestCreates.Aop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rougamo.Fody" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrestCreates.Aop.Abstractions\CrestCreates.Aop.Abstractions.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Authorization.Abstractions\CrestCreates.Authorization.Abstractions.csproj" />
    <ProjectReference Include="..\CrestCreates.Caching.Abstractions\CrestCreates.Caching.Abstractions.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Domain\CrestCreates.Domain.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Domain.Shared\CrestCreates.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Modularity\CrestCreates.Modularity.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.MultiTenancy.Abstract\CrestCreates.MultiTenancy.Abstract.csproj" />
    <ProjectReference Include="..\..\Persistence\CrestCreates.Data.Abstractions\CrestCreates.Data.Abstractions.csproj" />
  </ItemGroup>

</Project>
