using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.TenantDbContextFactoryGenerator
{
    [Generator]
    public class TenantDbContextFactorySourceGenerator : IIncrementalGenerator
    {
        private const string ITenantDbContextFactoryFullName = "CrestCreates.OrmProviders.EFCore.MultiTenancy.ITenantDbContextFactory";
        private const string RegistryStoreFullName = "CrestCreates.OrmProviders.EFCore.MultiTenancy.TenantDbContextFactoryRegistryStore";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var dbContextClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsDbContextCandidate(node),
                    transform: static (ctx, _) => GetDbContextClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            var hasFactoryInterface = context.CompilationProvider
                .Select(static (compilation, _) =>
                    compilation.GetTypeByMetadataName(ITenantDbContextFactoryFullName) is not null &&
                    compilation.GetTypeByMetadataName(RegistryStoreFullName) is not null);

            var combined = dbContextClasses.Combine(hasFactoryInterface);

            context.RegisterSourceOutput(combined, ExecuteGeneration);
        }

        private static bool IsDbContextCandidate(SyntaxNode node)
        {
            if (node is ClassDeclarationSyntax classDecl && classDecl.BaseList != null)
            {
                foreach (var baseType in classDecl.BaseList.Types)
                {
                    var typeName = baseType.Type.ToString();
                    if (typeName.Contains("DbContext"))
                        return true;
                }
            }
            return false;
        }

        private static INamedTypeSymbol? GetDbContextClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol == null) return null;

            var baseType = symbol.BaseType;
            while (baseType != null)
            {
                if (baseType.Name == "DbContext" && baseType.ContainingNamespace.ToDisplayString().StartsWith("Microsoft.EntityFrameworkCore"))
                    return symbol;
                baseType = baseType.BaseType;
            }

            return null;
        }

        private void ExecuteGeneration(SourceProductionContext context, (ImmutableArray<INamedTypeSymbol?> DbContexts, bool HasFactoryInterface) input)
        {
            var (dbContexts, hasFactoryInterface) = input;

            if (!hasFactoryInterface) return;
            if (dbContexts.IsDefaultOrEmpty) return;

            var processed = new HashSet<string>();
            var dbContextList = new List<INamedTypeSymbol>();

            foreach (var dbContext in dbContexts)
            {
                if (dbContext == null) continue;
                var fullName = dbContext.ToDisplayString();
                if (processed.Contains(fullName)) continue;
                processed.Add(fullName);
                dbContextList.Add(dbContext);
            }

            if (dbContextList.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
            sb.AppendLine("using CrestCreates.OrmProviders.EFCore.MultiTenancy;");
            sb.AppendLine();
            sb.AppendLine("namespace CrestCreates.OrmProviders.EFCore.MultiTenancy");
            sb.AppendLine("{");
            sb.AppendLine("    internal sealed class GeneratedTenantDbContextFactory : ITenantDbContextFactory");
            sb.AppendLine("    {");

            foreach (var dbContext in dbContextList)
            {
                var fullName = dbContext.ToDisplayString();
                sb.AppendLine($"        private static DbContextOptions<{fullName}> CastOptions{dbContext.Name}(DbContextOptions<{fullName}> options) => options;");
                sb.AppendLine($"        private static {fullName} Create{dbContext.Name}(DbContextOptions<{fullName}> options) => new {fullName}(options);");
                sb.AppendLine();
            }

            sb.AppendLine("        public TDbContext Create<TDbContext>(DbContextOptions<TDbContext> options) where TDbContext : DbContext");
            sb.AppendLine("        {");

            for (int i = 0; i < dbContextList.Count; i++)
            {
                var dbContext = dbContextList[i];
                var fullName = dbContext.ToDisplayString();
                var prefix = i == 0 ? "if" : "else if";
                sb.AppendLine($"            {prefix} (typeof(TDbContext) == typeof({fullName}))");
                sb.AppendLine($"                return (TDbContext)(object)Create{dbContext.Name}(CastOptions{dbContext.Name}((DbContextOptions<{fullName}>)(object)options));");
            }

            sb.AppendLine("            throw new InvalidOperationException($\"No factory registered for {typeof(TDbContext).Name}. Register an ITenantDbContextFactory or ensure the DbContext is discoverable by the source generator.\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class GeneratedTenantDbContextFactoryRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void Register()");
            sb.AppendLine("        {");
            sb.AppendLine("            TenantDbContextFactoryRegistryStore.Register(new GeneratedTenantDbContextFactory());");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TenantDbContextFactory.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
