using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.ServiceGenerator
{
    [Generator]
    public class ServiceSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 创建增量数据源：查找带有ServiceAttribute的类
            var serviceClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsServiceCandidate(node),
                    transform: static (ctx, _) => GetServiceClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            // 注册源代码生成
            context.RegisterSourceOutput(serviceClasses, ExecuteGeneration);
        }

        private static bool IsServiceCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static bool HasServiceAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass != null && (
                    attr.AttributeClass.Name == "ServiceAttribute" ||
                    attr.AttributeClass.Name == "Service" ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".ServiceAttribute") ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".Service")
                ));
        }

        private static INamedTypeSymbol? GetServiceClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && HasServiceAttribute(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> serviceClasses)
        {
            if (serviceClasses.IsDefaultOrEmpty)
                return;

            // 去重处理
            var uniqueServices = serviceClasses
                .Where(s => s != null)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .ToList();

            try
            {
                // 先生成服务接口（如果不存在）
                foreach (var service in uniqueServices)
                {
                    GenerateServiceInterface(context, service);
                }
                
                // 生成服务注册代码
                GenerateServiceRegistration(context, uniqueServices.ToArray());

                // 生成API控制器
                foreach (var service in uniqueServices)
                {
                    if (GetAttributeProperty(service, "GenerateController", true))
                    {
                        GenerateApiController(context, service);
                    }
                }
                
                // 生成服务扩展方法
                foreach (var service in uniqueServices)
                {
                    GenerateServiceExtensions(context, service);
                }
                
                // 生成服务测试基类
                foreach (var service in uniqueServices)
                {
                    GenerateServiceTestBase(context, service);
                }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CCCG002", "Service generation error",
                        $"Error generating service code: {ex.Message}",
                        "CodeGeneration", DiagnosticSeverity.Warning, true),
                    Location.None));
            }
        }

        private void GenerateServiceRegistration(SourceProductionContext context, INamedTypeSymbol[] serviceClasses)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            builder.AppendLine();
            builder.AppendLine("namespace CrestCreates.Infrastructure.DependencyInjection");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 自动生成的服务注册扩展类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public static class AutoServiceRegistration");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 注册所有自动生成的服务");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        public static IServiceCollection AddGeneratedServices(this IServiceCollection services)");
            builder.AppendLine("        {");

            foreach (var service in serviceClasses)
            {
                var serviceType = service.ToDisplayString();
                bool hasInterface = false;
                string? interfaceType = null;
                
                // 查找该服务的接口
                foreach (var interfaceSymbol in service.Interfaces)
                {
                    if (interfaceSymbol.Name.StartsWith("I") && 
                        interfaceSymbol.Name.Substring(1) == service.Name)
                    {
                        interfaceType = interfaceSymbol.ToDisplayString();
                        hasInterface = true;
                        break;
                    }
                }

                var lifetimeEnum = GetAttributeProperty(service, "Lifetime", 0);
                var lifetime = lifetimeEnum switch
                {
                    0 => "Scoped",
                    1 => "Singleton",
                    2 => "Transient",
                    _ => "Scoped"
                };
                
                builder.AppendLine($"            // {service.Name} - {lifetime}");
                if (hasInterface && interfaceType != null)
                {
                    builder.AppendLine($"            services.Add{lifetime}<{interfaceType}, {serviceType}>();");
                }
                else
                {
                    builder.AppendLine($"            services.Add{lifetime}<{serviceType}>();");
                }
                builder.AppendLine();
            }

            builder.AppendLine("            return services;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource("AutoServiceRegistration.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private void GenerateApiController(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            if (serviceClass == null) return;
            
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            var routeAttr = GetAttributeProperty(serviceClass, "Route", "");
            var route = !string.IsNullOrEmpty(routeAttr) 
                ? routeAttr 
                : $"api/{serviceName.Replace("Service", "").ToLowerInvariant()}";
            
            // 查找该服务的接口
            INamedTypeSymbol? interfaceSymbol = null;
            foreach (var iface in serviceClass.Interfaces)
            {
                if (iface.Name.StartsWith("I") && 
                    iface.Name.Substring(1) == serviceName)
                {
                    interfaceSymbol = iface;
                    break;
                }
            }

            // 如果没有接口，使用生成的接口
            var serviceInterface = interfaceSymbol?.ToDisplayString() ?? $"{namespaceName}.I{serviceName}";
            var controllerName = serviceName.Replace("Service", "");
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
            builder.AppendLine("using Microsoft.Extensions.Logging;");
            builder.AppendLine($"using {namespaceName};");
            
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Controllers");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {controllerName} API 控制器");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    [ApiController]");
            builder.AppendLine($"    [Route(\"{route}\")]");
            builder.AppendLine($"    public partial class {controllerName}Controller : ControllerBase");
            builder.AppendLine("    {");
            builder.AppendLine($"        private readonly {serviceInterface} _service;");
            builder.AppendLine($"        private readonly ILogger<{controllerName}Controller> _logger;");
            builder.AppendLine();
            
            builder.AppendLine($"        public {controllerName}Controller(");
            builder.AppendLine($"            {serviceInterface} service,");
            builder.AppendLine($"            ILogger<{controllerName}Controller> logger)");
            builder.AppendLine("        {");
            builder.AppendLine("            _service = service ?? throw new ArgumentNullException(nameof(service));");
            builder.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
            builder.AppendLine("        }");
            builder.AppendLine();
            
            // 为每个公共方法生成API端点
            var methods = serviceClass.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && 
                           !m.IsStatic &&
                           m.MethodKind == MethodKind.Ordinary);
                
            foreach (var method in methods)
            {
                GenerateControllerAction(builder, method, serviceName);
            }
            
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource($"{controllerName}Controller.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private void GenerateControllerAction(StringBuilder builder, IMethodSymbol method, string serviceName)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var httpVerb = DetermineHttpVerb(methodName);
            var routeTemplate = GenerateRouteTemplate(methodName, method.Parameters);
            
            builder.AppendLine("        /// <summary>");
            builder.AppendLine($"        /// {methodName}");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        [Http{httpVerb}(\"{routeTemplate}\")]");
            builder.AppendLine($"        [ProducesResponseType(200)]");
            builder.AppendLine($"        [ProducesResponseType(400)]");
            builder.AppendLine($"        [ProducesResponseType(500)]");
            
            // 方法签名
            builder.Append($"        public async Task<IActionResult> {methodName}(");
            
            // 参数列表
            var parameters = new List<string>();
            foreach (var parameter in method.Parameters)
            {
                string paramAttr = DetermineParameterAttribute(parameter, httpVerb);
                parameters.Add($"{paramAttr}{parameter.Type.ToDisplayString()} {parameter.Name}");
            }
            
            builder.Append(string.Join(", ", parameters));
            builder.AppendLine(")");
            builder.AppendLine("        {");
            builder.AppendLine("            try");
            builder.AppendLine("            {");
            
            // 方法实现
            if (returnType == "void" || returnType == "System.Threading.Tasks.Task")
            {
                builder.Append($"                await _service.{methodName}(");
                builder.Append(string.Join(", ", method.Parameters.Select(p => p.Name)));
                builder.AppendLine(");");
                builder.AppendLine("                return Ok();");
            }
            else
            {
                builder.Append($"                var result = await _service.{methodName}(");
                builder.Append(string.Join(", ", method.Parameters.Select(p => p.Name)));
                builder.AppendLine(");");
                builder.AppendLine("                return Ok(result);");
            }
            
            builder.AppendLine("            }");
            builder.AppendLine("            catch (ArgumentException ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogWarning(ex, \"Bad request in {methodName}\");");
            builder.AppendLine("                return BadRequest(ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine("            catch (Exception ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogError(ex, \"Error in {methodName}\");");
            builder.AppendLine("                return StatusCode(500, \"An error occurred while processing your request.\");");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private string DetermineParameterAttribute(IParameterSymbol parameter, string httpVerb)
        {
            var typeName = parameter.Type.ToDisplayString();
            
            // 简单类型从路由或查询字符串获取
            if (parameter.Type.SpecialType != SpecialType.None || 
                typeName == "string" || 
                typeName == "System.Guid" ||
                typeName.StartsWith("System."))
            {
                return "[FromRoute] ";
            }
            
            // 复杂类型从请求体获取
            if (httpVerb == "Get")
            {
                return "[FromQuery] ";
            }
            
            return "[FromBody] ";
        }

        private string DetermineHttpVerb(string methodName)
        {
            if (methodName.StartsWith("Get"))
                return "Get";
            if (methodName.StartsWith("Create") || methodName.StartsWith("Add") || methodName.StartsWith("Insert"))
                return "Post";
            if (methodName.StartsWith("Update"))
                return "Put";
            if (methodName.StartsWith("Delete") || methodName.StartsWith("Remove"))
                return "Delete";
            if (methodName.StartsWith("Patch"))
                return "Patch";
            
            return "Post"; // 默认
        }

        private string GenerateRouteTemplate(string methodName, ImmutableArray<IParameterSymbol> parameters)
        {
            if (methodName.StartsWith("Get"))
            {
                // GetById -> {id}
                if (methodName.EndsWith("ById") && parameters.Length > 0)
                    return $"{{{parameters[0].Name}}}";
                // GetAll -> 空路由
                if (methodName.EndsWith("All") || methodName == "Get")
                    return "";
                // GetByXxx -> byxxx
                if (methodName.StartsWith("GetBy") && parameters.Length > 0)
                    return $"by{methodName.Substring(5).ToLowerInvariant()}/{{{parameters[0].Name}}}";
            }
            
            if (methodName.StartsWith("Create") || methodName.StartsWith("Add"))
            {
                return "";
            }
            
            if (methodName.StartsWith("Update") && parameters.Length > 0)
            {
                return $"{{{parameters[0].Name}}}";
            }
            
            if (methodName.StartsWith("Delete") && parameters.Length > 0)
            {
                return $"{{{parameters[0].Name}}}";
            }
            
            // 其他情况，使用方法名的小写形式
            return methodName.ToLowerInvariant();
        }

        // 生成服务接口
        private void GenerateServiceInterface(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            // 检查是否已经有接口
            var hasInterface = serviceClass.Interfaces.Any(i => 
                i.Name.StartsWith("I") && i.Name.Substring(1) == serviceName);
            
            if (hasInterface)
                return;
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的服务接口");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public interface I{serviceName}");
            builder.AppendLine("    {");
            
            // 获取所有公共方法
            var methods = serviceClass.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && 
                           !m.IsStatic &&
                           m.MethodKind == MethodKind.Ordinary);
            
            foreach (var method in methods)
            {
                builder.AppendLine("        /// <summary>");
                builder.AppendLine($"        /// {method.Name}");
                builder.AppendLine("        /// </summary>");
                
                builder.Append($"        {method.ReturnType.ToDisplayString()} {method.Name}(");
                
                var parameters = new List<string>();
                foreach (var param in method.Parameters)
                {
                    parameters.Add($"{param.Type.ToDisplayString()} {param.Name}");
                }
                
                builder.Append(string.Join(", ", parameters));
                builder.AppendLine(");");
                builder.AppendLine();
            }
            
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"I{serviceName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        // 生成服务扩展方法
        private void GenerateServiceExtensions(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Extensions");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的扩展方法");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public static class {serviceName}Extensions");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 安全执行服务方法，捕获异常");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public static async Task<(bool Success, T? Result, string? Error)> TryExecuteAsync<T>(");
            builder.AppendLine($"            this I{serviceName} service,");
            builder.AppendLine($"            Func<I{serviceName}, Task<T>> action)");
            builder.AppendLine("        {");
            builder.AppendLine("            try");
            builder.AppendLine("            {");
            builder.AppendLine("                var result = await action(service);");
            builder.AppendLine("                return (true, result, null);");
            builder.AppendLine("            }");
            builder.AppendLine("            catch (Exception ex)");
            builder.AppendLine("            {");
            builder.AppendLine("                return (false, default, ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{serviceName}Extensions.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        // 生成服务测试基类
        private void GenerateServiceTestBase(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Linq.Expressions;");
            builder.AppendLine("using Xunit;");
            builder.AppendLine("using Moq;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Tests");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的测试基类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public abstract class {serviceName}TestBase");
            builder.AppendLine("    {");
            builder.AppendLine($"        protected Mock<I{serviceName}> ServiceMock {{ get; }}");
            builder.AppendLine($"        protected I{serviceName} Service => ServiceMock.Object;");
            builder.AppendLine();
            builder.AppendLine($"        protected {serviceName}TestBase()");
            builder.AppendLine("        {");
            builder.AppendLine($"            ServiceMock = new Mock<I{serviceName}>();");
            builder.AppendLine("            SetupMocks();");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 设置Mock对象的行为");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected virtual void SetupMocks()");
            builder.AppendLine("        {");
            builder.AppendLine("            // 在派生类中重写此方法以设置特定的Mock行为");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 验证Mock方法被调用");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected void VerifyServiceCalled(");
            builder.AppendLine("            Expression<Action<I" + serviceName + ">> expression,");
            builder.AppendLine("            Times? times = null)");
            builder.AppendLine("        {");
            builder.AppendLine("            ServiceMock.Verify(expression, times ?? Times.Once());");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 验证Mock方法被调用并返回结果");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected void VerifyServiceCalled<TResult>(");
            builder.AppendLine("            Expression<Func<I" + serviceName + ", TResult>> expression,");
            builder.AppendLine("            Times? times = null)");
            builder.AppendLine("        {");
            builder.AppendLine("            ServiceMock.Verify(expression, times ?? Times.Once());");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{serviceName}TestBase.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private T GetAttributeProperty<T>(ISymbol symbol, string propertyName, T defaultValue)
        {
            if (symbol == null)
                return defaultValue;
                
            var attr = symbol.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.Name == "ServiceAttribute" || 
                                     attr.AttributeClass?.Name == "Service");

            if (attr == null)
                return defaultValue;

            var namedArg = attr.NamedArguments
                .FirstOrDefault(arg => arg.Key == propertyName);

            if (namedArg.Key == propertyName && namedArg.Value.Value is T value)
                return value;

            return defaultValue;
        }
}
}
