using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.ServiceGenerator
{
    [Generator]
    public class ServiceSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 创建增量数据源：查找带有ServiceAttribute的类
            var serviceClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsServiceCandidate(node),
                    transform: static (ctx, _) => GetServiceClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            // 注册源代码生成
            context.RegisterSourceOutput(serviceClasses, ExecuteGeneration);
        }

        private static bool IsServiceCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static bool HasServiceAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass != null && (
                    attr.AttributeClass.Name == "ServiceAttribute" ||
                    attr.AttributeClass.Name == "Service" ||
                    attr.AttributeClass.ToDisplayString() == "CrestCreates.Domain.Shared.Attributes.ServiceAttribute"
                ));
        }

        private static INamedTypeSymbol? GetServiceClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && HasServiceAttribute(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> serviceClasses)
        {
            if (serviceClasses.IsDefaultOrEmpty)
                return;

            // 去重处理
            var uniqueServices = serviceClasses
                .Where(s => s != null)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .ToList();

            try
            {
                // 先生成服务接口（如果不存在）
                foreach (var service in uniqueServices)
                {
                    GenerateServiceInterface(context, service);
                }
                
                // 生成服务异常类
                foreach (var service in uniqueServices)
                {
                    GenerateServiceExceptions(context, service);
                }
                
                // 生成验证器
                foreach (var service in uniqueServices)
                {
                    GenerateValidators(context, service);
                }
                
                // 生成服务注册代码
                GenerateServiceRegistration(context, uniqueServices.ToArray());
                
                // 生成服务扩展方法
                // foreach (var service in uniqueServices)
                // {
                //     GenerateServiceExtensions(context, service);
                // }
                
                // 生成服务测试基类
                // foreach (var service in uniqueServices)
                // {
                //     GenerateServiceTestBase(context, service);
                // }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CCCG002", "Service generation error",
                        $"Error generating service code: {ex.Message}",
                        "CodeGeneration", DiagnosticSeverity.Warning, true),
                    Location.None));
            }
        }

        // 生成服务异常类
        private void GenerateServiceExceptions(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            var exceptionClassName = $"{serviceName}Exception";
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Runtime.Serialization;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Exceptions");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 服务异常类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    [Serializable]");
            builder.AppendLine($"    public class {exceptionClassName} : Exception");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 错误码");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        public string ErrorCode { get; set; }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public {exceptionClassName}() : base()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine($"        public {exceptionClassName}(string message) : base(message)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"errorCode\">错误码</param>");
            builder.AppendLine($"        public {exceptionClassName}(string message, string errorCode) : base(message)");
            builder.AppendLine("        {");
            builder.AppendLine("            ErrorCode = errorCode;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"innerException\">内部异常</param>");
            builder.AppendLine($"        public {exceptionClassName}(string message, Exception innerException) : base(message, innerException)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"errorCode\">错误码</param>");
            builder.AppendLine("        /// <param name=\"innerException\">内部异常</param>");
            builder.AppendLine($"        public {exceptionClassName}(string message, string errorCode, Exception innerException) : base(message, innerException)");
            builder.AppendLine("        {");
            builder.AppendLine("            ErrorCode = errorCode;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 序列化构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"info\">序列化信息</param>");
            builder.AppendLine("        /// <param name=\"context\">序列化上下文</param>");
            builder.AppendLine($"        protected {exceptionClassName}(SerializationInfo info, StreamingContext context) : base(info, context)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (info != null)");
            builder.AppendLine("            {");
            builder.AppendLine("                ErrorCode = info.GetString(\"ErrorCode\");");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 序列化方法");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"info\">序列化信息</param>");
            builder.AppendLine("        /// <param name=\"context\">序列化上下文</param>");
            builder.AppendLine("        public override void GetObjectData(SerializationInfo info, StreamingContext context)");
            builder.AppendLine("        {");
            builder.AppendLine("            base.GetObjectData(info, context);");
            builder.AppendLine("            if (info != null)");
            builder.AppendLine("            {");
            builder.AppendLine("                info.AddValue(\"ErrorCode\", ErrorCode);");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 服务参数异常类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    [Serializable]");
            builder.AppendLine($"    public class {serviceName}ValidationException : {exceptionClassName}");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public {serviceName}ValidationException() : base()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine($"        public {serviceName}ValidationException(string message) : base(message, \"VALIDATION_ERROR\")");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"innerException\">内部异常</param>");
            builder.AppendLine($"        public {serviceName}ValidationException(string message, Exception innerException) : base(message, \"VALIDATION_ERROR\", innerException)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 序列化构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"info\">序列化信息</param>");
            builder.AppendLine("        /// <param name=\"context\">序列化上下文</param>");
            builder.AppendLine($"        protected {serviceName}ValidationException(SerializationInfo info, StreamingContext context) : base(info, context)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 服务业务异常类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    [Serializable]");
            builder.AppendLine($"    public class {serviceName}BusinessException : {exceptionClassName}");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public {serviceName}BusinessException() : base()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine($"        public {serviceName}BusinessException(string message) : base(message, \"BUSINESS_ERROR\")");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"innerException\">内部异常</param>");
            builder.AppendLine($"        public {serviceName}BusinessException(string message, Exception innerException) : base(message, \"BUSINESS_ERROR\", innerException)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 序列化构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"info\">序列化信息</param>");
            builder.AppendLine("        /// <param name=\"context\">序列化上下文</param>");
            builder.AppendLine($"        protected {serviceName}BusinessException(SerializationInfo info, StreamingContext context) : base(info, context)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 服务未找到异常类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    [Serializable]");
            builder.AppendLine($"    public class {serviceName}NotFoundException : {exceptionClassName}");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public {serviceName}NotFoundException() : base()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine($"        public {serviceName}NotFoundException(string message) : base(message, \"NOT_FOUND\")");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"message\">错误消息</param>");
            builder.AppendLine("        /// <param name=\"innerException\">内部异常</param>");
            builder.AppendLine($"        public {serviceName}NotFoundException(string message, Exception innerException) : base(message, \"NOT_FOUND\", innerException)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 序列化构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        /// <param name=\"info\">序列化信息</param>");
            builder.AppendLine("        /// <param name=\"context\">序列化上下文</param>");
            builder.AppendLine($"        protected {serviceName}NotFoundException(SerializationInfo info, StreamingContext context) : base(info, context)");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{exceptionClassName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private void GenerateServiceRegistration(SourceProductionContext context, INamedTypeSymbol[] serviceClasses)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            builder.AppendLine("using FluentValidation;");
            builder.AppendLine();
            builder.AppendLine("namespace CrestCreates.Infrastructure.DependencyInjection");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// 自动生成的服务注册扩展类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public static class AutoServiceRegistration");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 注册所有自动生成的服务");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        public static IServiceCollection AddGeneratedServices(this IServiceCollection services)");
            builder.AppendLine("        {");
            builder.AppendLine("            // 注册 FluentValidation");
            builder.AppendLine("            // services.AddValidatorsFromAssembly(typeof(AutoServiceRegistration).Assembly);");
            builder.AppendLine("            // services.AddTransient<IValidatorFactory, ServiceProviderValidatorFactory>();");
            builder.AppendLine();

            foreach (var service in serviceClasses)
            {
                var serviceType = service.ToDisplayString();
                bool hasInterface = false;
                string? interfaceType = null;
                
                // 查找该服务的接口
                foreach (var interfaceSymbol in service.Interfaces)
                {
                    if (interfaceSymbol.Name.StartsWith("I") && 
                        interfaceSymbol.Name.Substring(1) == service.Name)
                    {
                        interfaceType = interfaceSymbol.ToDisplayString();
                        hasInterface = true;
                        break;
                    }
                }

                var lifetimeEnum = GetAttributeProperty(service, "Lifetime", 0);
                var lifetime = lifetimeEnum switch
                {
                    0 => "Scoped",
                    1 => "Singleton",
                    2 => "Transient",
                    _ => "Scoped"
                };
                
                builder.AppendLine($"            // {service.Name} - {lifetime}");
                if (hasInterface && interfaceType != null)
                {
                    builder.AppendLine($"            services.Add{lifetime}<{interfaceType}, {serviceType}>();");
                }
                else
                {
                    builder.AppendLine($"            services.Add{lifetime}<{serviceType}>();");
                }
                builder.AppendLine();
            }

            builder.AppendLine("            return services;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource("AutoServiceRegistration.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        // 生成服务接口
        private void GenerateServiceInterface(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            // 检查是否已经有接口
            var hasInterface = serviceClass.Interfaces.Any(i => 
                i.Name.StartsWith("I") && i.Name.Substring(1) == serviceName);
            
            if (hasInterface)
                return;
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的服务接口");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public interface I{serviceName}");
            builder.AppendLine("    {");
            
            // 获取所有公共方法
            var methods = serviceClass.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && 
                           !m.IsStatic &&
                           m.MethodKind == MethodKind.Ordinary);
            
            foreach (var method in methods)
            {
                builder.AppendLine("        /// <summary>");
                builder.AppendLine($"        /// {method.Name}");
                builder.AppendLine("        /// </summary>");
                
                builder.Append($"        {method.ReturnType.ToDisplayString()} {method.Name}(");
                
                var parameters = new List<string>();
                foreach (var param in method.Parameters)
                {
                    parameters.Add($"{param.Type.ToDisplayString()} {param.Name}");
                }
                
                builder.Append(string.Join(", ", parameters));
                builder.AppendLine(");");
                builder.AppendLine();
            }
            
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"I{serviceName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        // 生成服务扩展方法
        private void GenerateServiceExtensions(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Extensions");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的扩展方法");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public static class {serviceName}Extensions");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 安全执行服务方法，捕获异常");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public static async Task<(bool Success, T? Result, string? Error)> TryExecuteAsync<T>(");
            builder.AppendLine($"            this I{serviceName} service,");
            builder.AppendLine($"            Func<I{serviceName}, Task<T>> action)");
            builder.AppendLine("        {");
            builder.AppendLine("            try");
            builder.AppendLine("            {");
            builder.AppendLine("                var result = await action(service);");
            builder.AppendLine("                return (true, result, null);");
            builder.AppendLine("            }");
            builder.AppendLine("            catch (Exception ex)");
            builder.AppendLine("            {");
            builder.AppendLine("                return (false, default, ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{serviceName}Extensions.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        // 生成服务测试基类
        private void GenerateServiceTestBase(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Linq.Expressions;");
            builder.AppendLine("using Xunit;");
            builder.AppendLine("using Moq;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Tests");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {serviceName} 的测试基类");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public abstract class {serviceName}TestBase");
            builder.AppendLine("    {");
            builder.AppendLine($"        protected Mock<I{serviceName}> ServiceMock {{ get; }}");
            builder.AppendLine($"        protected I{serviceName} Service => ServiceMock.Object;");
            builder.AppendLine();
            builder.AppendLine($"        protected {serviceName}TestBase()");
            builder.AppendLine("        {");
            builder.AppendLine($"            ServiceMock = new Mock<I{serviceName}>();");
            builder.AppendLine("            SetupMocks();");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 设置Mock对象的行为");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected virtual void SetupMocks()");
            builder.AppendLine("        {");
            builder.AppendLine("            // 在派生类中重写此方法以设置特定的Mock行为");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 验证Mock方法被调用");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected void VerifyServiceCalled(");
            builder.AppendLine("            Expression<Action<I" + serviceName + ">> expression,");
            builder.AppendLine("            Times? times = null)");
            builder.AppendLine("        {");
            builder.AppendLine("            ServiceMock.Verify(expression, times ?? Times.Once());");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 验证Mock方法被调用并返回结果");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine("        protected void VerifyServiceCalled<TResult>(");
            builder.AppendLine("            Expression<Func<I" + serviceName + ", TResult>> expression,");
            builder.AppendLine("            Times? times = null)");
            builder.AppendLine("        {");
            builder.AppendLine("            ServiceMock.Verify(expression, times ?? Times.Once());");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{serviceName}TestBase.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private T GetAttributeProperty<T>(ISymbol symbol, string propertyName, T defaultValue)
        {
            if (symbol == null)
                return defaultValue;
                
            var attr = symbol.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.Name == "ServiceAttribute" || 
                                     attr.AttributeClass?.Name == "Service");

            if (attr == null)
                return defaultValue;

            var namedArg = attr.NamedArguments
                .FirstOrDefault(arg => arg.Key == propertyName);

            if (namedArg.Key == propertyName && namedArg.Value.Value is T value)
                return value;

            return defaultValue;
        }

        // 生成验证器
        private void GenerateValidators(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            
            // 获取服务的所有公共方法
            var methods = serviceClass.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && 
                           !m.IsStatic &&
                           m.MethodKind == MethodKind.Ordinary);
            
            // 收集所有 DTO 类型
            var dtoTypes = new HashSet<ITypeSymbol>();
            foreach (var method in methods)
            {
                foreach (var parameter in method.Parameters)
                {
                    var paramType = parameter.Type;
                    if (IsDtoType(paramType))
                    {
                        dtoTypes.Add(paramType);
                    }
                }
            }
            
            // 为每个 DTO 生成验证器
            foreach (var dtoType in dtoTypes)
            {
                GenerateDtoValidator(context, dtoType, namespaceName);
            }
        }

        private bool IsDtoType(ITypeSymbol type)
        {
            var typeName = type.Name;
            return typeName.EndsWith("Dto") || 
                   typeName.EndsWith("Request") || 
                   typeName.EndsWith("Input") || 
                   typeName.EndsWith("Command");
        }

        private void GenerateDtoValidator(SourceProductionContext context, ITypeSymbol dtoType, string namespaceName)
        {
            var dtoName = dtoType.Name;
            var validatorName = $"{dtoName}Validator";
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using FluentValidation;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Validators");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {dtoName} 的验证器");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public class {validatorName} : AbstractValidator<{dtoType.ToDisplayString()}>");
            builder.AppendLine("    {");
            builder.AppendLine("        /// <summary>");
            builder.AppendLine("        /// 构造函数");
            builder.AppendLine("        /// </summary>");
            builder.AppendLine($"        public {validatorName}()");
            builder.AppendLine("        {");
            
            // 生成验证规则
            GenerateValidationRules(builder, dtoType);
            
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            context.AddSource($"{validatorName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private void GenerateValidationRules(StringBuilder builder, ITypeSymbol dtoType)
        {
            // 获取 DTO 的所有属性
            var properties = dtoType.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && 
                           !p.IsStatic &&
                           p.SetMethod != null);
            
            foreach (var property in properties)
            {
                var propertyName = property.Name;
                var propertyType = property.Type;
                var typeName = propertyType.Name;
                
                // 根据属性类型生成验证规则
                switch (typeName)
                {
                    case "String":
                        builder.AppendLine($"            RuleFor(x => x.{propertyName}).NotEmpty().WithMessage(\"{propertyName} 不能为空\");");
                        // 检查是否是邮箱、URL等特殊字符串
                        if (propertyName.Contains("Email", StringComparison.OrdinalIgnoreCase))
                        {
                            builder.AppendLine($"            RuleFor(x => x.{propertyName}).EmailAddress().WithMessage(\"{propertyName} 格式不正确\");");
                        }
                        else if (propertyName.Contains("Url", StringComparison.OrdinalIgnoreCase) || 
                                 propertyName.Contains("Uri", StringComparison.OrdinalIgnoreCase))
                        {
                            builder.AppendLine($"            RuleFor(x => x.{propertyName}).Url().WithMessage(\"{propertyName} 格式不正确\");");
                        }
                        break;
                    
                    case "Int32":
                    case "Int64":
                    case "Double":
                    case "Decimal":
                        builder.AppendLine($"            RuleFor(x => x.{propertyName}).GreaterThan(0).WithMessage(\"{propertyName} 必须大于 0\");");
                        break;
                    
                    case "Boolean":
                        // 布尔类型通常不需要验证
                        break;
                    
                    case "Guid":
                        builder.AppendLine($"            RuleFor(x => x.{propertyName}).NotEmpty().WithMessage(\"{propertyName} 不能为空\");");
                        break;
                    
                    case "DateTime":
                        builder.AppendLine($"            RuleFor(x => x.{propertyName}).NotEmpty().WithMessage(\"{propertyName} 不能为空\");");
                        builder.AppendLine($"            RuleFor(x => x.{propertyName}).LessThanOrEqualTo(DateTime.Now).WithMessage(\"{propertyName} 不能超过当前时间\");");
                        break;
                    
                    default:
                        // 复杂类型，检查是否是集合
                        if (propertyType is INamedTypeSymbol namedType && 
                            namedType.IsGenericType && 
                            namedType.ConstructedFrom.Name == "List" && 
                            namedType.TypeArguments.Length > 0)
                        {
                            builder.AppendLine($"            RuleFor(x => x.{propertyName}).NotEmpty().WithMessage(\"{propertyName} 不能为空\");");
                            builder.AppendLine($"            RuleFor(x => x.{propertyName}).Must(list => list.Count > 0).WithMessage(\"{propertyName} 至少包含一个元素\");");
                        }
                        break;
                }
            }
        }
}
}