using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.QueryBuilderGenerator
{
    [Generator]
    public class QueryBuilderSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var queryBuilderClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsQueryBuilderCandidate(node),
                    transform: static (ctx, _) => GetQueryBuilderClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            context.RegisterSourceOutput(queryBuilderClasses, ExecuteGeneration);
        }

        private static bool IsQueryBuilderCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetQueryBuilderClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol != null && HasGenerateQueryBuilderAttribute(symbol))
            {
                return symbol;
            }

            return null;
        }

        private static bool HasGenerateQueryBuilderAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "GenerateQueryBuilderAttribute" ||
                attr.AttributeClass?.Name == "GenerateQueryBuilder");
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> entityClasses)
        {
            if (entityClasses.IsDefaultOrEmpty) return;

            var processedEntities = new HashSet<string>();

            foreach (var entityClass in entityClasses)
            {
                if (entityClass == null) continue;

                var entityFullName = entityClass.ToDisplayString();
                if (processedEntities.Contains(entityFullName)) continue;

                processedEntities.Add(entityFullName);

                try
                {
                    GenerateFilterBuilder(context, entityClass);
                    GenerateSortBuilder(context, entityClass);
                    GenerateQueryRequest(context, entityClass);
                    GenerateQueryExecutor(context, entityClass);
                }
                catch (Exception ex)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("CCQB001", "QueryBuilder generation error",
                            $"Error generating query builder for {entityFullName}: {ex.Message}",
                            "CodeGeneration", DiagnosticSeverity.Warning, true),
                        Location.None));
                }
            }
        }

        private void GenerateFilterBuilder(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetQueryableProperties(entityClass);

            var sourceCode = new StringBuilder();
            sourceCode.AppendLine("#nullable enable");
            sourceCode.AppendLine("// <auto-generated />");
            sourceCode.AppendLine("using System;");
            sourceCode.AppendLine("using System.Collections.Generic;");
            sourceCode.AppendLine("using System.Linq;");
            sourceCode.AppendLine("using System.Linq.Expressions;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.DTOs;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.Enums;");
            sourceCode.AppendLine($"using {namespaceName};");
            sourceCode.AppendLine();
            sourceCode.AppendLine($"namespace {namespaceName}.QueryBuilders");
            sourceCode.AppendLine("{");
            sourceCode.AppendLine($"    /// <summary>");
            sourceCode.AppendLine($"    /// {entityName} 的过滤器构建器");
            sourceCode.AppendLine($"    /// </summary>");
            sourceCode.AppendLine($"    public class {entityName}FilterBuilder");
            sourceCode.AppendLine("    {");
            sourceCode.AppendLine("        private readonly List<FilterDescriptor> _filters = new();");
            sourceCode.AppendLine("        private FilterOperator _currentOperator = FilterOperator.Equals;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 获取所有过滤器");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public IReadOnlyList<FilterDescriptor> Filters => _filters;");
            sourceCode.AppendLine();

            // 生成 Where 方法（等值过滤）
            foreach (var prop in properties)
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 过滤（等值）");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}({propType} value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.Equals, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成字符串属性的 Contains 方法（模糊查询）
            foreach (var prop in properties.Where(p => IsStringType(p.Type)))
            {
                var propName = prop.Name;

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 模糊查询（包含）");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}Contains(string value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.Contains, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 开头匹配");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}StartsWith(string value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.StartsWith, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 结尾匹配");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}EndsWith(string value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.EndsWith, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成数值/日期属性的 Between 方法（范围查询）
            foreach (var prop in properties.Where(p => IsNumericOrDateType(p.Type)))
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 范围过滤");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}Between({propType} from, {propType} to)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.GreaterThanOrEqual, from));");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.LessThanOrEqual, to));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 大于过滤");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}GreaterThan({propType} value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.GreaterThan, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 小于过滤");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}FilterBuilder Where{propName}LessThan({propType} value)");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _filters.Add(new FilterDescriptor(\"{propName}\", FilterOperator.LessThan, value));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成 And、Or 条件组合方法
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 添加自定义过滤器");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}FilterBuilder AddFilter(FilterDescriptor filter)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            _filters.Add(filter);");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 添加多个过滤器（And 关系）");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}FilterBuilder And(Action<{entityName}FilterBuilder> configure)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine($"            var builder = new {entityName}FilterBuilder();");
            sourceCode.AppendLine("            configure(builder);");
            sourceCode.AppendLine("            _filters.AddRange(builder.Filters);");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 清空所有过滤器");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}FilterBuilder Clear()");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            _filters.Clear();");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 构建过滤器列表");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public List<FilterDescriptor> Build()");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            return new List<FilterDescriptor>(_filters);");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine("    }");
            sourceCode.AppendLine("}");

            context.AddSource($"{entityName}FilterBuilder.g.cs", SourceText.From(sourceCode.ToString(), Encoding.UTF8));
        }

        private void GenerateSortBuilder(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetQueryableProperties(entityClass);

            var sourceCode = new StringBuilder();
            sourceCode.AppendLine("#nullable enable");
            sourceCode.AppendLine("// <auto-generated />");
            sourceCode.AppendLine("using System;");
            sourceCode.AppendLine("using System.Collections.Generic;");
            sourceCode.AppendLine("using System.Linq;");
            sourceCode.AppendLine("using System.Linq.Expressions;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.DTOs;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.Enums;");
            sourceCode.AppendLine($"using {namespaceName};");
            sourceCode.AppendLine();
            sourceCode.AppendLine($"namespace {namespaceName}.QueryBuilders");
            sourceCode.AppendLine("{");
            sourceCode.AppendLine($"    /// <summary>");
            sourceCode.AppendLine($"    /// {entityName} 的排序构建器");
            sourceCode.AppendLine($"    /// </summary>");
            sourceCode.AppendLine($"    public class {entityName}SortBuilder");
            sourceCode.AppendLine("    {");
            sourceCode.AppendLine("        private readonly List<SortDescriptor> _sorts = new();");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 获取所有排序规则");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public IReadOnlyList<SortDescriptor> Sorts => _sorts;");
            sourceCode.AppendLine();

            // 生成 OrderBy 方法（升序）
            foreach (var prop in properties)
            {
                var propName = prop.Name;

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 升序排序");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}SortBuilder OrderBy{propName}()");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _sorts.Add(new SortDescriptor(\"{propName}\", SortDirection.Ascending));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成 OrderByDescending 方法（降序）
            foreach (var prop in properties)
            {
                var propName = prop.Name;

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 按 {propName} 降序排序");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}SortBuilder OrderBy{propName}Descending()");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _sorts.Add(new SortDescriptor(\"{propName}\", SortDirection.Descending));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成 ThenBy 多级排序方法
            foreach (var prop in properties)
            {
                var propName = prop.Name;

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 然后按 {propName} 升序排序");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}SortBuilder ThenBy{propName}()");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _sorts.Add(new SortDescriptor(\"{propName}\", SortDirection.Ascending));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();

                sourceCode.AppendLine($"        /// <summary>");
                sourceCode.AppendLine($"        /// 然后按 {propName} 降序排序");
                sourceCode.AppendLine($"        /// </summary>");
                sourceCode.AppendLine($"        public {entityName}SortBuilder ThenBy{propName}Descending()");
                sourceCode.AppendLine("        {");
                sourceCode.AppendLine($"            _sorts.Add(new SortDescriptor(\"{propName}\", SortDirection.Descending));");
                sourceCode.AppendLine("            return this;");
                sourceCode.AppendLine("        }");
                sourceCode.AppendLine();
            }

            // 生成通用方法
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 添加自定义排序");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}SortBuilder AddSort(SortDescriptor sort)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            _sorts.Add(sort);");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 清空所有排序");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}SortBuilder Clear()");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            _sorts.Clear();");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 构建排序列表");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public List<SortDescriptor> Build()");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            return new List<SortDescriptor>(_sorts);");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine("    }");
            sourceCode.AppendLine("}");

            context.AddSource($"{entityName}SortBuilder.g.cs", SourceText.From(sourceCode.ToString(), Encoding.UTF8));
        }

        private void GenerateQueryRequest(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();

            var sourceCode = new StringBuilder();
            sourceCode.AppendLine("#nullable enable");
            sourceCode.AppendLine("// <auto-generated />");
            sourceCode.AppendLine("using System;");
            sourceCode.AppendLine("using System.Collections.Generic;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.DTOs;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.Enums;");
            sourceCode.AppendLine($"using {namespaceName};");
            sourceCode.AppendLine();
            sourceCode.AppendLine($"namespace {namespaceName}.QueryBuilders");
            sourceCode.AppendLine("{");
            sourceCode.AppendLine($"    /// <summary>");
            sourceCode.AppendLine($"    /// {entityName} 的查询请求");
            sourceCode.AppendLine($"    /// </summary>");
            sourceCode.AppendLine($"    public class {entityName}QueryRequest");
            sourceCode.AppendLine("    {");
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 过滤器列表");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public List<FilterDescriptor> Filters { get; set; } = new();");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 排序列表");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public List<SortDescriptor> Sorts { get; set; } = new();");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 分页信息");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine("        public PagedRequestDto Paging { get; set; } = new();");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 创建空的查询请求");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest()");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 从过滤器构建器创建");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest({entityName}FilterBuilder filterBuilder)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Filters = filterBuilder.Build();");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 从排序构建器创建");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest({entityName}SortBuilder sortBuilder)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Sorts = sortBuilder.Build();");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 从过滤器和排序构建器创建");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest({entityName}FilterBuilder filterBuilder, {entityName}SortBuilder sortBuilder)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Filters = filterBuilder.Build();");
            sourceCode.AppendLine("            Sorts = sortBuilder.Build();");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 设置分页");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest WithPaging(int pageIndex, int pageSize)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Paging.PageIndex = pageIndex;");
            sourceCode.AppendLine("            Paging.PageSize = pageSize;");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 添加过滤器");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest AddFilter(FilterDescriptor filter)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Filters.Add(filter);");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 添加排序");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public {entityName}QueryRequest AddSort(SortDescriptor sort)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            Sorts.Add(sort);");
            sourceCode.AppendLine("            return this;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine("    }");
            sourceCode.AppendLine("}");

            context.AddSource($"{entityName}QueryRequest.g.cs", SourceText.From(sourceCode.ToString(), Encoding.UTF8));
        }

        private void GenerateQueryExecutor(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetQueryableProperties(entityClass);

            var sourceCode = new StringBuilder();
            sourceCode.AppendLine("#nullable enable");
            sourceCode.AppendLine("// <auto-generated />");
            sourceCode.AppendLine("using System;");
            sourceCode.AppendLine("using System.Collections.Generic;");
            sourceCode.AppendLine("using System.Linq;");
            sourceCode.AppendLine("using System.Linq.Expressions;");
            sourceCode.AppendLine("using System.Reflection;");
            sourceCode.AppendLine("using System.Threading;");
            sourceCode.AppendLine("using System.Threading.Tasks;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.DTOs;");
            sourceCode.AppendLine("using CrestCreates.Domain.Shared.Enums;");
            sourceCode.AppendLine($"using {namespaceName};");
            sourceCode.AppendLine($"using {namespaceName}.QueryBuilders;");
            sourceCode.AppendLine();
            sourceCode.AppendLine($"namespace {namespaceName}.QueryBuilders");
            sourceCode.AppendLine("{");
            sourceCode.AppendLine($"    /// <summary>");
            sourceCode.AppendLine($"    /// {entityName} 的查询执行器");
            sourceCode.AppendLine($"    /// </summary>");
            sourceCode.AppendLine($"    public class {entityName}QueryExecutor");
            sourceCode.AppendLine("    {");
            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 执行查询");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static IQueryable<{entityName}> ApplyFilters(IQueryable<{entityName}> query, {entityName}QueryRequest request)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            if (request?.Filters == null || !request.Filters.Any())");
            sourceCode.AppendLine("                return query;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            foreach (var filter in request.Filters)");
            sourceCode.AppendLine("            {");
            sourceCode.AppendLine("                query = ApplyFilter(query, filter);");
            sourceCode.AppendLine("            }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            return query;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 应用单个过滤器");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        private static IQueryable<{entityName}> ApplyFilter(IQueryable<{entityName}> query, FilterDescriptor filter)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"x\");");
            sourceCode.AppendLine("            var property = Expression.Property(parameter, filter.Field);");
            sourceCode.AppendLine("            var constant = Expression.Constant(filter.Value);");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            Expression? predicate = null;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            switch (filter.Operator)");
            sourceCode.AppendLine("            {");
            sourceCode.AppendLine("                case FilterOperator.Equals:");
            sourceCode.AppendLine("                    predicate = Expression.Equal(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.NotEquals:");
            sourceCode.AppendLine("                    predicate = Expression.NotEqual(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.GreaterThan:");
            sourceCode.AppendLine("                    predicate = Expression.GreaterThan(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.GreaterThanOrEqual:");
            sourceCode.AppendLine("                    predicate = Expression.GreaterThanOrEqual(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.LessThan:");
            sourceCode.AppendLine("                    predicate = Expression.LessThan(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.LessThanOrEqual:");
            sourceCode.AppendLine("                    predicate = Expression.LessThanOrEqual(property, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.Contains:");
            sourceCode.AppendLine("                    var containsMethod = typeof(string).GetMethod(\"Contains\", new[] { typeof(string) });");
            sourceCode.AppendLine("                    if (containsMethod != null)");
            sourceCode.AppendLine("                        predicate = Expression.Call(property, containsMethod, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.StartsWith:");
            sourceCode.AppendLine("                    var startsWithMethod = typeof(string).GetMethod(\"StartsWith\", new[] { typeof(string) });");
            sourceCode.AppendLine("                    if (startsWithMethod != null)");
            sourceCode.AppendLine("                        predicate = Expression.Call(property, startsWithMethod, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("                case FilterOperator.EndsWith:");
            sourceCode.AppendLine("                    var endsWithMethod = typeof(string).GetMethod(\"EndsWith\", new[] { typeof(string) });");
            sourceCode.AppendLine("                    if (endsWithMethod != null)");
            sourceCode.AppendLine("                        predicate = Expression.Call(property, endsWithMethod, constant);");
            sourceCode.AppendLine("                    break;");
            sourceCode.AppendLine("            }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            if (predicate != null)");
            sourceCode.AppendLine("            {");
            sourceCode.AppendLine($"                var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
            sourceCode.AppendLine("                query = query.Where(lambda);");
            sourceCode.AppendLine("            }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            return query;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 应用排序");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static IQueryable<{entityName}> ApplySorts(IQueryable<{entityName}> query, {entityName}QueryRequest request)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            if (request?.Sorts == null || !request.Sorts.Any())");
            sourceCode.AppendLine("                return query;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            bool isFirstSort = true;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            foreach (var sort in request.Sorts)");
            sourceCode.AppendLine("            {");
            sourceCode.AppendLine("                query = ApplySort(query, sort, ref isFirstSort);");
            sourceCode.AppendLine("            }");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            return query;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 应用单个排序");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        private static IQueryable<{entityName}> ApplySort(IQueryable<{entityName}> query, SortDescriptor sort, ref bool isFirstSort)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"x\");");
            sourceCode.AppendLine("            var property = Expression.Property(parameter, sort.Field);");
            sourceCode.AppendLine("            var lambda = Expression.Lambda(property, parameter);");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            var methodName = isFirstSort");
            sourceCode.AppendLine("                ? (sort.Direction == SortDirection.Ascending ? \"OrderBy\" : \"OrderByDescending\")");
            sourceCode.AppendLine("                : (sort.Direction == SortDirection.Ascending ? \"ThenBy\" : \"ThenByDescending\");");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            var method = typeof(Queryable).GetMethods()");
            sourceCode.AppendLine("                .Where(m => m.Name == methodName && m.GetParameters().Length == 2)");
            sourceCode.AppendLine("                .Single()");
            sourceCode.AppendLine($"                .MakeGenericMethod(typeof({entityName}), property.Type);");
            sourceCode.AppendLine();
            sourceCode.AppendLine($"            query = (IQueryable<{entityName}>)method.Invoke(null, new object[] {{ query, lambda }});");
            sourceCode.AppendLine("            isFirstSort = false;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            return query;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 应用分页");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static IQueryable<{entityName}> ApplyPaging(IQueryable<{entityName}> query, {entityName}QueryRequest request)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            if (request?.Paging == null)");
            sourceCode.AppendLine("                return query;");
            sourceCode.AppendLine();
            sourceCode.AppendLine("            var skipCount = request.Paging.GetSkipCount();");
            sourceCode.AppendLine("            return query.Skip(skipCount).Take(request.Paging.PageSize);");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 执行完整查询（过滤、排序、分页）");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static IQueryable<{entityName}> Execute(IQueryable<{entityName}> query, {entityName}QueryRequest request)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            query = ApplyFilters(query, request);");
            sourceCode.AppendLine("            query = ApplySorts(query, request);");
            sourceCode.AppendLine("            query = ApplyPaging(query, request);");
            sourceCode.AppendLine("            return query;");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 获取总记录数（应用过滤后）");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static int GetTotalCount(IQueryable<{entityName}> query, {entityName}QueryRequest request)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            query = ApplyFilters(query, request);");
            sourceCode.AppendLine("            return query.Count();");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine();

            sourceCode.AppendLine("        /// <summary>");
            sourceCode.AppendLine("        /// 获取总记录数（异步，应用过滤后）");
            sourceCode.AppendLine("        /// </summary>");
            sourceCode.AppendLine($"        public static async Task<int> GetTotalCountAsync(IQueryable<{entityName}> query, {entityName}QueryRequest request, CancellationToken cancellationToken = default)");
            sourceCode.AppendLine("        {");
            sourceCode.AppendLine("            query = ApplyFilters(query, request);");
            sourceCode.AppendLine("            // 注意：实际使用时需要引用 Microsoft.EntityFrameworkCore 或使用 IAsyncEnumerable");
            sourceCode.AppendLine("            return await Task.FromResult(query.Count());");
            sourceCode.AppendLine("        }");
            sourceCode.AppendLine("    }");
            sourceCode.AppendLine("}");

            context.AddSource($"{entityName}QueryExecutor.g.cs", SourceText.From(sourceCode.ToString(), Encoding.UTF8));
        }

        private List<IPropertySymbol> GetQueryableProperties(INamedTypeSymbol entityClass)
        {
            return entityClass.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                           !p.IsStatic &&
                           p.CanBeReferencedByName &&
                           p.Name != "Id" &&
                           !IsNavigationProperty(p))
                .ToList();
        }

        private bool IsNavigationProperty(IPropertySymbol property)
        {
            var type = property.Type;

            // 检查是否是集合类型（导航集合）
            if (type is INamedTypeSymbol namedType)
            {
                if (namedType.IsGenericType)
                {
                    var genericTypeName = namedType.ConstructedFrom.ToDisplayString();
                    if (genericTypeName.StartsWith("System.Collections") ||
                        genericTypeName.StartsWith("System.Collections.Generic"))
                    {
                        return true;
                    }
                }

                // 检查是否是复杂类型（可能是导航属性）
                if (namedType.TypeKind == TypeKind.Class &&
                    !namedType.IsValueType &&
                    namedType.SpecialType == SpecialType.None &&
                    !IsPrimitiveType(namedType))
                {
                    return true;
                }
            }

            return false;
        }

        private bool IsPrimitiveType(INamedTypeSymbol type)
        {
            var primitiveTypes = new[]
            {
                SpecialType.System_Boolean,
                SpecialType.System_Char,
                SpecialType.System_SByte,
                SpecialType.System_Byte,
                SpecialType.System_Int16,
                SpecialType.System_UInt16,
                SpecialType.System_Int32,
                SpecialType.System_UInt32,
                SpecialType.System_Int64,
                SpecialType.System_UInt64,
                SpecialType.System_Decimal,
                SpecialType.System_Single,
                SpecialType.System_Double,
                SpecialType.System_String,
                SpecialType.System_DateTime
            };

            return primitiveTypes.Contains(type.SpecialType) || type.Name == "Guid";
        }

        private bool IsStringType(ITypeSymbol type)
        {
            return type.SpecialType == SpecialType.System_String;
        }

        private bool IsNumericOrDateType(ITypeSymbol type)
        {
            var numericTypes = new[]
            {
                SpecialType.System_Int16,
                SpecialType.System_Int32,
                SpecialType.System_Int64,
                SpecialType.System_UInt16,
                SpecialType.System_UInt32,
                SpecialType.System_UInt64,
                SpecialType.System_Decimal,
                SpecialType.System_Single,
                SpecialType.System_Double,
                SpecialType.System_Byte,
                SpecialType.System_SByte,
                SpecialType.System_DateTime
            };

            return numericTypes.Contains(type.SpecialType);
        }
    }
}
