using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.CanonicalHashGenerator;

internal sealed class CanonicalHashProjectionWriter
{
    /// <summary>
    /// Generates projection methods for all profiles.
    /// </summary>
    public string Write(IReadOnlyList<ProfileModel> profiles)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        foreach (var profile in profiles)
        {
            WriteProjectionClass(sb, profile);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Metadata.CanonicalHashing.Generated;");
        sb.AppendLine();
    }

    private void WriteProjectionClass(StringBuilder sb, ProfileModel profile)
    {
        var className = $"{profile.Stem}CanonicalHashProjection";
        var targetTypeName = profile.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"internal static class {className}");
        sb.AppendLine("{");

        // ToContractPayload
        WriteProjectionMethod(sb, profile, "Contract", profile.ContractFields);
        sb.AppendLine();

        // ToDefinitionPayload
        WriteProjectionMethod(sb, profile, "Definition", profile.DefinitionFields);

        sb.AppendLine("}");
    }

    private void WriteProjectionMethod(StringBuilder sb, ProfileModel profile, string purpose,
        IReadOnlyList<ProfileFieldModel> fields)
    {
        var payloadName = $"{profile.Stem}{purpose}HashPayload";
        var targetTypeName = profile.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"    public static {payloadName} To{purpose}Payload({targetTypeName} source)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {payloadName}");
        sb.AppendLine("        {");

        foreach (var field in fields)
        {
            var expr = GetProjectionExpression(field, "source", purpose);
            sb.AppendLine($"            {field.PropertyName} = {expr},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static string GetProjectionExpression(ProfileFieldModel field, string sourceVar, string purpose)
    {
        var access = $"{sourceVar}.{field.PropertyName}";

        // Dictionary → ordered KV list
        if (field.IsDictionary)
        {
            return GetDictionaryProjection(field, access);
        }

        // Collection with element profile or union element reference
        if (field.IsCollection && (field.ElementProfile is not null || field.ElementProfileReference?.UnionProfile is not null))
        {
            return GetCollectionWithElementProjection(field, access, purpose);
        }

        // Collection without element profile (primitives)
        if (field.IsCollection)
        {
            return GetSimpleCollectionProjection(field, access);
        }

        // Non-collection complex type with ValueProfile or union value reference
        if (field.ValueProfile is not null || field.ValueProfileReference?.UnionProfile is not null)
        {
            // For union profile references, pass value through directly (no projection)
            // since union profiles don't have their own payload records.
            if (field.ValueProfileReference?.UnionProfile is not null)
            {
                return access;
            }

            var childProjectionClass = $"{field.ValueProfile!.Stem}CanonicalHashProjection";
            if (field.IsNullable)
            {
                // Nullable value types (Nullable<T>) need .HasValue / .Value pattern
                if (IsNullableValueType(field.PropertyType))
                    return $"{access}.HasValue ? {childProjectionClass}.To{purpose}Payload({access}.Value) : null";
                // Nullable reference types use `is not null` pattern
                return $"{access} is not null ? {childProjectionClass}.To{purpose}Payload({access}) : null";
            }
            return $"{childProjectionClass}.To{purpose}Payload({access})";
        }

        // Simple type — direct assignment
        return access;
    }

    private static string GetDictionaryProjection(ProfileFieldModel field, string access)
    {
        // Dictionaries always use OrderedKeyValue (sort by key) regardless of the
        // CollectionOrderMode on the profile — this is the only deterministic ordering
        // for dictionary types. CCHASH012 enforces that only OrderedKeyValue is used.
        var valueType = GetDictionaryValueType(field.PropertyType);
        var nullableCheck = field.IsNullable ? $"{access}?" : access;

        if (valueType is not null)
        {
            return $"{nullableCheck}.OrderBy(kv => kv.Key, StringComparer.Ordinal).Select(kv => new CanonicalStringKeyValuePayload<{valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> {{ Key = kv.Key, Value = kv.Value }}).ToArray()";
        }

        return $"{nullableCheck}.OrderBy(kv => kv.Key, StringComparer.Ordinal).Select(kv => new CanonicalStringKeyValuePayload {{ Key = kv.Key, Value = kv.Value }}).ToArray()";
    }

    private static string GetCollectionWithElementProjection(ProfileFieldModel field, string access, string purpose)
    {
        // For union element references, pass items through directly (no projection)
        // since union profiles don't have their own payload records.
        string? selectExpression = null;
        if (field.ElementProfileReference?.UnionProfile is not null)
        {
            // No projection needed for union elements — items pass through as-is
        }
        else
        {
            var childProjectionClass = $"{field.ElementProfile!.Stem}CanonicalHashProjection";
            selectExpression = $"Select({childProjectionClass}.To{purpose}Payload)";
        }

        var orderingClause = GetOrderingClause(field);
        var filterWhere = GetFilterWhereClause(field);

        // Build chain: source -> filter -> order -> select (if any)
        var chain = new System.Text.StringBuilder();
        if (field.IsNullable)
            chain.Append($"{access}?");
        else
            chain.Append(access);

        if (filterWhere.Length > 0)
            chain.Append('.').Append(filterWhere);

        if (orderingClause.Length > 0)
            chain.Append('.').Append(orderingClause);

        if (selectExpression is not null)
            chain.Append('.').Append(selectExpression);

        chain.Append(".ToArray()");

        return chain.ToString();
    }

    private static string GetSimpleCollectionProjection(ProfileFieldModel field, string access)
    {
        var orderingClause = GetOrderingClause(field);
        var filterWhere = GetFilterWhereClause(field);

        // Build chain: source -> filter -> order
        var chain = new System.Text.StringBuilder();
        if (field.IsNullable)
            chain.Append($"{access}?");
        else
            chain.Append(access);

        if (filterWhere.Length > 0)
            chain.Append('.').Append(filterWhere);

        if (orderingClause.Length > 0)
            chain.Append('.').Append(orderingClause);

        chain.Append(".ToArray()");

        return chain.ToString();
    }

    /// <summary>
    /// Returns a .Where(filter.Include) clause if the field has a filter, or empty string otherwise.
    /// </summary>
    private static string GetFilterWhereClause(ProfileFieldModel field)
    {
        if (field.Filter is not null)
        {
            return $"Where({field.Filter.FullyQualifiedTypeName}.Include)";
        }
        return "";
    }

    private static string GetOrderingClause(ProfileFieldModel field)
    {
        return field.CollectionOrderMode switch
        {
            "SourceOrder" => "",
            "OrdinalByValue" => IsElementStringType(field) ? "OrderBy(x => x, StringComparer.Ordinal)" : "OrderBy(x => x)",
            "OrdinalByProperty" when field.OrderByProperty is not null =>
                BuildMultiPropertyOrdering(field.OrderByProperty, GetElementType(field)),
            "OrderedKeyValue" => "OrderBy(kv => kv.Key, StringComparer.Ordinal)",  // For dictionaries, handled separately
            _ => "",
        };
    }

    /// <summary>
    /// Gets the element type for a collection field.
    /// For fields with ElementProfile, returns the profile's target type.
    /// For simple collections, returns the collection's element type from the property.
    /// </summary>
    private static INamedTypeSymbol? GetElementType(ProfileFieldModel field)
    {
        if (field.ElementProfile is not null)
            return field.ElementProfile.TargetType;

        // For simple collections, extract the element type from IEnumerable<T>
        if (field.PropertyType is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType ==
                    SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length == 1)
                {
                    return iface.TypeArguments[0] as INamedTypeSymbol;
                }
            }
        }
        return null;
    }

    private static string BuildMultiPropertyOrdering(string orderByProperty, INamedTypeSymbol? elementType)
    {
        var props = orderByProperty.Split(',');
        if (props.Length == 0)
            return "";

        var sb = new StringBuilder();

        var firstProp = props[0].Trim();
        var firstLambda = BuildPropertyLambda(firstProp, elementType);
        var firstKeyIsString = IsPropertyTypeString(elementType, firstProp);
        if (firstKeyIsString)
            sb.Append($"OrderBy(x => {firstLambda}, StringComparer.Ordinal)");
        else
            sb.Append($"OrderBy(x => {firstLambda})");

        for (int i = 1; i < props.Length; i++)
        {
            var prop = props[i].Trim();
            var lambda = BuildPropertyLambda(prop, elementType);
            if (IsPropertyTypeString(elementType, prop))
                sb.Append($".ThenBy(x => {lambda}, StringComparer.Ordinal)");
            else
                sb.Append($".ThenBy(x => {lambda})");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Builds a lambda expression body for a property path, handling Nullable&lt;T&gt; intermediate segments.
    /// For simple properties: "Condition" → "x.Condition"
    /// For multi-segment through nullable value type: "Capability.Id" → "x.Capability != null ? x.Capability.Value.Id : (string?)null"
    /// For multi-segment through nullable reference: "Ref.Name" → "x.Ref!.Name"
    /// </summary>
    private static string BuildPropertyLambda(string propertyPath, INamedTypeSymbol? elementType)
    {
        if (!propertyPath.Contains('.')) return $"x.{propertyPath}";

        var segments = propertyPath.Split('.');
        var currentType = (ITypeSymbol?)elementType;
        var pathParts = new List<string>();
        bool needsConditional = false;
        string? nullableSegment = null;

        for (int i = 0; i < segments.Length; i++)
        {
            var segment = segments[i].Trim();
            if (currentType is null) break;

            // Unwrap Nullable<T> from current type for member lookup
            if (currentType is INamedTypeSymbol unwrapNullable
                && unwrapNullable.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && unwrapNullable.TypeArguments.Length == 1)
            {
                currentType = unwrapNullable.TypeArguments[0];
            }

            var member = currentType.GetMembers(segment).FirstOrDefault();
            ITypeSymbol? memberType = null;
            if (member is IPropertySymbol prop)
            {
                pathParts.Add(segment);
                memberType = prop.Type;
            }
            else if (member is IFieldSymbol fieldSym)
            {
                pathParts.Add(segment);
                memberType = fieldSym.Type;
            }
            else
            {
                pathParts.Add(segment);
                break;
            }

            // Check if the member's type is Nullable<T> — this is the segment that introduces nullability
            if (memberType is INamedTypeSymbol memberNamed
                && memberNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && memberNamed.TypeArguments.Length == 1)
            {
                needsConditional = true;
                if (nullableSegment is null)
                {
                    nullableSegment = segment;
                }
            }

            currentType = memberType;
        }

        if (!needsConditional)
        {
            var result = new StringBuilder("x.");
            for (int i = 0; i < pathParts.Count; i++)
            {
                result.Append(pathParts[i]);
                if (i < pathParts.Count - 1) result.Append("!");
            }
            return result.ToString();
        }

        var finalType = currentType;
        // Unwrap Nullable<T> from final type
        if (finalType is INamedTypeSymbol finalNullable
            && finalNullable.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && finalNullable.TypeArguments.Length == 1)
        {
            finalType = finalNullable.TypeArguments[0];
        }
        var isStringFinal = finalType?.SpecialType == SpecialType.System_String;
        var isIntFinal = finalType?.SpecialType == SpecialType.System_Int32 || finalType?.SpecialType == SpecialType.System_Int64;

        var valuePath = new StringBuilder($"x.{nullableSegment}.Value");
        int nullableIndex = -1;
        for (int i = 0; i < pathParts.Count; i++)
        {
            if (pathParts[i] == nullableSegment)
            {
                nullableIndex = i;
                break;
            }
        }
        for (int i = nullableIndex + 1; i < pathParts.Count; i++)
        {
            valuePath.Append($".{pathParts[i]}");
        }

        var nullablePath = $"x.{nullableSegment}";

        if (isStringFinal)
            return $"{nullablePath} != null ? {valuePath} : (string?)null";
        if (isIntFinal)
            return $"{nullablePath} != null ? {valuePath} : 0";
        return $"{nullablePath} != null ? {valuePath} : null";
    }

    /// <summary>
    /// Resolves the first segment of a dotted property path on the element type
    /// and checks if it is string.
    /// For simple paths (no dots), checks the direct property.
    /// For dotted paths like "Capability.Id", checks only the LAST segment's type.
    /// </summary>
    private static bool IsPropertyTypeString(INamedTypeSymbol? elementType, string propertyPath)
    {
        if (elementType is null)
            return false;

        var segments = propertyPath.Split('.');
        var currentType = (ITypeSymbol?)elementType;

        foreach (var segment in segments)
        {
            var trimmedSegment = segment.Trim();
            if (currentType is null)
                return false;

            // Unwrap Nullable<T> if needed
            if (currentType is INamedTypeSymbol nullableNamed
                && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && nullableNamed.TypeArguments.Length == 1)
            {
                currentType = nullableNamed.TypeArguments[0];
            }

            var member = currentType.GetMembers(trimmedSegment).FirstOrDefault();
            if (member is IPropertySymbol prop)
                currentType = prop.Type;
            else if (member is IFieldSymbol fieldSym)
                currentType = fieldSym.Type;
            else
                return false;
        }

        // Check if the final type is string
        return currentType?.SpecialType == SpecialType.System_String;
    }

    private static ITypeSymbol? GetDictionaryValueType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                var originalDef = iface.OriginalDefinition;
                if (IsDictionaryInterface(originalDef)
                    && iface.TypeArguments.Length == 2)
                {
                    return iface.TypeArguments[1];
                }
            }
        }
        return null;
    }

    private static bool IsNullableValueType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType
            && namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T)
            return true;
        return false;
    }

    private static bool IsDictionaryInterface(INamedTypeSymbol typeDef)
    {
        var name = typeDef.Name;
        var ns = typeDef.ContainingNamespace?.ToDisplayString();
        if (name == "IDictionary" && ns == "System.Collections.Generic") return true;
        if (name == "IReadOnlyDictionary" && ns == "System.Collections.Generic") return true;
        return false;
    }

    private static bool IsElementStringType(ProfileFieldModel field)
    {
        var elementType = GetElementTypeSymbol(field);
        return elementType?.SpecialType == SpecialType.System_String;
    }

    private static INamedTypeSymbol? GetElementTypeSymbol(ProfileFieldModel field)
    {
        if (field.ElementProfile is not null)
            return field.ElementProfile.TargetType;

        if (field.PropertyType is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length == 1)
                {
                    return iface.TypeArguments[0] as INamedTypeSymbol;
                }
            }
        }
        return null;
    }
}
