using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.CanonicalHashGenerator;

internal sealed class CanonicalHashPayloadWriter
{
    /// <summary>
    /// Generates all payload records (dual per profile + sub-structures).
    /// </summary>
    public string Write(IReadOnlyList<ProfileModel> profiles)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        foreach (var profile in profiles)
        {
            WritePayloadsForProfile(sb, profile);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Metadata.CanonicalHashing.Generated;");
        sb.AppendLine();
    }

    private void WritePayloadsForProfile(StringBuilder sb, ProfileModel profile)
    {
        WritePayload(sb, profile, "Contract",
            profile.ContractFields,
            profile.ContractShapeVersion);

        sb.AppendLine();

        WritePayload(sb, profile, "Definition",
            profile.DefinitionFields,
            profile.DefinitionShapeVersion);
    }

    private void WritePayload(StringBuilder sb, ProfileModel profile, string purpose,
        IReadOnlyList<ProfileFieldModel> fields, string shapeVersion)
    {
        var payloadName = $"{profile.Stem}{purpose}HashPayload";

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Canonical {purpose.ToLowerInvariant()}-hash payload for {profile.TargetTypeName}.");
        sb.AppendLine($"/// Shape version: {shapeVersion}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"internal sealed record {payloadName}");
        sb.AppendLine("{");

        int propertyOrder = 0;
        foreach (var field in fields)
        {
            var propertyType = GetPayloadPropertyType(field, purpose);
            var nullableSuffix = "";
            // For reference types, append ? if the original was nullable
            if (field.IsNullable && !IsValueType(field.PropertyType) && !propertyType.EndsWith("?"))
                nullableSuffix = "?";

            sb.AppendLine($"    [JsonPropertyOrder({propertyOrder})]");
            sb.AppendLine($"    public required {propertyType}{nullableSuffix} {field.PropertyName} {{ get; init; }}");
            propertyOrder++;
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Gets the type name to use in the payload for a field.
    /// </summary>
    private static string GetPayloadPropertyType(ProfileFieldModel field, string purpose)
    {
        // Dictionary → ordered KV list
        if (field.IsDictionary)
        {
            // Get the value type from the dictionary
            var valueType = GetDictionaryValueType(field.PropertyType);
            if (valueType is not null && !IsSimpleType(valueType))
            {
                var fqn = valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"IReadOnlyList<CanonicalStringKeyValuePayload<{fqn}>>";
            }
            else if (valueType is not null)
            {
                var fqn = valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"IReadOnlyList<CanonicalStringKeyValuePayload<{fqn}>>";
            }
            return "IReadOnlyList<CanonicalStringKeyValuePayload>";
        }

        // Collection with element profile → IReadOnlyList<ChildPayload>
        if (field.IsCollection && field.ElementProfile is not null)
        {
            var childProfile = field.ElementProfile;
            var childPayloadName = $"{childProfile.Stem}{purpose}HashPayload";
            return $"IReadOnlyList<{childPayloadName}>";
        }

        // Collection without element profile → IReadOnlyList<ElementType>
        if (field.IsCollection)
        {
            var elementType = GetCollectionElementType(field.PropertyType);
            if (elementType is not null)
            {
                var fqn = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                return $"IReadOnlyList<{fqn}>";
            }
            return $"IReadOnlyList<object>";
        }

        // Non-collection complex type with ValueProfile → child payload type
        if (field.ValueProfile is not null)
        {
            var childPayloadName = $"{field.ValueProfile.Stem}{purpose}HashPayload";
            return childPayloadName;
        }

        // Simple type — use original type name
        return field.PropertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    private static ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arrayType)
            return arrayType.ElementType;

        if (type is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType ==
                    SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length == 1)
                {
                    return iface.TypeArguments[0];
                }
            }
        }

        return null;
    }

    private static ITypeSymbol? GetDictionaryValueType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                var originalDef = iface.OriginalDefinition;
                if (IsDictionaryInterface(originalDef)
                    && iface.TypeArguments.Length == 2)
                {
                    return iface.TypeArguments[1]; // TValue
                }
            }
        }
        return null;
    }

    private static bool IsDictionaryInterface(INamedTypeSymbol typeDef)
    {
        var name = typeDef.Name;
        var ns = typeDef.ContainingNamespace?.ToDisplayString();
        if (name == "IDictionary" && ns == "System.Collections.Generic") return true;
        if (name == "IReadOnlyDictionary" && ns == "System.Collections.Generic") return true;
        return false;
    }

    private static bool IsSimpleType(ITypeSymbol type)
    {
        var underlying = type;
        if (type is INamedTypeSymbol n && n.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && n.TypeArguments.Length == 1)
            underlying = n.TypeArguments[0];

        if (underlying.SpecialType == SpecialType.System_String) return true;
        if (underlying.SpecialType == SpecialType.System_Int32) return true;
        if (underlying.SpecialType == SpecialType.System_Boolean) return true;
        if (underlying.SpecialType == SpecialType.System_Int64) return true;
        if (underlying.SpecialType == SpecialType.System_Single) return true;
        if (underlying.SpecialType == SpecialType.System_Double) return true;
        if (underlying.SpecialType == SpecialType.System_DateTime) return true;
        if (underlying.TypeKind == TypeKind.Enum) return true;

        return false;
    }

    private static bool IsValueType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType &&
            namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T)
            return true;

        return type.IsValueType;
    }
}
