using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.CanonicalHashGenerator;

/// <summary>
/// Generates canonical JSON writer methods for each profile.
/// Each writer method writes the complete envelope (metadata + payload) to Utf8JsonWriter.
///
/// Generated output per profile:
///   internal static class {Stem}CanonicalHashWriter
///   {
///       public static void WriteContractEnvelope(Utf8JsonWriter w, {TargetType} d, string scope, string algVer, string contrVer)
///       public static void WriteDefinitionEnvelope(Utf8JsonWriter w, {TargetType} d, string scope, string algVer, string contrVer)
///   }
///
/// The writer methods write deterministic PascalCase JSON with fixed property order.
/// No JsonSerializer, no JsonTypeInfo, no reflection — pure Utf8JsonWriter calls.
/// </summary>
internal sealed class CanonicalHashWriterWriter
{
    public string Write(IReadOnlyList<ProfileModel> profiles)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        foreach (var profile in profiles)
        {
            WriteWriterClass(sb, profile);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Metadata.CanonicalHashing.Generated;");
        sb.AppendLine();
    }

    private static void WriteWriterClass(StringBuilder sb, ProfileModel profile)
    {
        var className = $"{profile.Stem}CanonicalHashWriter";
        var targetTypeName = profile.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"internal static class {className}");
        sb.AppendLine("{");

        // WriteContractEnvelope + WriteContractPayload
        WriteEnvelopeMethod(sb, profile, "Contract", profile.ContractFields, targetTypeName);
        sb.AppendLine();
        WritePayloadMethod(sb, profile, "Contract", profile.ContractFields, targetTypeName);
        sb.AppendLine();

        // WriteDefinitionEnvelope + WriteDefinitionPayload
        WriteEnvelopeMethod(sb, profile, "Definition", profile.DefinitionFields, targetTypeName);
        sb.AppendLine();
        WritePayloadMethod(sb, profile, "Definition", profile.DefinitionFields, targetTypeName);

        sb.AppendLine("}");
    }

    private static void WriteEnvelopeMethod(StringBuilder sb, ProfileModel profile, string purpose,
        IReadOnlyList<ProfileFieldModel> fields, string targetTypeName)
    {
        var descriptorKindName = profile.DescriptorKind;
        var shapeVersion = purpose == "Contract" ? profile.ContractShapeVersion : profile.DefinitionShapeVersion;
        var purposeName = purpose == "Contract" ? "Contract" : "Definition";
        var artifactKind = profile.ArtifactKind;
        var stem = profile.Stem;

        // For top-level descriptors, use CanonicalHashArtifactNames.Descriptor
        // For sub-structures, use CanonicalHashArtifactNames.Descriptor too (they're still descriptor sub-structures)
        var artifactKindExpr = artifactKind == "Descriptor"
            ? "CanonicalHashArtifactNames.Descriptor"
            : $"\"{artifactKind}\"";

        sb.AppendLine($"    public static void Write{purpose}Envelope(Utf8JsonWriter w, {targetTypeName} d, string scopeString, string algorithmVersion, string contractVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        w.WriteStartObject();");

        // Write envelope metadata in spec §6.2 order: ArtifactKind, DescriptorKind, Scope, Purpose, ContractVersion, CanonicalShapeVersion, AlgorithmVersion
        sb.AppendLine($"        w.WriteString(\"ArtifactKind\", {artifactKindExpr});");

        // DescriptorKind: for Unknown sub-structures, write null instead of "Unknown" literal
        if (descriptorKindName != "Unknown")
        {
            sb.AppendLine($"        w.WriteString(\"DescriptorKind\", DescriptorKindNames.{descriptorKindName});");
        }
        else
        {
            sb.AppendLine("        w.WriteNull(\"DescriptorKind\");");
        }

        sb.AppendLine("        w.WriteString(\"Scope\", scopeString);");
        sb.AppendLine($"        w.WriteString(\"Purpose\", \"{purposeName}\");");
        sb.AppendLine("        w.WriteString(\"ContractVersion\", contractVersion);");
        sb.AppendLine($"        w.WriteString(\"CanonicalShapeVersion\", \"{shapeVersion}\");");
        sb.AppendLine("        w.WriteString(\"AlgorithmVersion\", algorithmVersion);");

        // Write payload section — delegate to payload method for shared field-writing logic
        sb.AppendLine("        w.WritePropertyName(\"Payload\");");
        sb.AppendLine($"        {stem}CanonicalHashWriter.Write{purpose}Payload(w, d);");

        sb.AppendLine("        w.WriteEndObject();"); // Envelope
        sb.AppendLine("    }");
    }

    private static void WritePayloadMethod(StringBuilder sb, ProfileModel profile, string purpose,
        IReadOnlyList<ProfileFieldModel> fields, string targetTypeName)
    {
        sb.AppendLine($"    public static void Write{purpose}Payload(Utf8JsonWriter w, {targetTypeName} d)");
        sb.AppendLine("    {");
        sb.AppendLine("        w.WriteStartObject();");

        // Write payload fields in profile order (no envelope metadata)
        foreach (var field in fields)
        {
            WriteField(sb, field, "d", purpose);
        }

        sb.AppendLine("        w.WriteEndObject();");
        sb.AppendLine("    }");
    }

    private static void WriteField(StringBuilder sb, ProfileFieldModel field, string sourceVar, string purpose)
    {
        var propName = field.PropertyName;
        var access = $"{sourceVar}.{propName}";

        // CustomWriter takes precedence — the SG delegates to a hand-written canonical writer
        if (field.CustomWriterTypeName is not null)
        {
            WriteCustomWriterField(sb, field, propName, access, purpose);
            return;
        }

        // Dictionary → CanonicalStringKeyValuePayload
        if (field.IsDictionary)
        {
            WriteDictionaryField(sb, field, propName, access);
            return;
        }

        // Collection with element profile
        if (field.IsCollection && field.ElementProfile is not null)
        {
            WriteCollectionWithProfileField(sb, field, propName, access, purpose);
            return;
        }

        // Simple collection (primitives)
        if (field.IsCollection)
        {
            WriteSimpleCollectionField(sb, field, propName, access);
            return;
        }

        // Non-collection complex type with ValueProfile (sub-structure)
        if (field.ValueProfile is not null)
        {
            WriteSubStructureField(sb, field, propName, access, purpose);
            return;
        }

        // Simple scalar type
        WriteScalarField(sb, field, propName, access);
    }

    private static void WriteScalarField(StringBuilder sb, ProfileFieldModel field, string propName, string access)
    {
        var type = field.PropertyType;
        var specialType = type.SpecialType;
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (field.IsNullable)
        {
            // Nullable value type or nullable reference type
            if (IsNullableValueType(type))
            {
                // Nullable<T> — need .HasValue check
                var underlyingType = GetUnderlyingType(type);
                sb.AppendLine($"        if ({access}.HasValue)");
                sb.AppendLine("        {");
                WriteScalarValue(sb, underlyingType, propName, $"{access}.Value");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
            else
            {
                // Nullable reference type — null check with pattern
                sb.AppendLine($"        if ({access} is not null)");
                sb.AppendLine("        {");
                WriteScalarValue(sb, type, propName, access);
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
            return;
        }

        // Non-nullable scalar
        WriteScalarValue(sb, type, propName, access);
    }

    private static void WriteScalarValue(StringBuilder sb, ITypeSymbol type, string propName, string access)
    {
        var specialType = type.SpecialType;

        switch (specialType)
        {
            case SpecialType.System_String:
                sb.AppendLine($"        w.WriteString(\"{propName}\", {access});");
                break;
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
                sb.AppendLine($"        w.WriteNumber(\"{propName}\", {access});");
                break;
            case SpecialType.System_Boolean:
                sb.AppendLine($"        w.WriteBoolean(\"{propName}\", {access});");
                break;
            case SpecialType.System_DateTime:
                sb.AppendLine($"        w.WriteString(\"{propName}\", {access}.ToString(\"O\"));");
                break;
            default:
                // Enum — use compile-time switch expression for determinism
                if (type.TypeKind == TypeKind.Enum)
                {
                    WriteEnumSwitchExpression(sb, type, propName, access, "        ");
                }
                else
                {
                    // Fallback: ToString() for any other type
                    sb.AppendLine($"        w.WriteString(\"{propName}\", {access}.ToString());");
                }
                break;
        }
    }

    private static void WriteCustomWriterField(StringBuilder sb, ProfileFieldModel field,
        string propName, string access, string purpose)
    {
        // CustomWriter is a static class with WriteContractPayload/WriteDefinitionPayload methods
        // that write only the payload fields (no envelope metadata).
        var writerClass = field.CustomWriterTypeName!;
        var payloadMethod = purpose == "Contract" ? "WriteContractPayload" : "WriteDefinitionPayload";

        if (field.IsNullable)
        {
            if (IsNullableValueType(field.PropertyType))
            {
                sb.AppendLine($"        if ({access}.HasValue)");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
                sb.AppendLine($"            {writerClass}.{payloadMethod}(w, {access}.Value);");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        if ({access} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
                sb.AppendLine($"            {writerClass}.{payloadMethod}(w, {access});");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
        }
        else
        {
            sb.AppendLine($"        w.WritePropertyName(\"{propName}\");");
            sb.AppendLine($"            {writerClass}.{payloadMethod}(w, {access});");
        }
    }

    private static void WriteDictionaryField(StringBuilder sb, ProfileFieldModel field, string propName, string access)
    {
        var valueType = GetDictionaryValueTypeSymbol(field.PropertyType);
        var isNullable = field.IsNullable;

        if (isNullable)
        {
            sb.AppendLine($"        if ({access} is not null)");
            sb.AppendLine("        {");
            WriteDictionaryContent(sb, field, propName, access, valueType);
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            w.WriteNull(\"{propName}\");");
            sb.AppendLine("        }");
        }
        else
        {
            WriteDictionaryContent(sb, field, propName, access, valueType);
        }
    }

    private static void WriteDictionaryContent(StringBuilder sb, ProfileFieldModel field, string propName,
        string access, ITypeSymbol? valueType)
    {
        // Dictionary is always written as ordered array of { Key, Value } objects
        sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
        sb.AppendLine("            w.WriteStartArray();");

        // Sort by key for determinism (CollectionOrderMode for dictionaries is always OrderedKeyValue)
        var sortedAccess = $"{access}.OrderBy(kv => kv.Key, StringComparer.Ordinal)";

        if (valueType is not null && field.ValueProfile is not null)
        {
            // Dictionary with sub-structure values — use payload methods (no envelope metadata)
            var writerClass = $"{field.ValueProfile.Stem}CanonicalHashWriter";
            sb.AppendLine($"            foreach (var kv in {sortedAccess})");
            sb.AppendLine("            {");
            sb.AppendLine("                w.WriteStartObject();");
            sb.AppendLine("                w.WriteString(\"Key\", kv.Key);");
            sb.AppendLine("                w.WritePropertyName(\"Value\");");
            sb.AppendLine($"                {writerClass}.WriteContractPayload(w, kv.Value);");
            sb.AppendLine("                w.WriteEndObject();");
            sb.AppendLine("            }");
        }
        else if (valueType is not null)
        {
            // Dictionary with scalar values — use CanonicalStringKeyValuePayload pattern in JSON
            sb.AppendLine($"            foreach (var kv in {sortedAccess})");
            sb.AppendLine("            {");
            sb.AppendLine("                w.WriteStartObject();");
            sb.AppendLine("                w.WriteString(\"Key\", kv.Key);");
            WriteScalarValueForDictionaryValue(sb, valueType, "Value", "kv.Value");
            sb.AppendLine("                w.WriteEndObject();");
            sb.AppendLine("            }");
        }
        else
        {
            // Dictionary<string, string> — simplest case
            sb.AppendLine($"            foreach (var kv in {sortedAccess})");
            sb.AppendLine("            {");
            sb.AppendLine("                w.WriteStartObject();");
            sb.AppendLine("                w.WriteString(\"Key\", kv.Key);");
            sb.AppendLine("                w.WriteString(\"Value\", kv.Value);");
            sb.AppendLine("                w.WriteEndObject();");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            w.WriteEndArray();");
    }

    private static void WriteScalarValueForDictionaryValue(StringBuilder sb, ITypeSymbol valueType,
        string jsonPropName, string access)
    {
        switch (valueType.SpecialType)
        {
            case SpecialType.System_String:
                sb.AppendLine($"                w.WriteString(\"{jsonPropName}\", {access});");
                break;
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
                sb.AppendLine($"                w.WriteNumber(\"{jsonPropName}\", {access});");
                break;
            case SpecialType.System_Boolean:
                sb.AppendLine($"                w.WriteBoolean(\"{jsonPropName}\", {access});");
                break;
            default:
                if (valueType.TypeKind == TypeKind.Enum)
                    WriteEnumSwitchExpression(sb, valueType, jsonPropName, access, "                ");
                else
                    sb.AppendLine($"                w.WriteString(\"{jsonPropName}\", {access}.ToString());");
                break;
        }
    }

    private static void WriteCollectionWithProfileField(StringBuilder sb, ProfileFieldModel field,
        string propName, string access, string purpose)
    {
        var elementWriter = $"{field.ElementProfile!.Stem}CanonicalHashWriter";
        var orderingClause = GetOrderingClause(field);

        if (field.IsNullable)
        {
            sb.AppendLine($"        if ({access} is not null)");
            sb.AppendLine("        {");
            WriteCollectionWithProfileContent(sb, field, propName, access, purpose, elementWriter, orderingClause);
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            w.WriteNull(\"{propName}\");");
            sb.AppendLine("        }");
        }
        else
        {
            WriteCollectionWithProfileContent(sb, field, propName, access, purpose, elementWriter, orderingClause);
        }
    }

    private static void WriteCollectionWithProfileContent(StringBuilder sb, ProfileFieldModel field,
        string propName, string access, string purpose, string elementWriter, string orderingClause)
    {
        var writerMethod = purpose == "Contract" ? "WriteContractPayload" : "WriteDefinitionPayload";
        var orderedAccess = orderingClause.Length > 0
            ? $"{access}.{orderingClause}"
            : access;

        sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
        sb.AppendLine("            w.WriteStartArray();");
        sb.AppendLine($"            foreach (var item in {orderedAccess})");
        sb.AppendLine("            {");
        sb.AppendLine($"                {elementWriter}.{writerMethod}(w, item);");
        sb.AppendLine("            }");
        sb.AppendLine("            w.WriteEndArray();");
    }

    private static void WriteSimpleCollectionField(StringBuilder sb, ProfileFieldModel field,
        string propName, string access)
    {
        var orderingClause = GetOrderingClause(field);

        if (field.IsNullable)
        {
            sb.AppendLine($"        if ({access} is not null)");
            sb.AppendLine("        {");
            WriteSimpleCollectionContent(sb, field, propName, access, orderingClause);
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            w.WriteNull(\"{propName}\");");
            sb.AppendLine("        }");
        }
        else
        {
            WriteSimpleCollectionContent(sb, field, propName, access, orderingClause);
        }
    }

    private static void WriteSimpleCollectionContent(StringBuilder sb, ProfileFieldModel field,
        string propName, string access, string orderingClause)
    {
        var orderedAccess = orderingClause.Length > 0
            ? $"{access}.{orderingClause}"
            : access;

        sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
        sb.AppendLine("            w.WriteStartArray();");

        // For simple collections, write each element directly
        sb.AppendLine($"            foreach (var item in {orderedAccess})");
        sb.AppendLine("            {");

        var elementType = GetElementTypeSymbol(field);
        WriteScalarValueInline(sb, elementType, "item");

        sb.AppendLine("            }");
        sb.AppendLine("            w.WriteEndArray();");
    }

    private static void WriteSubStructureField(StringBuilder sb, ProfileFieldModel field,
        string propName, string access, string purpose)
    {
        var writerClass = $"{field.ValueProfile!.Stem}CanonicalHashWriter";
        var payloadMethod = purpose == "Contract" ? "WriteContractPayload" : "WriteDefinitionPayload";

        if (field.IsNullable)
        {
            if (IsNullableValueType(field.PropertyType))
            {
                sb.AppendLine($"        if ({access}.HasValue)");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
                sb.AppendLine($"            {writerClass}.{payloadMethod}(w, {access}.Value);");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
            else
            {
                sb.AppendLine($"        if ({access} is not null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WritePropertyName(\"{propName}\");");
                sb.AppendLine($"            {writerClass}.{payloadMethod}(w, {access});");
                sb.AppendLine("        }");
                sb.AppendLine("        else");
                sb.AppendLine("        {");
                sb.AppendLine($"            w.WriteNull(\"{propName}\");");
                sb.AppendLine("        }");
            }
        }
        else
        {
            sb.AppendLine($"        w.WritePropertyName(\"{propName}\");");
            sb.AppendLine($"        {writerClass}.{payloadMethod}(w, {access});");
        }
    }

    private static void WriteScalarValueInline(StringBuilder sb, ITypeSymbol? elementType, string accessExpr)
    {
        if (elementType is null)
        {
            sb.AppendLine($"                w.WriteStringValue({accessExpr}.ToString());");
            return;
        }

        switch (elementType.SpecialType)
        {
            case SpecialType.System_String:
                sb.AppendLine($"                w.WriteStringValue({accessExpr});");
                break;
            case SpecialType.System_Int32:
            case SpecialType.System_Int64:
                sb.AppendLine($"                w.WriteNumberValue({accessExpr});");
                break;
            case SpecialType.System_Boolean:
                sb.AppendLine($"                w.WriteBooleanValue({accessExpr});");
                break;
            default:
                if (elementType.TypeKind == TypeKind.Enum)
                    WriteEnumSwitchExpression(sb, elementType, null, accessExpr, "                ");
                else
                    sb.AppendLine($"                w.WriteStringValue({accessExpr}.ToString());");
                break;
        }
    }

    /// <summary>
    /// Generates a compile-time switch expression for an enum that maps each member
    /// to its canonical name string. This replaces .ToString() which is brittle
    /// against enum member renames (ToString() follows runtime metadata).
    ///
    /// When propName is null, generates w.WriteStringValue(...) for inline/array context.
    /// When propName is non-null, generates w.WriteString(propName, ...) for property context.
    /// </summary>
    private static void WriteEnumSwitchExpression(StringBuilder sb, ITypeSymbol enumType,
        string? propName, string accessExpr, string indent)
    {
        var enumFqn = enumType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var enumName = enumType.Name;

        // Get enum member fields (exclude the compiler-generated "value__" field)
        var members = enumType.GetMembers()
            .Where(m => m is IFieldSymbol && m.Name != "value__")
            .Select(m => m.Name)
            .ToList();

        if (members.Count == 0)
        {
            // Degenerate enum — fall back to .ToString()
            if (propName is not null)
                sb.AppendLine($"{indent}w.WriteString(\"{propName}\", {accessExpr}.ToString());");
            else
                sb.AppendLine($"{indent}w.WriteStringValue({accessExpr}.ToString());");
            return;
        }

        if (propName is not null)
        {
            // w.WriteString("PropName", accessExpr switch { ... });
            sb.AppendLine($"{indent}w.WriteString(\"{propName}\", {accessExpr} switch");
            sb.AppendLine($"{indent}{{");
        }
        else
        {
            // w.WriteStringValue(accessExpr switch { ... });
            sb.AppendLine($"{indent}w.WriteStringValue({accessExpr} switch");
            sb.AppendLine($"{indent}{{");
        }

        foreach (var member in members)
        {
            sb.AppendLine($"{indent}    {enumFqn}.{member} => \"{member}\",");
        }

        // Catch-all for forward-compatibility when new enum members are added
        sb.AppendLine($"{indent}    _ => throw new InvalidOperationException($\"Unknown {enumName} value: {{{accessExpr}}}\")");

        if (propName is not null)
        {
            sb.AppendLine($"{indent}}});");
        }
        else
        {
            sb.AppendLine($"{indent}}});");
        }
    }

    // --- Helpers for ordering clause generation (same logic as ProjectionWriter) ---
    private static string GetOrderingClause(ProfileFieldModel field)
    {
        return field.CollectionOrderMode switch
        {
            "SourceOrder" => "",
            "OrdinalByValue" => IsElementStringType(field) ? "OrderBy(x => x, StringComparer.Ordinal)" : "OrderBy(x => x)",
            "OrdinalByProperty" when field.OrderByProperty is not null =>
                BuildMultiPropertyOrdering(field.OrderByProperty, field),
            "OrderedKeyValue" => "OrderBy(kv => kv.Key, StringComparer.Ordinal)",
            _ => "",
        };
    }

    private static string BuildMultiPropertyOrdering(string orderByProperty, ProfileFieldModel field)
    {
        var props = orderByProperty.Split(',');
        if (props.Length == 0) return "";

        var sb = new StringBuilder();
        var elementType = field.ElementProfile?.TargetType ?? GetElementTypeSymbol(field) as INamedTypeSymbol;

        var firstProp = props[0].Trim();
        var firstLambda = BuildPropertyLambda(firstProp, elementType);
        var firstKeyIsString = IsPropertyTypeString(elementType, firstProp);
        if (firstKeyIsString)
            sb.Append($"OrderBy(x => {firstLambda}, StringComparer.Ordinal)");
        else
            sb.Append($"OrderBy(x => {firstLambda})");

        for (int i = 1; i < props.Length; i++)
        {
            var prop = props[i].Trim();
            var lambda = BuildPropertyLambda(prop, elementType);
            if (IsPropertyTypeString(elementType, prop))
                sb.Append($".ThenBy(x => {lambda}, StringComparer.Ordinal)");
            else
                sb.Append($".ThenBy(x => {lambda})");
        }
        return sb.ToString();
    }

    /// <summary>
    /// Builds a lambda expression body for a property path, handling Nullable&lt;T&gt; intermediate segments.
    /// For simple properties: "Condition" → "x.Condition"
    /// For multi-segment through nullable value type: "Capability.Id" → "x.Capability != null ? x.Capability.Value.Id : (string?)null"
    /// For multi-segment through nullable reference: "Ref.Name" → "x.Ref!.Name"
    /// </summary>
    private static string BuildPropertyLambda(string propertyPath, INamedTypeSymbol? elementType)
    {
        if (!propertyPath.Contains('.')) return $"x.{propertyPath}";

        // Walk the property path to determine nullability of each segment
        var segments = propertyPath.Split('.');
        var currentType = (ITypeSymbol?)elementType;
        var pathParts = new List<string>();
        bool needsConditional = false;
        string? nullableSegment = null;

        for (int i = 0; i < segments.Length; i++)
        {
            var segment = segments[i].Trim();
            if (currentType is null) break;

            // Unwrap Nullable<T> from current type for member lookup
            if (currentType is INamedTypeSymbol unwrapNullable
                && unwrapNullable.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && unwrapNullable.TypeArguments.Length == 1)
            {
                currentType = unwrapNullable.TypeArguments[0];
            }

            var member = currentType.GetMembers(segment).FirstOrDefault();
            ITypeSymbol? memberType = null;
            if (member is IPropertySymbol prop)
            {
                pathParts.Add(segment);
                memberType = prop.Type;
            }
            else if (member is IFieldSymbol fieldSym)
            {
                pathParts.Add(segment);
                memberType = fieldSym.Type;
            }
            else
            {
                pathParts.Add(segment);
                break;
            }

            // Check if the member's type is Nullable<T> — this is the segment that introduces nullability
            if (memberType is INamedTypeSymbol memberNamed
                && memberNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && memberNamed.TypeArguments.Length == 1)
            {
                needsConditional = true;
                if (nullableSegment is null)
                {
                    nullableSegment = segment;
                }
            }

            currentType = memberType;
        }

        // If no Nullable<T> intermediate segment, use simple member access with ! for reference types
        if (!needsConditional)
        {
            var result = new StringBuilder("x.");
            for (int i = 0; i < pathParts.Count; i++)
            {
                result.Append(pathParts[i]);
                if (i < pathParts.Count - 1) result.Append("!");
            }
            return result.ToString();
        }

        // For Nullable<T> intermediate segments, generate a conditional expression
        // x.{nullableSegment} != null ? x.{nullableSegment}.Value.{remaining_path} : {fallback}
        var finalType = currentType;
        // Unwrap Nullable<T> from final type for fallback determination
        if (finalType is INamedTypeSymbol finalNullable
            && finalNullable.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && finalNullable.TypeArguments.Length == 1)
        {
            finalType = finalNullable.TypeArguments[0];
        }
        var isStringFinal = finalType?.SpecialType == SpecialType.System_String;
        var isIntFinal = finalType?.SpecialType == SpecialType.System_Int32 || finalType?.SpecialType == SpecialType.System_Int64;

        // Build the value path: x.{nullableSegment}.Value.{remaining}
        var valuePath = new StringBuilder($"x.{nullableSegment}.Value");
        // Find the index of nullableSegment in pathParts to know where to continue
        int nullableIndex = -1;
        for (int i = 0; i < pathParts.Count; i++)
        {
            if (pathParts[i] == nullableSegment)
            {
                nullableIndex = i;
                break;
            }
        }
        // Append remaining path after the nullable segment
        for (int i = nullableIndex + 1; i < pathParts.Count; i++)
        {
            valuePath.Append($".{pathParts[i]}");
        }

        var nullablePath = $"x.{nullableSegment}";

        if (isStringFinal)
            return $"{nullablePath} != null ? {valuePath} : (string?)null";
        if (isIntFinal)
            return $"{nullablePath} != null ? {valuePath} : 0";
        return $"{nullablePath} != null ? {valuePath} : null";
    }

    private static bool IsElementStringType(ProfileFieldModel field)
    {
        var elementType = GetElementTypeSymbol(field);
        return elementType?.SpecialType == SpecialType.System_String;
    }

    private static INamedTypeSymbol? GetElementTypeSymbol(ProfileFieldModel field)
    {
        if (field.ElementProfile is not null)
            return field.ElementProfile.TargetType;

        if (field.PropertyType is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length == 1)
                {
                    return iface.TypeArguments[0] as INamedTypeSymbol;
                }
            }
        }
        return null;
    }

    private static bool IsPropertyTypeString(INamedTypeSymbol? elementType, string propertyPath)
    {
        if (elementType is null) return false;

        var segments = propertyPath.Split('.');
        var currentType = (ITypeSymbol?)elementType;

        foreach (var segment in segments)
        {
            var trimmedSegment = segment.Trim();
            if (currentType is null) return false;

            if (currentType is INamedTypeSymbol nullableNamed
                && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
                && nullableNamed.TypeArguments.Length == 1)
            {
                currentType = nullableNamed.TypeArguments[0];
            }

            var member = currentType.GetMembers(trimmedSegment).FirstOrDefault();
            if (member is IPropertySymbol prop)
                currentType = prop.Type;
            else if (member is IFieldSymbol fieldSym)
                currentType = fieldSym.Type;
            else
                return false;
        }

        return currentType?.SpecialType == SpecialType.System_String;
    }

    private static bool IsNullableValueType(ITypeSymbol type)
    {
        return type is INamedTypeSymbol namedType
            && namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T;
    }

    private static ITypeSymbol GetUnderlyingType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType
            && namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && namedType.TypeArguments.Length == 1)
        {
            return namedType.TypeArguments[0];
        }
        return type;
    }

    private static ITypeSymbol? GetDictionaryValueTypeSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                var originalDef = iface.OriginalDefinition;
                if (IsDictionaryInterface(originalDef)
                    && iface.TypeArguments.Length == 2)
                {
                    return iface.TypeArguments[1];
                }
            }
        }
        return null;
    }

    private static bool IsDictionaryInterface(INamedTypeSymbol typeDef)
    {
        var name = typeDef.Name;
        var ns = typeDef.ContainingNamespace?.ToDisplayString();
        if (name == "IDictionary" && ns == "System.Collections.Generic") return true;
        if (name == "IReadOnlyDictionary" && ns == "System.Collections.Generic") return true;
        return false;
    }
}
