using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.CanonicalHashGenerator;

/// <summary>
/// Generates the switch-based dispatcher that:
/// 1. Pattern-matches on the descriptor type
/// 2. Constructs CanonicalHashMetadata
/// 3. Creates a closed-over-descriptor WriteCanonicalJson delegate
/// 4. Returns CanonicalHashProjectionResult via Create(metadata, writerDelegate)
///
/// The writerDelegate captures the matched descriptor variable so that
/// Action&lt;Utf8JsonWriter&gt; only needs the writer parameter.
/// </summary>
internal sealed class CanonicalHashDispatcherWriter
{
    public string Write(IReadOnlyList<ProfileModel> profiles)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        var descriptorProfiles = profiles
            .Where(p => p.IsTopLevelDescriptor)
            .ToList();

        if (descriptorProfiles.Count == 0)
        {
            WriteEmptyDispatcher(sb);
        }
        else
        {
            WriteToContractProjection(sb, descriptorProfiles);
            sb.AppendLine();
            WriteToDefinitionProjection(sb, descriptorProfiles);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Metadata.CanonicalHashing.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CanonicalHashProjectionDispatcher");
        sb.AppendLine("{");
    }

    private void WriteEmptyDispatcher(StringBuilder sb)
    {
        sb.AppendLine("    public static CanonicalHashProjectionResult ToContractProjection(");
        sb.AppendLine("        IDescriptor descriptor,");
        sb.AppendLine("        CanonicalHashScope scope,");
        sb.AppendLine("        string contractVersion,");
        sb.AppendLine("        string algorithmVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new InvalidOperationException(");
        sb.AppendLine("            \"No canonical hash profile registered for the given descriptor type\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static CanonicalHashProjectionResult ToDefinitionProjection(");
        sb.AppendLine("        IDescriptor descriptor,");
        sb.AppendLine("        CanonicalHashScope scope,");
        sb.AppendLine("        string contractVersion,");
        sb.AppendLine("        string algorithmVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        throw new InvalidOperationException(");
        sb.AppendLine("            \"No canonical hash profile registered for the given descriptor type\");");
        sb.AppendLine("    }");
    }

    private void WriteToContractProjection(StringBuilder sb, List<ProfileModel> descriptorProfiles)
    {
        sb.AppendLine("    public static CanonicalHashProjectionResult ToContractProjection(");
        sb.AppendLine("        IDescriptor descriptor,");
        sb.AppendLine("        CanonicalHashScope scope,");
        sb.AppendLine("        string contractVersion,");
        sb.AppendLine("        string algorithmVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        var scopeString = CanonicalHashScopeNames.ToCanonicalString(scope);");
        sb.AppendLine();
        sb.AppendLine("        return descriptor switch");
        sb.AppendLine("        {");

        foreach (var profile in descriptorProfiles)
        {
            var targetTypeFqn = profile.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var stem = profile.Stem;
            var descriptorKindName = profile.DescriptorKind;
            var writerClassName = $"{stem}CanonicalHashWriter";

            // The delegate captures 'd' (matched descriptor) + scopeString + algorithmVersion + contractVersion
            sb.AppendLine($"            {targetTypeFqn} d => CanonicalHashProjectionResult.Create(");
            sb.AppendLine($"                new CanonicalHashMetadata");
            sb.AppendLine("                {");
            sb.AppendLine($"                    ArtifactKind = CanonicalHashArtifactNames.Descriptor,");
            sb.AppendLine($"                    DescriptorKind = DescriptorKindNames.{descriptorKindName},");
            sb.AppendLine($"                    Scope = scopeString,");
            sb.AppendLine($"                    Purpose = CanonicalHashPurposeNames.Contract,");
            sb.AppendLine($"                    CanonicalShapeVersion = \"{profile.ContractShapeVersion}\",");
            sb.AppendLine("                    AlgorithmVersion = algorithmVersion,");
            sb.AppendLine("                    ContractVersion = contractVersion");
            sb.AppendLine("                },");
            sb.AppendLine($"                w => {writerClassName}.WriteContractEnvelope(w, d, scopeString, algorithmVersion, contractVersion)),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(");
        sb.AppendLine("                \"No canonical hash profile registered for the given descriptor type\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private void WriteToDefinitionProjection(StringBuilder sb, List<ProfileModel> descriptorProfiles)
    {
        sb.AppendLine("    public static CanonicalHashProjectionResult ToDefinitionProjection(");
        sb.AppendLine("        IDescriptor descriptor,");
        sb.AppendLine("        CanonicalHashScope scope,");
        sb.AppendLine("        string contractVersion,");
        sb.AppendLine("        string algorithmVersion)");
        sb.AppendLine("    {");
        sb.AppendLine("        var scopeString = CanonicalHashScopeNames.ToCanonicalString(scope);");
        sb.AppendLine();
        sb.AppendLine("        return descriptor switch");
        sb.AppendLine("        {");

        foreach (var profile in descriptorProfiles)
        {
            var targetTypeFqn = profile.TargetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var stem = profile.Stem;
            var descriptorKindName = profile.DescriptorKind;
            var writerClassName = $"{stem}CanonicalHashWriter";

            sb.AppendLine($"            {targetTypeFqn} d => CanonicalHashProjectionResult.Create(");
            sb.AppendLine($"                new CanonicalHashMetadata");
            sb.AppendLine("                {");
            sb.AppendLine($"                    ArtifactKind = CanonicalHashArtifactNames.Descriptor,");
            sb.AppendLine($"                    DescriptorKind = DescriptorKindNames.{descriptorKindName},");
            sb.AppendLine($"                    Scope = scopeString,");
            sb.AppendLine($"                    Purpose = CanonicalHashPurposeNames.Definition,");
            sb.AppendLine($"                    CanonicalShapeVersion = \"{profile.DefinitionShapeVersion}\",");
            sb.AppendLine("                    AlgorithmVersion = algorithmVersion,");
            sb.AppendLine("                    ContractVersion = contractVersion");
            sb.AppendLine("                },");
            sb.AppendLine($"                w => {writerClassName}.WriteDefinitionEnvelope(w, d, scopeString, algorithmVersion, contractVersion)),");
        }

        sb.AppendLine("            _ => throw new InvalidOperationException(");
        sb.AppendLine("                \"No canonical hash profile registered for the given descriptor type\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }
}
