using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using CrestCreates.CodeGenerator.Authorization;

namespace CrestCreates.CodeGenerator.ControllerGenerator
{
    [Generator]
    public class ControllerSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 创建增量数据源：查找带有ServiceAttribute的类
            var serviceClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsServiceCandidate(node),
                    transform: static (ctx, _) => GetServiceClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            // 注册源代码生成
            context.RegisterSourceOutput(serviceClasses, ExecuteGeneration);
        }

        private static bool IsServiceCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration &&
                   classDeclaration.AttributeLists.Count > 0;
        }

        private static bool HasServiceAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass != null && (
                    attr.AttributeClass.Name == "ServiceAttribute" ||
                    attr.AttributeClass.Name == "Service" ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".ServiceAttribute") ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".Service")
                ));
        }

        private static INamedTypeSymbol? GetServiceClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && HasServiceAttribute(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> serviceClasses)
        {
            if (serviceClasses.IsDefaultOrEmpty)
                return;

            // 去重处理
            var uniqueServices = serviceClasses
                .Where(s => s != null)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .ToList();

            try
            {
                // 生成API控制器
                foreach (var service in uniqueServices)
                {
                    if (GetAttributeProperty(service, "GenerateController", true))
                    {
                        GenerateApiController(context, service);
                    }
                }
            }
            catch (Exception ex)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("CCCG003", "Controller generation error",
                        $"Error generating controller code: {ex.Message}",
                        "CodeGeneration", DiagnosticSeverity.Warning, true),
                    Location.None));
            }
        }

        private void GenerateApiController(SourceProductionContext context, INamedTypeSymbol serviceClass)
        {
            if (serviceClass == null) return;
            
            var serviceName = serviceClass.Name;
            var namespaceName = serviceClass.ContainingNamespace.ToDisplayString();
            var routeAttr = GetAttributeProperty(serviceClass, "Route", "");
            var route = !string.IsNullOrEmpty(routeAttr) 
                ? routeAttr 
                : $"api/{serviceName.Replace("Service", "").ToLowerInvariant()}";
            
            // 查找该服务的接口
            INamedTypeSymbol? interfaceSymbol = null;
            foreach (var iface in serviceClass.Interfaces)
            {
                if (iface.Name.StartsWith("I") && 
                    iface.Name.Substring(1) == serviceName)
                {
                    interfaceSymbol = iface;
                    break;
                }
            }

            // 如果没有接口，使用生成的接口
            var serviceInterface = interfaceSymbol?.ToDisplayString() ?? $"{namespaceName}.I{serviceName}";
            var controllerName = serviceName.Replace("Service", "");
            
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using System.Threading.Tasks;");
            builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
            builder.AppendLine("using Microsoft.Extensions.Logging;");
            builder.AppendLine("using FluentValidation;");
            builder.AppendLine("using CrestCreates.Infrastructure.Authorization;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine($"using {namespaceName}.Validators;");
            
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.Controllers");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {controllerName} API 控制器");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    [ApiController]");
            builder.AppendLine($"    [Route(\"{route}\")]");
            
            builder.AppendLine($"    public partial class {controllerName}Controller : ControllerBase");

            builder.AppendLine("    {");
            builder.AppendLine($"        private readonly {serviceInterface} _service;");
            builder.AppendLine($"        private readonly ILogger<{controllerName}Controller> _logger;");
            builder.AppendLine("        private readonly IValidatorFactory _validatorFactory;");
            builder.AppendLine();
            
            builder.AppendLine($"        public {controllerName}Controller(");
            builder.AppendLine($"            {serviceInterface} service,");
            builder.AppendLine($"            ILogger<{controllerName}Controller> logger,");
            builder.AppendLine("            IValidatorFactory validatorFactory)");
            builder.AppendLine("        {");
            builder.AppendLine("            _service = service ?? throw new ArgumentNullException(nameof(service));");
            builder.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
            builder.AppendLine("            _validatorFactory = validatorFactory ?? throw new ArgumentNullException(nameof(validatorFactory));");
            builder.AppendLine("        }");
            builder.AppendLine();
            
            // 获取授权配置
            var generateAuthorization = GetAttributeProperty(serviceClass, "GenerateAuthorization", false);
            var resourceName = GetAttributeProperty(serviceClass, "ResourceName", "");
            var generateCrudPermissions = GetAttributeProperty(serviceClass, "GenerateCrudPermissions", true);
            var defaultRoles = GetAttributeProperty<string[]>(serviceClass, "DefaultRoles", Array.Empty<string>());
            var requireAll = GetAttributeProperty(serviceClass, "RequireAll", false);
            var requireAuthorizationForAll = GetAttributeProperty(serviceClass, "RequireAuthorizationForAll", true);
            
            // 验证授权配置
            ValidateAuthorizationConfig(context, serviceClass, generateAuthorization, resourceName);
            
            // 控制器级别的授权
            if (generateAuthorization && requireAuthorizationForAll)
            {
                builder.AppendLine("    [Authorize]");
            }
            
            // 为每个公共方法生成API端点
            var methods = serviceClass.GetMembers().OfType<IMethodSymbol>()
                .Where(m => m.DeclaredAccessibility == Accessibility.Public && 
                           !m.IsStatic &&
                           m.MethodKind == MethodKind.Ordinary);
                
            foreach (var method in methods)
            {
                GenerateControllerAction(builder, method, serviceName, namespaceName, generateAuthorization, resourceName, generateCrudPermissions, defaultRoles, requireAll, requireAuthorizationForAll);
            }
            
            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource($"{controllerName}Controller.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private void GenerateControllerAction(StringBuilder builder, IMethodSymbol method, string serviceName, string namespaceName, bool generateAuthorization, string resourceName, bool generateCrudPermissions, string[] defaultRoles, bool requireAll, bool requireAuthorizationForAll = true)
        {
            var methodName = method.Name;
            var returnType = method.ReturnType.ToDisplayString();
            var httpVerb = DetermineHttpVerb(methodName);
            var routeTemplate = GenerateRouteTemplate(methodName, method.Parameters);
            
            builder.AppendLine("        /// <summary>");
            builder.AppendLine($"        /// {methodName}");
            builder.AppendLine("        /// </summary>");
            
            // 生成授权特性
            if (generateAuthorization)
            {
                GenerateAuthorizationAttributes(builder, methodName, httpVerb, resourceName, generateCrudPermissions, defaultRoles, requireAll);
            }
            
            builder.AppendLine($"        [Http{httpVerb}(\"{routeTemplate}\")]");
            builder.AppendLine("        [ProducesResponseType(200)]");
            builder.AppendLine("        [ProducesResponseType(400)]");
            builder.AppendLine("        [ProducesResponseType(500)]");
            
            // 方法签名
            builder.Append($"        public async Task<IActionResult> {methodName}(");
            
            // 参数列表
            var parameters = new List<string>();
            foreach (var parameter in method.Parameters)
            {
                string paramAttr = DetermineParameterAttribute(parameter, httpVerb);
                parameters.Add($"{paramAttr}{parameter.Type.ToDisplayString()} {parameter.Name}");
            }
            
            builder.Append(string.Join(", ", parameters));
            builder.AppendLine(")");
            builder.AppendLine("        {");
            builder.AppendLine("            try");
            builder.AppendLine("            {");
            
            // 添加验证逻辑
            foreach (var parameter in method.Parameters)
            {
                var paramType = parameter.Type;
                var paramName = parameter.Name;
                if (IsDtoType(paramType))
                {
                    builder.AppendLine($"                // 验证 {paramName}");
                    builder.AppendLine($"                var validator = _validatorFactory.GetValidator<{paramType.ToDisplayString()}>();");
                    builder.AppendLine($"                if (validator != null)");
                    builder.AppendLine("                {");
                    builder.AppendLine($"                    var validationResult = await validator.ValidateAsync({paramName});");
                    builder.AppendLine("                    if (!validationResult.IsValid)");
                    builder.AppendLine("                    {");
                    builder.AppendLine($"                        _logger.LogWarning(\"Validation failed for {paramName}\");");
                    builder.AppendLine("                        return BadRequest(validationResult.Errors);");
                    builder.AppendLine("                    }");
                    builder.AppendLine("                }");
                    builder.AppendLine();
                }
            }
            
            // 方法实现
            if (returnType == "void" || returnType == "System.Threading.Tasks.Task")
            {
                builder.Append($"                await _service.{methodName}(");
                builder.Append(string.Join(", ", method.Parameters.Select(p => p.Name)));
                builder.AppendLine(");");
                builder.AppendLine("                return Ok();");
            }
            else
            {
                builder.Append($"                var result = await _service.{methodName}(");
                builder.Append(string.Join(", ", method.Parameters.Select(p => p.Name)));
                builder.AppendLine(");");
                builder.AppendLine("                return Ok(result);");
            }
            
            builder.AppendLine("            }");
            builder.AppendLine("            catch (ArgumentException ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogWarning(ex, \"Bad request in {methodName}\");");
            builder.AppendLine("                return BadRequest(ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine($"            catch (global::{namespaceName}.Exceptions.{serviceName}ValidationException ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogWarning(ex, \"Validation error in {methodName}\");");
            builder.AppendLine("                return BadRequest(ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine($"            catch (global::{namespaceName}.Exceptions.{serviceName}NotFoundException ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogWarning(ex, \"Not found error in {methodName}\");");
            builder.AppendLine("                return NotFound(ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine($"            catch (global::{namespaceName}.Exceptions.{serviceName}BusinessException ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogWarning(ex, \"Business error in {methodName}\");");
            builder.AppendLine("                return BadRequest(ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine($"            catch (global::{namespaceName}.Exceptions.{serviceName}Exception ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogError(ex, \"Service error in {methodName}\");");
            builder.AppendLine("                return StatusCode(500, ex.Message);");
            builder.AppendLine("            }");
            builder.AppendLine("            catch (Exception ex)");
            builder.AppendLine("            {");
            builder.AppendLine($"                _logger.LogError(ex, \"Unexpected error in {methodName}\");");
            builder.AppendLine("                return StatusCode(500, \"An unexpected error occurred while processing your request.\");");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private string DetermineParameterAttribute(IParameterSymbol parameter, string httpVerb)
        {
            var typeName = parameter.Type.ToDisplayString();
            
            // 简单类型从路由或查询字符串获取
            if (parameter.Type.SpecialType != SpecialType.None || 
                typeName == "string" || 
                typeName == "System.Guid" ||
                typeName.StartsWith("System."))
            {
                return "[FromRoute] ";
            }
            
            // 复杂类型从请求体获取
            if (httpVerb == "Get")
            {
                return "[FromQuery] ";
            }
            
            return "[FromBody] ";
        }

        private string DetermineHttpVerb(string methodName)
        {
            if (methodName.StartsWith("Get"))
                return "Get";
            if (methodName.StartsWith("Create") || methodName.StartsWith("Add") || methodName.StartsWith("Insert"))
                return "Post";
            if (methodName.StartsWith("Update"))
                return "Put";
            if (methodName.StartsWith("Delete") || methodName.StartsWith("Remove"))
                return "Delete";
            if (methodName.StartsWith("Patch"))
                return "Patch";
            
            return "Post"; // 默认
        }

        private string GenerateRouteTemplate(string methodName, ImmutableArray<IParameterSymbol> parameters)
        {
            if (methodName.StartsWith("Get"))
            {
                // GetById -> {id}
                if (methodName.EndsWith("ById") && parameters.Length > 0)
                    return $"{{{parameters[0].Name}}}";
                // GetAll -> 空路由
                if (methodName.EndsWith("All") || methodName == "Get")
                    return "";
                // GetByXxx -> byxxx
                if (methodName.StartsWith("GetBy") && parameters.Length > 0)
                    return $"by{methodName.Substring(5).ToLowerInvariant()}/{{{parameters[0].Name}}}";
            }
            
            if (methodName.StartsWith("Create") || methodName.StartsWith("Add"))
            {
                return "";
            }
            
            if (methodName.StartsWith("Update") && parameters.Length > 0)
            {
                return $"{{{parameters[0].Name}}}";
            }
            
            if (methodName.StartsWith("Delete") && parameters.Length > 0)
            {
                return $"{{{parameters[0].Name}}}";
            }
            
            // 其他情况，使用方法名的小写形式
            return methodName.ToLowerInvariant();
        }
        
        private void GenerateAuthorizationAttributes(StringBuilder builder, string methodName, string httpVerb, string resourceName, bool generateCrudPermissions, string[] defaultRoles, bool requireAll)
        {
            if (string.IsNullOrEmpty(resourceName))
            {
                // 如果没有指定资源名称，使用方法名的前缀
                resourceName = AuthorizationHelper.GetResourceNameFromMethodName(methodName);
            }
            
            var attributes = AuthorizationHelper.GenerateAuthorizationAttributes(
                methodName, 
                httpVerb, 
                resourceName, 
                generateCrudPermissions, 
                defaultRoles, 
                requireAll);
            
            if (!string.IsNullOrEmpty(attributes))
            {
                builder.AppendLine("        " + attributes);
            }
        }
        
        private void ValidateAuthorizationConfig(SourceProductionContext context, INamedTypeSymbol serviceClass, bool generateAuthorization, string resourceName)
        {
            if (generateAuthorization)
            {
                if (string.IsNullOrEmpty(resourceName))
                {
                    // 生成警告：资源名称为空
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("CCCG004", "Authorization configuration warning",
                            $"GenerateAuthorization is true but ResourceName is empty for service {serviceClass.Name}. Resource name will be inferred from method names.",
                            "CodeGeneration", DiagnosticSeverity.Warning, true),
                        serviceClass.Locations[0]));
                }
            }
        }
        
        private T GetAttributeProperty<T>(ISymbol symbol, string propertyName, T defaultValue)
        {
            if (symbol == null)
                return defaultValue;
                
            var attr = symbol.GetAttributes()
                .FirstOrDefault(attr => attr.AttributeClass?.Name == "ServiceAttribute" || 
                                     attr.AttributeClass?.Name == "Service");

            if (attr == null)
                return defaultValue;

            var namedArg = attr.NamedArguments
                .FirstOrDefault(arg => arg.Key == propertyName);

            if (namedArg.Key == propertyName)
            {
                if (namedArg.Value.Value is T value)
                    return value;
                
                // 处理数组类型
                if (typeof(T).IsArray && namedArg.Value.Value is IEnumerable<object> arrayValues)
                {
                    var elementType = typeof(T).GetElementType();
                    if (elementType == typeof(string))
                    {
                        var stringArray = arrayValues.OfType<string>().ToArray();
                        return (T)(object)stringArray;
                    }
                }
            }

            return defaultValue;
        }

        private bool IsDtoType(ITypeSymbol type)
        {
            var typeName = type.Name;
            return typeName.EndsWith("Dto") || 
                   typeName.EndsWith("Request") || 
                   typeName.EndsWith("Input") || 
                   typeName.EndsWith("Command");
        }
    }
}