using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.ControllerGenerator
{
    [Generator]
    public sealed class CrudControllerSourceGenerator : IIncrementalGenerator
    {
        private const string CrudApiControllerAttributeName = "CrestCreates.Domain.Shared.Attributes.CrestCrudApiControllerAttribute";
        private const string CrudAppServiceNamespace = "CrestCreates.Application.Contracts.Interfaces";
        private const string CrudAppServiceMetadataName = "ICrudAppService`5";
        private const string CrudControllerBaseMetadataName = "CrestCreates.AspNetCore.Controllers.CrudControllerBase`6";
        private const string ControllerBaseMetadataName = "Microsoft.AspNetCore.Mvc.ControllerBase";

        private static readonly SymbolDisplayFormat FullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var controllerInfos = context.CompilationProvider.Select(static (compilation, _) => GetControllerInfos(compilation));
            context.RegisterSourceOutput(controllerInfos, ExecuteGeneration);
        }

        private static List<CrudControllerInfo> GetControllerInfos(Compilation compilation)
        {
            var result = new List<CrudControllerInfo>();

            if (compilation.GetTypeByMetadataName(CrudControllerBaseMetadataName) == null ||
                compilation.GetTypeByMetadataName(ControllerBaseMetadataName) == null)
            {
                return result;
            }

            var processedServices = new HashSet<string>(StringComparer.Ordinal);
            foreach (var type in GetAllCandidateTypes(compilation))
            {
                if (type.TypeKind != TypeKind.Interface)
                {
                    continue;
                }

                var attribute = type.GetAttributes()
                    .FirstOrDefault(attr => attr.AttributeClass?.ToDisplayString() == CrudApiControllerAttributeName);
                if (attribute == null)
                {
                    continue;
                }

                var serviceName = type.ToDisplayString(FullyQualifiedFormat);
                if (!processedServices.Add(serviceName))
                {
                    continue;
                }

                var crudAppService = type.AllInterfaces.FirstOrDefault(IsCrudAppServiceInterface);
                if (crudAppService == null || crudAppService.TypeArguments.Length != 5)
                {
                    continue;
                }

                var controllerName = GetAttributeStringArgument(attribute, 0, "ControllerName");
                var route = GetAttributeStringArgument(attribute, 1, "Route");
                if (string.IsNullOrWhiteSpace(controllerName) || string.IsNullOrWhiteSpace(route))
                {
                    continue;
                }

                result.Add(new CrudControllerInfo(
                    GetControllerNamespace(type),
                    ToControllerClassName(controllerName!),
                    route!,
                    serviceName,
                    crudAppService.TypeArguments[0].ToDisplayString(FullyQualifiedFormat),
                    crudAppService.TypeArguments[1].ToDisplayString(FullyQualifiedFormat),
                    crudAppService.TypeArguments[2].ToDisplayString(FullyQualifiedFormat),
                    crudAppService.TypeArguments[3].ToDisplayString(FullyQualifiedFormat),
                    crudAppService.TypeArguments[4].ToDisplayString(FullyQualifiedFormat)));
            }

            return result;
        }

        private static void ExecuteGeneration(SourceProductionContext context, List<CrudControllerInfo> controllerInfos)
        {
            foreach (var info in controllerInfos)
            {
                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated />");
                builder.AppendLine("#nullable enable");
                builder.AppendLine("using CrestCreates.AspNetCore.Controllers;");
                builder.AppendLine("using Microsoft.AspNetCore.Mvc;");
                builder.AppendLine();
                builder.AppendLine($"namespace {info.Namespace}");
                builder.AppendLine("{");
                builder.AppendLine("    /// <summary>");
                builder.AppendLine($"    /// {info.ControllerClassName} CRUD API 控制器");
                builder.AppendLine("    /// </summary>");
                builder.AppendLine("    [ApiController]");
                builder.AppendLine("    [Route(\"" + EscapeStringLiteral(info.Route) + "\")]");
                builder.AppendLine($"    public sealed partial class {info.ControllerClassName} : CrudControllerBase<{info.ServiceType}, {info.KeyType}, {info.DtoType}, {info.CreateDtoType}, {info.UpdateDtoType}, {info.ListRequestDtoType}>");
                builder.AppendLine("    {");
                builder.AppendLine($"        public {info.ControllerClassName}({info.ServiceType} service)");
                builder.AppendLine("            : base(service)");
                builder.AppendLine("        {");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine("}");

                context.AddSource($"{info.ControllerClassName}.{GetStableSuffix(info.ServiceType)}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
            }
        }

        private static bool IsCrudAppServiceInterface(INamedTypeSymbol symbol)
        {
            return symbol.OriginalDefinition.MetadataName == CrudAppServiceMetadataName &&
                   symbol.OriginalDefinition.ContainingNamespace.ToDisplayString() == CrudAppServiceNamespace;
        }

        private static IEnumerable<INamedTypeSymbol> GetAllCandidateTypes(Compilation compilation)
        {
            foreach (var type in GetAllTypes(compilation.Assembly.GlobalNamespace))
            {
                yield return type;
            }

            foreach (var reference in compilation.References)
            {
                if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assemblySymbol)
                {
                    continue;
                }

                foreach (var type in GetAllTypes(assemblySymbol.GlobalNamespace))
                {
                    yield return type;
                }
            }
        }

        private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol namespaceSymbol)
        {
            foreach (var member in namespaceSymbol.GetTypeMembers())
            {
                foreach (var type in GetAllNestedTypes(member))
                {
                    yield return type;
                }
            }

            foreach (var nestedNamespace in namespaceSymbol.GetNamespaceMembers())
            {
                foreach (var type in GetAllTypes(nestedNamespace))
                {
                    yield return type;
                }
            }
        }

        private static IEnumerable<INamedTypeSymbol> GetAllNestedTypes(INamedTypeSymbol typeSymbol)
        {
            yield return typeSymbol;

            foreach (var nestedType in typeSymbol.GetTypeMembers())
            {
                foreach (var type in GetAllNestedTypes(nestedType))
                {
                    yield return type;
                }
            }
        }

        private static string? GetAttributeStringArgument(AttributeData attribute, int constructorIndex, string propertyName)
        {
            if (attribute.ConstructorArguments.Length > constructorIndex &&
                attribute.ConstructorArguments[constructorIndex].Value is string constructorValue)
            {
                return constructorValue;
            }

            foreach (var namedArgument in attribute.NamedArguments)
            {
                if (namedArgument.Key == propertyName && namedArgument.Value.Value is string namedValue)
                {
                    return namedValue;
                }
            }

            return null;
        }

        private static string GetControllerNamespace(INamedTypeSymbol serviceInterface)
        {
            var serviceNamespace = serviceInterface.ContainingNamespace.IsGlobalNamespace
                ? "Generated.Controllers"
                : serviceInterface.ContainingNamespace.ToDisplayString();

            return serviceNamespace.EndsWith(".Services", StringComparison.Ordinal)
                ? serviceNamespace.Substring(0, serviceNamespace.Length - ".Services".Length) + ".Controllers"
                : serviceNamespace + ".Controllers";
        }

        private static string ToControllerClassName(string controllerName)
        {
            var sanitized = SanitizeIdentifier(controllerName);
            return sanitized.EndsWith("Controller", StringComparison.Ordinal)
                ? sanitized
                : sanitized + "Controller";
        }

        private static string SanitizeIdentifier(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "Generated";
            }

            var builder = new StringBuilder();
            foreach (var ch in value)
            {
                builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            }

            if (builder.Length == 0 || !IsIdentifierStartCharacter(builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        private static bool IsIdentifierStartCharacter(char ch)
        {
            return char.IsLetter(ch) || ch == '_';
        }

        private static string GetStableSuffix(string value)
        {
            unchecked
            {
                uint hash = 17;
                foreach (var ch in value)
                {
                    hash = hash * 31 + ch;
                }

                return hash.ToString("X");
            }
        }

        private static string EscapeStringLiteral(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private sealed class CrudControllerInfo
        {
            public CrudControllerInfo(
                string @namespace,
                string controllerClassName,
                string route,
                string serviceType,
                string keyType,
                string dtoType,
                string createDtoType,
                string updateDtoType,
                string listRequestDtoType)
            {
                Namespace = @namespace;
                ControllerClassName = controllerClassName;
                Route = route;
                ServiceType = serviceType;
                KeyType = keyType;
                DtoType = dtoType;
                CreateDtoType = createDtoType;
                UpdateDtoType = updateDtoType;
                ListRequestDtoType = listRequestDtoType;
            }

            public string Namespace { get; }

            public string ControllerClassName { get; }

            public string Route { get; }

            public string ServiceType { get; }

            public string KeyType { get; }

            public string DtoType { get; }

            public string CreateDtoType { get; }

            public string UpdateDtoType { get; }

            public string ListRequestDtoType { get; }
        }
    }
}
