namespace CrestCreates.DynamicApi.Abstractions;

/// <summary>
/// Provides the compatibility projection manifest for AppService-to-Capability mapping.
/// Generated by AppServiceCompatibilityGenerator for each projected [CrestService].
/// </summary>
public interface IAppServiceCompatibilityProjectionManifestProvider
{
    IReadOnlyList<AppServiceCompatibilityProjectionEntry> GetEntries();
}
