<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CrestCreates.EventBus.RabbitMQ.Tests.Integration</RootNamespace>
    <AssemblyName>CrestCreates.EventBus.RabbitMQ.Tests.Integration</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Runtime\CrestCreates.EventBus.RabbitMQ\CrestCreates.EventBus.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\src\Runtime\CrestCreates.EventBus.Abstract\CrestCreates.EventBus.Abstract.csproj" />
    <ProjectReference Include="..\..\..\src\Framework\CrestCreates.Domain\CrestCreates.Domain.csproj" />
  </ItemGroup>

</Project>