using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using FluentAssertions;
using SaaSHelpdesk.Tests.Fixtures;
using Xunit;

namespace SaaSHelpdesk.Tests;

/// <summary>
/// End-to-end tests for the SLA Policy Dynamic API.
/// Verifies all CRUD branches of SLAPolicyAppService through the generated endpoints.
///
/// Routes (generated by ToKebabCase from "SLAPolicy"):
///   POST   /api/s-l-a-policy        → Create
///   GET    /api/s-l-a-policy/{id}   → GetById
///   GET    /api/s-l-a-policy/all    → GetAll
///   PUT    /api/s-l-a-policy/{id}   → Update
///   DELETE /api/s-l-a-policy/{id}   → Delete (If-Match header for concurrency)
/// </summary>
public class SLAPolicyApiTests : BaseTest
{
    private const string RoutePrefix = "/api/s-l-a-policy";

    public SLAPolicyApiTests(HelpdeskWebApplicationFactory factory)
        : base(factory)
    {
    }

    // ═══════════════════════════════════════════════════════════════
    //  CREATE
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public async Task CreateAsync_WithAllPriorityLevels_ShouldReturnCreatedPolicy()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();

        var request = new
        {
            Name = "Standard SLA",
            Description = "Standard support SLA policy covering all priority levels",
            IsActive = true,
            LowPriorityResponseMinutes = 240,
            LowPriorityResolutionMinutes = 1440,
            MediumPriorityResponseMinutes = 120,
            MediumPriorityResolutionMinutes = 720,
            HighPriorityResponseMinutes = 60,
            HighPriorityResolutionMinutes = 480,
            UrgentPriorityResponseMinutes = 15,
            UrgentPriorityResolutionMinutes = 120
        };

        // Act
        var response = await PostAsync(client, RoutePrefix, request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        var envelope = await ReadApiResponseAsync<SlaPolicyResponse>(response);
        envelope.Data.Should().NotBeNull();
        var policy = envelope.Data!;

        policy.Id.Should().NotBe(Guid.Empty);
        policy.Name.Should().Be("Standard SLA");
        policy.Description.Should().Be("Standard support SLA policy covering all priority levels");
        policy.IsActive.Should().BeTrue();
        policy.LowPriorityResponseMinutes.Should().Be(240);
        policy.LowPriorityResolutionMinutes.Should().Be(1440);
        policy.MediumPriorityResponseMinutes.Should().Be(120);
        policy.MediumPriorityResolutionMinutes.Should().Be(720);
        policy.HighPriorityResponseMinutes.Should().Be(60);
        policy.HighPriorityResolutionMinutes.Should().Be(480);
        policy.UrgentPriorityResponseMinutes.Should().Be(15);
        policy.UrgentPriorityResolutionMinutes.Should().Be(120);
        policy.ConcurrencyStamp.Should().NotBeNullOrEmpty();
        policy.CreationTime.Should().BeAfter(DateTime.UtcNow.AddMinutes(-1));
    }

    // ═══════════════════════════════════════════════════════════════
    //  GET BY ID
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public async Task GetByIdAsync_ExistingPolicy_ShouldReturnPolicy()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var created = await CreatePolicyAsync(client, "Support SLA");
        var getUrl = $"{RoutePrefix}/{created.Id}";

        // Act
        var response = await GetAsync(client, getUrl);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        var envelope = await ReadApiResponseAsync<SlaPolicyResponse>(response);
        var policy = envelope.Data!;

        policy.Id.Should().Be(created.Id);
        policy.Name.Should().Be("Support SLA");
        policy.LowPriorityResponseMinutes.Should().Be(240);
        policy.LowPriorityResolutionMinutes.Should().Be(1440);
    }

    [Fact]
    public async Task GetByIdAsync_NonExistingPolicy_ShouldReturn404()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var nonExistingId = Guid.NewGuid();
        var getUrl = $"{RoutePrefix}/{nonExistingId}";

        // Act
        var response = await GetAsync(client, getUrl);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NotFound, await response.Content.ReadAsStringAsync());
    }

    // ═══════════════════════════════════════════════════════════════
    //  GET ALL
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public async Task GetAllAsync_ShouldReturnAllPolicies()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var created = await CreatePolicyAsync(client, "SLA-GetAll-Test");

        // Act
        var getAllUrl = $"{RoutePrefix}/all";
        var response = await GetAsync(client, getAllUrl);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        var envelope = await ReadApiResponseAsync<List<SlaPolicyResponse>>(response);
        var policies = envelope.Data!;

        policies.Should().NotBeEmpty();
        policies.Should().Contain(p => p.Id == created.Id);
        policies.Should().Contain(p => p.Name == "SLA-GetAll-Test");
    }

    // ═══════════════════════════════════════════════════════════════
    //  UPDATE
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public async Task UpdateAsync_ExistingPolicy_ShouldApplyChanges()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var created = await CreatePolicyAsync(client, "Original SLA");

        var updateUrl = $"{RoutePrefix}/{created.Id}";
        var updateRequest = new
        {
            Id = created.Id,
            Name = "Updated SLA",
            Description = "Updated description after change",
            IsActive = true,
            LowPriorityResponseMinutes = 480,
            LowPriorityResolutionMinutes = 2880,
            MediumPriorityResponseMinutes = 240,
            MediumPriorityResolutionMinutes = 1440,
            HighPriorityResponseMinutes = 120,
            HighPriorityResolutionMinutes = 960,
            UrgentPriorityResponseMinutes = 30,
            UrgentPriorityResolutionMinutes = 240,
            ConcurrencyStamp = created.ConcurrencyStamp
        };

        // Act
        var response = await PutAsync(client, updateUrl, updateRequest);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        var envelope = await ReadApiResponseAsync<SlaPolicyResponse>(response);
        var updated = envelope.Data!;

        updated.Id.Should().Be(created.Id);
        updated.Name.Should().Be("Updated SLA");
        updated.Description.Should().Be("Updated description after change");
        updated.LowPriorityResponseMinutes.Should().Be(480);
        updated.LowPriorityResolutionMinutes.Should().Be(2880);
        updated.MediumPriorityResponseMinutes.Should().Be(240);
        updated.MediumPriorityResolutionMinutes.Should().Be(1440);
        updated.HighPriorityResponseMinutes.Should().Be(120);
        updated.HighPriorityResolutionMinutes.Should().Be(960);
        updated.UrgentPriorityResponseMinutes.Should().Be(30);
        updated.UrgentPriorityResolutionMinutes.Should().Be(240);
    }

    // ═══════════════════════════════════════════════════════════════
    //  DELETE
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public async Task DeleteAsync_WithValidConcurrencyStamp_ShouldRemovePolicy()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var created = await CreatePolicyAsync(client, "SLA-To-Delete");

        // Act
        var deleteUrl = $"{RoutePrefix}/{created.Id}";
        var request = new HttpRequestMessage(HttpMethod.Delete, deleteUrl);
        request.Headers.Add("If-Match", created.ConcurrencyStamp);
        var response = await client.SendAsync(request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        // Verify gone
        var getUrl = $"{RoutePrefix}/{created.Id}";
        var getResponse = await GetAsync(client, getUrl);
        getResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task DeleteAsync_WithoutConcurrencyStamp_ShouldStillRemovePolicy()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var created = await CreatePolicyAsync(client, "SLA-Delete-No-Stamp");

        // Act — no If-Match header; delete without optimistic check
        var deleteUrl = $"{RoutePrefix}/{created.Id}";
        var response = await DeleteAsync(client, deleteUrl);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        // Verify gone
        var getUrl = $"{RoutePrefix}/{created.Id}";
        var getResponse = await GetAsync(client, getUrl);
        getResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    [Fact]
    public async Task DeleteAsync_NonExistingPolicy_ShouldReturnError()
    {
        // Arrange
        var (client, _) = await CreateAuthenticatedAdminClientAsync();
        var nonExistingId = Guid.NewGuid();
        var deleteUrl = $"{RoutePrefix}/{nonExistingId}";

        // Act
        var request = new HttpRequestMessage(HttpMethod.Delete, deleteUrl);
        var response = await client.SendAsync(request);

        // Assert — a delete against a missing entity should fail with a server error
        response.StatusCode.Should().Be(HttpStatusCode.InternalServerError, await response.Content.ReadAsStringAsync());
    }

    // ═══════════════════════════════════════════════════════════════
    //  Helpers
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Creates an SLA policy with all 4 priority levels filled and returns the parsed response.
    /// </summary>
    private async Task<SlaPolicyResponse> CreatePolicyAsync(HttpClient client, string name)
    {
        var createDto = new
        {
            Name = name,
            Description = $"Test SLA: {name}",
            IsActive = true,
            LowPriorityResponseMinutes = 240,
            LowPriorityResolutionMinutes = 1440,
            MediumPriorityResponseMinutes = 120,
            MediumPriorityResolutionMinutes = 720,
            HighPriorityResponseMinutes = 60,
            HighPriorityResolutionMinutes = 480,
            UrgentPriorityResponseMinutes = 15,
            UrgentPriorityResolutionMinutes = 120
        };

        var response = await PostAsync(client, RoutePrefix, createDto);
        response.StatusCode.Should().Be(HttpStatusCode.OK, await response.Content.ReadAsStringAsync());

        var envelope = await ReadApiResponseAsync<SlaPolicyResponse>(response);
        return envelope.Data!;
    }

    // ═══════════════════════════════════════════════════════════════
    //  Response types
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Minimal SLA Policy response model for test assertions.
    /// Matches the shape of SaaSHelpdesk.Application.Contracts.DTOs.SLAPolicyDto.
    /// </summary>
    private sealed class SlaPolicyResponse
    {
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; } = string.Empty;

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("isActive")]
        public bool IsActive { get; set; }

        [JsonPropertyName("lowPriorityResponseMinutes")]
        public int LowPriorityResponseMinutes { get; set; }

        [JsonPropertyName("lowPriorityResolutionMinutes")]
        public int LowPriorityResolutionMinutes { get; set; }

        [JsonPropertyName("mediumPriorityResponseMinutes")]
        public int MediumPriorityResponseMinutes { get; set; }

        [JsonPropertyName("mediumPriorityResolutionMinutes")]
        public int MediumPriorityResolutionMinutes { get; set; }

        [JsonPropertyName("highPriorityResponseMinutes")]
        public int HighPriorityResponseMinutes { get; set; }

        [JsonPropertyName("highPriorityResolutionMinutes")]
        public int HighPriorityResolutionMinutes { get; set; }

        [JsonPropertyName("urgentPriorityResponseMinutes")]
        public int UrgentPriorityResponseMinutes { get; set; }

        [JsonPropertyName("urgentPriorityResolutionMinutes")]
        public int UrgentPriorityResolutionMinutes { get; set; }

        [JsonPropertyName("creationTime")]
        public DateTime CreationTime { get; set; }

        [JsonPropertyName("concurrencyStamp")]
        public string ConcurrencyStamp { get; set; } = string.Empty;
    }
}
