<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Infrastructure/CrestCreates.Aop/CrestCreates.Aop.csproj" />
    <ProjectReference Include="../../Ddd/CrestCreates.Application.Contracts/CrestCreates.Application.Contracts.csproj" />
    <ProjectReference Include="../../Infrastructure/CrestCreates.Authorization.Abstractions/CrestCreates.Authorization.Abstractions.csproj" />
    <ProjectReference Include="../../Ddd/CrestCreates.Domain.Shared/CrestCreates.Domain.Shared.csproj" />
    <ProjectReference Include="../../Modularity/CrestCreates.Modularity/CrestCreates.Modularity.csproj" />
    <ProjectReference Include="../../../Persistence/CrestCreates.Data.Abstractions/CrestCreates.Data.Abstractions.csproj" />
    <ProjectReference Include="../../Infrastructure/CrestCreates.Validation/CrestCreates.Validation.csproj" />
    <ProjectReference Include="../../../Runtime/Capability/CrestCreates.Capability.Abstractions/CrestCreates.Capability.Abstractions.csproj" />
    <ProjectReference Include="../../../Metadata/CrestCreates.Metadata.Abstractions/CrestCreates.Metadata.Abstractions.csproj" />
    <ProjectReference Include="..\CrestCreates.DynamicApi.Abstractions\CrestCreates.DynamicApi.Abstractions.csproj" />
    <ProjectReference Include="../../../Metadata/CrestCreates.Metadata/CrestCreates.Metadata.csproj" />
  </ItemGroup>

</Project>
