<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrestCreates.Agent.Memory</RootNamespace>
    <AssemblyName>CrestCreates.Agent.Memory</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CrestCreates.Agent.Memory.Abstractions\CrestCreates.Agent.Memory.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Metadata\CrestCreates.Metadata.Abstractions\CrestCreates.Metadata.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
</Project>
