// framework/tools/CrestCreates.CodeGenerator/RabbitMqGenerator/RabbitMqSubscriptionCodeWriter.cs
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.RabbitMqGenerator
{
    internal sealed class RabbitMqSubscriptionCodeWriter
    {
        public string WriteRegistry(RabbitMqSubscriptionModel model)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using CrestCreates.EventBus.RabbitMQ.Options;");
            sb.AppendLine();

            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");

            WriteRegistryClass(sb, model);

            sb.AppendLine("}");

            return sb.ToString();
        }

        private void WriteRegistryClass(StringBuilder sb, RabbitMqSubscriptionModel model)
        {
            sb.AppendLine("    public static class RabbitMqSubscriptionRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IReadOnlyList<RabbitMqSubscriptionInfo> GetSubscriptions() => _subscriptions;");
            sb.AppendLine();

            // Build the static array initialization
            sb.AppendLine("        private static readonly IReadOnlyList<RabbitMqSubscriptionInfo> _subscriptions = new[]");
            sb.AppendLine("        {");

            foreach (var subscription in model.Subscriptions)
            {
                sb.AppendLine($"            new RabbitMqSubscriptionInfo(");
                sb.AppendLine($"                EventType: \"{EscapeString(subscription.EventType)}\",");
                sb.AppendLine($"                HandlerType: typeof(global::{subscription.HandlerType}),");
                sb.AppendLine($"                HandlerMethod: \"{EscapeString(subscription.HandlerMethod)}\",");
                sb.AppendLine($"                Exchange: \"{EscapeString(subscription.Exchange)}\",");
                sb.AppendLine($"                Queue: \"{EscapeString(subscription.Queue)}\",");
                sb.AppendLine($"                PrefetchCount: {subscription.PrefetchCount},");
                WriteInvokerLambda(sb, subscription);
                sb.AppendLine($"            ),");
            }

            sb.AppendLine("        };");

            sb.AppendLine("    }");
        }

        private void WriteInvokerLambda(StringBuilder sb, SubscriptionInfo subscription)
        {
            // Generate a lambda that:
            // 1. Resolves the handler from DI
            // 2. Calls the handler method with the event and cancellation token
            sb.AppendLine($"                InvokeHandler: (sp, evt, ct) =>");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    var handler = (global::{subscription.HandlerType})sp.GetRequiredService(typeof(global::{subscription.HandlerType}));");
            sb.AppendLine($"                    return handler.{subscription.HandlerMethod}(({subscription.EventType})evt!, ct);");
            sb.AppendLine($"                }})");
        }

        private static string EscapeString(string value)
        {
            if (string.IsNullOrEmpty(value))
                return value;

            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
