using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.EventBusGenerator
{
    [Generator]
    public class DomainEventSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var domainEvents = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsDomainEventCandidate(node),
                    transform: static (ctx, _) => GetDomainEventClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            var eventHandlers = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsEventHandlerCandidate(node),
                    transform: static (ctx, _) => GetEventHandlerClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            var combined = domainEvents.Combine(eventHandlers);

            context.RegisterSourceOutput(combined, ExecuteGeneration);
        }

        private static bool IsDomainEventCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration && 
                   classDeclaration.BaseList != null && 
                   classDeclaration.BaseList.Types.Any(t => 
                       t.Type.ToString().Contains("DomainEvent") || 
                       t.Type.ToString().Contains("IDomainEvent"));
        }

        private static bool IsEventHandlerCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration && 
                   classDeclaration.BaseList != null && 
                   classDeclaration.BaseList.Types.Any(t => 
                       t.Type.ToString().Contains("INotificationHandler<") || 
                       t.Type.ToString().Contains("IEventHandler<"));
        }

        private static INamedTypeSymbol? GetDomainEventClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && IsDomainEvent(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private static INamedTypeSymbol? GetEventHandlerClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
            
            if (symbol != null && IsEventHandler(symbol))
            {
                return symbol;
            }
            
            return null;
        }

        private static bool IsDomainEvent(INamedTypeSymbol symbol)
        {
            return symbol.AllInterfaces.Any(i => i.Name == "IDomainEvent") || 
                   (symbol.BaseType?.Name == "DomainEvent") || 
                   (symbol.BaseType?.AllInterfaces.Any(i => i.Name == "IDomainEvent") ?? false);
        }

        private static bool IsEventHandler(INamedTypeSymbol symbol)
        {
            return symbol.AllInterfaces.Any(i => 
                i.Name == "INotificationHandler" || 
                i.Name == "IEventHandler");
        }

        private void ExecuteGeneration(SourceProductionContext context, (ImmutableArray<INamedTypeSymbol?> Events, ImmutableArray<INamedTypeSymbol?> Handlers) data)
        {
            var (events, handlers) = data;

            if (events.IsDefaultOrEmpty && handlers.IsDefaultOrEmpty)
                return;

            GenerateEventBusExtensions(context, events, handlers);
            GenerateDomainEventHelper(context);
        }

        private void GenerateEventBusExtensions(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> events, ImmutableArray<INamedTypeSymbol?> handlers)
        {
            var eventTypes = events.Where(e => e != null).ToList();
            var handlerTypes = handlers.Where(h => h != null).ToList();

            if (!eventTypes.Any() && !handlerTypes.Any())
                return;

            var sourceCode = "// <auto-generated /\n";
            sourceCode += "using System;\n";
            sourceCode += "using System.Collections.Generic;\n";
            sourceCode += "using System.Reflection;\n";
            sourceCode += "using Microsoft.Extensions.DependencyInjection;\n";
            sourceCode += "using MediatR;\n";
            sourceCode += "using CrestCreates.Domain.DomainEvents;\n";
            sourceCode += "using CrestCreates.Infrastructure.EventBus.Local;\n";
            sourceCode += "\n";
            sourceCode += "namespace CrestCreates.Infrastructure.EventBus\n";
            sourceCode += "{\n";
            sourceCode += "    /// <summary>\n";
            sourceCode += "    /// 事件总线扩展方法\n";
            sourceCode += "    /// </summary>\n";
            sourceCode += "    public static class EventBusExtensions\n";
            sourceCode += "    {\n";
            sourceCode += "        /// <summary>\n";
            sourceCode += "        /// 注册领域事件处理器\n";
            sourceCode += "        /// </summary>\n";
            sourceCode += "        /// <param name=" + """services""" + @">服务集合</param>\n";
            sourceCode += "        /// <param name=" + """assemblies""" + @">包含事件处理器的程序集</param>\n";
            sourceCode += "        /// <returns></returns>\n";
            sourceCode += "        public static IServiceCollection AddDomainEventHandlers(this IServiceCollection services, params Assembly[] assemblies)\n";
            sourceCode += "        {\n";
            sourceCode += "            services.AddMediatR(config =>\n";
            sourceCode += "            {\n";
            sourceCode += "                if (assemblies != null && assemblies.Length > 0)\n";
            sourceCode += "                {\n";
            sourceCode += "                    foreach (var assembly in assemblies)\n";
            sourceCode += "                    {\n";
            sourceCode += "                        config.RegisterServicesFromAssembly(assembly);\n";
            sourceCode += "                    }\n";
            sourceCode += "                }\n";
            sourceCode += "            });\n";
            sourceCode += "            \n";
            sourceCode += "            services.AddScoped<IDomainEventPublisher, DomainEventPublisher>();\n";
            sourceCode += "            \n";
            sourceCode += "            return services;\n";
            sourceCode += "        }\n";
            sourceCode += "        \n";
            sourceCode += "        /// <summary>\n";
            sourceCode += "        /// 注册领域事件处理器（从当前程序集）\n";
            sourceCode += "        /// </summary>\n";
            sourceCode += "        /// <param name=" + """services""" + @">服务集合</param>\n";
            sourceCode += "        /// <returns></returns>\n";
            sourceCode += "        public static IServiceCollection AddDomainEventHandlers(this IServiceCollection services)\n";
            sourceCode += "        {\n";
            sourceCode += "            return services.AddDomainEventHandlers(Assembly.GetCallingAssembly());\n";
            sourceCode += "        }\n";
            sourceCode += "    }\n";
            sourceCode += "}";

            context.AddSource("EventBusExtensions.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }

        private void GenerateDomainEventHelper(SourceProductionContext context)
        {
            var sourceCode = "// <auto-generated /\n";
            sourceCode += "using System;\n";
            sourceCode += "using System.Collections.Generic;\n";
            sourceCode += "using System.Threading;\n";
            sourceCode += "using System.Threading.Tasks;\n";
            sourceCode += "using CrestCreates.Domain.DomainEvents;\n";
            sourceCode += "using CrestCreates.Domain.Entities;\n";
            sourceCode += "\n";
            sourceCode += "namespace CrestCreates.Infrastructure.EventBus\n";
            sourceCode += "{\n";
            sourceCode += "    /// <summary>\n";
            sourceCode += "    /// 领域事件辅助类\n";
            sourceCode += "    /// </summary>\n";
            sourceCode += "    public static class DomainEventHelper\n";
            sourceCode += "    {\n";
            sourceCode += "        /// <summary>\n";
            sourceCode += "        /// 从实体集合中获取所有领域事件\n";
            sourceCode += "        /// </summary>\n";
            sourceCode += "        /// <typeparam name=" + """TEntity""" + @">实体类型</typeparam>\n";
            sourceCode += "        /// <typeparam name=" + """TId""" + @">实体ID类型</typeparam>\n";
            sourceCode += "        /// <param name=" + """entities""" + @">实体集合</param>\n";
            sourceCode += "        /// <returns>领域事件列表</returns>\n";
            sourceCode += "        public static List<(TEntity Entity, IDomainEvent Event)> GetDomainEvents<TEntity, TId>(IEnumerable<TEntity> entities)\n";
            sourceCode += "            where TEntity : Entity<TId>\n";
            sourceCode += "            where TId : IEquatable<TId>\n";
            sourceCode += "        {\n";
            sourceCode += "            var events = new List<(TEntity, IDomainEvent)>();\n";
            sourceCode += "            \n";
            sourceCode += "            foreach (var entity in entities)\n";
            sourceCode += "            {\n";
            sourceCode += "                foreach (var domainEvent in entity.DomainEvents)\n";
            sourceCode += "                {\n";
            sourceCode += "                    events.Add((entity, domainEvent));\n";
            sourceCode += "                }\n";
            sourceCode += "            }\n";
            sourceCode += "            \n";
            sourceCode += "            return events;\n";
            sourceCode += "        }\n";
            sourceCode += "        \n";
            sourceCode += "        /// <summary>\n";
            sourceCode += "        /// 发布领域事件并清空实体的事件列表\n";
            sourceCode += "        /// </summary>\n";
            sourceCode += "        /// <typeparam name=" + """TEntity""" + @">实体类型</typeparam>\n";
            sourceCode += "        /// <typeparam name=" + """TId""" + @">实体ID类型</typeparam>\n";
            sourceCode += "        /// <param name=" + """publisher""" + @">事件发布器</param>\n";
            sourceCode += "        /// <param name=" + """entities""" + @">实体集合</param>\n";
            sourceCode += "        /// <param name=" + """cancellationToken""" + @">取消令牌</param>\n";
            sourceCode += "        /// <returns></returns>\n";
            sourceCode += "        public static async Task PublishDomainEventsAsync<TEntity, TId>(\n";
            sourceCode += "            this IDomainEventPublisher publisher,\n";
            sourceCode += "            IEnumerable<TEntity> entities,\n";
            sourceCode += "            CancellationToken cancellationToken = default)\n";
            sourceCode += "            where TEntity : Entity<TId>\n";
            sourceCode += "            where TId : IEquatable<TId>\n";
            sourceCode += "        {\n";
            sourceCode += "            foreach (var entity in entities)\n";
            sourceCode += "            {\n";
            sourceCode += "                foreach (var domainEvent in entity.DomainEvents)\n";
            sourceCode += "                {\n";
            sourceCode += "                    await publisher.PublishAsync(domainEvent, cancellationToken);\n";
            sourceCode += "                }\n";
            sourceCode += "                entity.ClearDomainEvents();\n";
            sourceCode += "            }\n";
            sourceCode += "        }\n";
            sourceCode += "    }\n";
            sourceCode += "}";

            context.AddSource("DomainEventHelper.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }
}