using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AppServiceCompatibilityGenerator;

internal static class AppServiceCompatibilityJsonContextEmitter
{
    /// <summary>
    /// Emits a JsonSerializerContext partial class with [JsonSerializable] for all body types
    /// found in the compatibility service model's actions.
    /// </summary>
    public static string Emit(CompatibilityServiceModel service)
    {
        var bodyTypes = CollectBodyTypes(service);
        if (bodyTypes.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();

        sb.AppendLine($"[JsonSerializable(typeof({bodyTypes.First()}))");
        foreach (var type in bodyTypes.Skip(1))
        {
            sb.AppendLine($"   ,JsonSerializable(typeof({type}))");
        }
        sb.AppendLine("   ]");
        sb.AppendLine($"internal sealed partial class GeneratedCompatibilityEndpointJsonContext : JsonSerializerContext");
        sb.AppendLine("{");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Returns the STJ property accessor for a body type in the generated context.
    /// Uses GetTypeInfo(typeof(T)) with a cast — this compiles without STJ's
    /// source generator output while remaining AOT-safe at runtime (the cast
    /// succeeds because [JsonSerializable] guarantees metadata registration).
    /// </summary>
    public static string GetTypeInfoAccessor(string typeName)
    {
        return $"(System.Text.Json.Serialization.Metadata.JsonTypeInfo<{typeName}>)GeneratedCompatibilityEndpointJsonContext.Default.GetTypeInfo(typeof({typeName}))!";
    }

    private static HashSet<string> CollectBodyTypes(CompatibilityServiceModel service)
    {
        var bodyTypes = new HashSet<string>();
        foreach (var action in service.Actions)
        {
            foreach (var param in action.Parameters)
            {
                if (param.Source == "Body")
                {
                    bodyTypes.Add(param.TypeName);
                }
            }
        }
        return bodyTypes;
    }

    /// <summary>
    /// Converts a type name to the STJ-generated property name format.
    /// STJ removes dots, angle brackets, commas, spaces, and global:: markers
    /// from the full qualified name.
    /// e.g., "global::TestNs.CreateDto" → "TestNsCreateDto"
    /// e.g., "List&lt;BookDto&gt;" → "ListBookDto"
    /// </summary>
    private static string ToStjPropertyName(string typeName)
    {
        var name = typeName.StartsWith("global::")
            ? typeName.Substring("global::".Length)
            : typeName;

        // Also strip any remaining global:: markers (e.g., in nested generic type args)
        name = name.Replace("global::", "");

        var result = new StringBuilder();
        foreach (var c in name)
        {
            if (c == '<' || c == '>' || c == ',' || c == ' ' || c == '.' || c == ':')
                continue;
            result.Append(c);
        }
        return result.ToString();
    }
}
