using System.Text;

namespace CrestCreates.CodeGenerator.AppServiceCompatibilityGenerator;

/// <summary>
/// Emits [ModuleInitializer] code that registers per-endpoint result contracts
/// via <see cref="CapabilityEndpointResultContractRegistration"/>. Each endpoint
/// gets a lambda that wraps the raw handler output in a
/// <see cref="DynamicApiResponse"/> / <see cref="DynamicApiResponse{T}"/>
/// envelope matching legacy AppService behavior.
///
/// Wrap method selection:
///   - Void return  →  DynamicApiGeneratedRuntime.WrapVoidResult()
///   - GET non-void →  DynamicApiGeneratedRuntime.WrapGetResult(ctx.Output)
///   - Other non-void → DynamicApiGeneratedRuntime.WrapResult(ctx.Output)
/// </summary>
internal static class AppServiceCompatibilityResultContractEmitter
{
    public static string Emit(CompatibilityServiceModel service)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using CrestCreates.DynamicApi;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();

        sb.AppendLine($"internal static class GeneratedAppServiceCompatibilityResultContracts_{service.SanitizedIdentifier}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var action in service.Actions)
        {
            string wrapExpression;

            if (action.IsVoidReturn)
            {
                wrapExpression = "DynamicApiGeneratedRuntime.WrapVoidResult()";
            }
            else if (action.HttpMethod == "GET")
            {
                wrapExpression = "DynamicApiGeneratedRuntime.WrapGetResult(ctx.Output)";
            }
            else
            {
                wrapExpression = "DynamicApiGeneratedRuntime.WrapResult(ctx.Output)";
            }

            sb.AppendLine($"        CapabilityEndpointResultContractRegistration.Register(");
            sb.AppendLine($"            \"{Escape(action.EndpointId)}\",");
            sb.AppendLine("            1,");
            sb.AppendLine($"            ctx => {wrapExpression});");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
