using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AppServiceCompatibilityGenerator;

/// <summary>
/// Emits CapabilityEndpointDescriptor providers, per-action input envelopes,
/// binding delegates, and CapabilityEndpointBindingRegistry registration
/// for a single projected CrestService.
///
/// Produces two source files per service:
///   1. GeneratedAppServiceCompatibilityEndpoints_{name}.g.cs
///       — ICapabilityEndpointDescriptorProvider implementation
///   2. GeneratedAppServiceCompatibilityBindings_{name}.g.cs
///       — input envelopes + bind delegates + binding registration
///
/// All generated code is AoT-safe: typed parse calls per parameter (no reflection).
/// Body binding uses CapabilityEndpointBodyReader with CapabilityEndpointJsonTypeInfoResolver.
/// P0-1 NOTE: JsonSerializerContext generation was removed because Roslyn SGs
/// cannot see each other's output. Use the generic ReadBodyAsync&lt;T&gt; overload instead.
/// When STJ adds a companion incremental generator for JsonSerializerContext, we can
/// restore the type-safe JsonTypeInfo path.
/// </summary>
internal static class AppServiceCompatibilityEndpointEmitter
{
    public static (string EndpointsSource, string BindingsSource) Emit(CompatibilityServiceModel service)
    {
        return (EmitEndpoints(service), EmitBindings(service));
    }

    private static string EmitEndpoints(CompatibilityServiceModel service)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using CrestCreates.DynamicApi;");
        sb.AppendLine("using CrestCreates.Metadata;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();

        sb.AppendLine($"internal sealed class GeneratedAppServiceCompatibilityEndpoints_{service.SanitizedIdentifier} : ICapabilityEndpointDescriptorProvider");
        sb.AppendLine("{");
        sb.AppendLine("    public IReadOnlyList<CapabilityEndpointDescriptor> GetDescriptors()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new CapabilityEndpointDescriptor[]");
        sb.AppendLine("        {");

        foreach (var action in service.Actions)
        {
            var httpMethodEnum = MapHttpMethodEnum(action.HttpMethod);
            var successStatusCode = MapSuccessStatusCode(action.HttpMethod);
            var operationId = action.CapabilityId.Replace('.', '_');

            sb.AppendLine("            new CapabilityEndpointDescriptor");
            sb.AppendLine("            {");
            sb.AppendLine($"                Id = \"{Escape(action.EndpointId)}\",");
            sb.AppendLine($"                Name = \"{Escape(action.ActionName)}\",");
            sb.AppendLine("                Version = 1,");
            sb.AppendLine("                State = DescriptorState.Active,");
            sb.AppendLine($"                Capability = new VersionedDescriptorRef<CapabilityDescriptor>(\"{Escape(action.CapabilityId)}\", 1),");
            sb.AppendLine($"                HttpMethod = {httpMethodEnum},");
            sb.AppendLine($"                RoutePattern = \"{Escape(action.RoutePattern)}\",");
            sb.AppendLine("                AuthorizationMode = CapabilityEndpointAuthorizationMode.InheritCapability,");
            sb.AppendLine("                InputBindings = new CapabilityEndpointInputBinding[]");
            sb.AppendLine("                {");
            EmitInputBindings(sb, action);
            sb.AppendLine("                },");
            sb.AppendLine($"                OutputMapping = new CapabilityEndpointOutputMapping {{ SuccessStatusCode = {successStatusCode} }},");
            sb.AppendLine("                Projection = new CapabilityEndpointProjectionMetadata");
            sb.AppendLine("                {");
            sb.AppendLine($"                    OperationId = \"{Escape(operationId)}\",");
            sb.AppendLine($"                    Tags = new[] {{ \"{Escape(service.ServiceName)}\" }}");
            sb.AppendLine("                }");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Bootstrapper
        sb.AppendLine($"internal static class GeneratedAppServiceCompatibilityEndpointsBootstrapper_{service.SanitizedIdentifier}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine($"        DescriptorProviderRegistry.Register<CapabilityEndpointDescriptor>(new GeneratedAppServiceCompatibilityEndpoints_{service.SanitizedIdentifier}());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitInputBindings(StringBuilder sb, CompatibilityActionModel action)
    {
        foreach (var param in action.Parameters)
        {
            if (param.Source == "CancellationToken") continue;

            var sourceEnum = param.Source switch
            {
                "Route" => "CapabilityEndpointParameterSource.Route",
                "Query" => "CapabilityEndpointParameterSource.Query",
                "Body" => "CapabilityEndpointParameterSource.Body",
                "Header" => "CapabilityEndpointParameterSource.Header",
                _ => "CapabilityEndpointParameterSource.Query"
            };

            sb.AppendLine($"                    new CapabilityEndpointInputBinding");
            sb.AppendLine("                    {");
            sb.AppendLine($"                        Name = \"{Escape(param.Name)}\",");
            sb.AppendLine($"                        Source = {sourceEnum},");
            sb.AppendLine($"                        Required = {(!param.IsOptional).ToString().ToLowerInvariant()}");
            sb.AppendLine("                    },");
        }
    }

    private static string EmitBindings(CompatibilityServiceModel service)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using CrestCreates.DynamicApi;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();

        // Envelope types for multi-parameter methods (must have a non-null EnvelopeTypeName)
        foreach (var action in service.Actions.Where(a => a.EnvelopeTypeName is not null))
        {
            sb.AppendLine($"internal sealed class {action.EnvelopeTypeName}");
            sb.AppendLine("{");
            foreach (var param in action.Parameters)
            {
                if (param.Source == "CancellationToken") continue;
                var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                sb.AppendLine($"    public {param.TypeName} {propertyName} {{ get; init; }} = default!;");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Binding registration class
        sb.AppendLine($"internal static class GeneratedAppServiceCompatibilityBindings_{service.SanitizedIdentifier}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var action in service.Actions)
        {
            sb.AppendLine($"        CapabilityEndpointBindingRegistry.Register(new CapabilityEndpointBindingContract(");
            sb.AppendLine($"            \"{Escape(action.EndpointId)}\",");
            sb.AppendLine("            1,");
            sb.AppendLine($"            Bind_{SanitizeMethodName(action.ActionName)}_Async));");
        }

        // Register body types for AOT JSON contract validation
        foreach (var action in service.Actions)
        {
            var bodyParam = action.Parameters.FirstOrDefault(p => p.Source == "Body");
            if (bodyParam is not null)
            {
                // Strip nullable reference type suffix — typeof(T?) is illegal for reference types
                var typeofName = bodyParam.TypeName.EndsWith("?")
                    ? bodyParam.TypeName.Substring(0, bodyParam.TypeName.Length - 1)
                    : bodyParam.TypeName;
                sb.AppendLine($"        CapabilityEndpointJsonContractRegistry.RegisterBodyType(typeof({typeofName}));");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Binding delegate methods
        foreach (var action in service.Actions)
        {
            var methodName = $"Bind_{SanitizeMethodName(action.ActionName)}_Async";
            EmitBindingMethod(sb, action, methodName);
        }

        // Typed parse helpers — AoT-safe, no reflection
        EmitTypedParseHelpers(sb, service);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitBindingMethod(StringBuilder sb,
        CompatibilityActionModel action, string methodName)
    {
        // Reserve all parameter local variable names to avoid collision with generated out-var names
        var reservedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var param in action.Parameters)
        {
            if (param.Source == "CancellationToken") continue;
            var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
            reservedNames.Add(Camelize(propertyName));
        }
        // "body" is also a reserved local variable name
        reservedNames.Add("body");
        reservedNames.Add("input");

        // Monotonic counter for query value out-var names — skips reserved names
        int qvIndex = 0;
        string NextQvVar()
        {
            while (true)
            {
                var candidate = $"qv{qvIndex++}";
                if (!reservedNames.Contains(candidate))
                    return candidate;
            }
        }

        sb.AppendLine($"    private static async ValueTask<object?> {methodName}(HttpContext context, CancellationToken ct)");
        sb.AppendLine("    {");

        var bodyParam = action.Parameters.FirstOrDefault(p => p.Source == "Body");
        var routeParams = action.Parameters.Where(p => p.Source == "Route").ToArray();
        var queryParams = action.Parameters.Where(p => p.Source == "Query").ToArray();
        var headerParams = action.Parameters.Where(p => p.Source == "Header").ToArray();

        if (action.IsSingleParam && bodyParam is not null)
        {
            // Single body parameter — use CapabilityEndpointBodyReader with
            // emptyBodyFactory for legacy-compatible body behavior (empty body → new T()).
            var bodyOptional = bodyParam.IsOptional.ToString().ToLowerInvariant();
            var emptyFactory = GetEmptyBodyFactoryExpr(bodyParam.TypeName);
            sb.AppendLine($"        var jsonTypeInfo = CapabilityEndpointJsonTypeInfoResolver.Resolve<{bodyParam.TypeName}>(context)");
            sb.AppendLine($"            ?? throw new InvalidOperationException(");
            sb.AppendLine($"                \"No JsonTypeInfo registered for {bodyParam.TypeName}. Add [JsonSerializable(typeof({bodyParam.TypeName}))] to your JsonSerializerContext.\");");
            sb.AppendLine($"        return await CapabilityEndpointBodyReader.ReadBodyAsync<{bodyParam.TypeName}>(");
            sb.AppendLine($"            context, jsonTypeInfo, {emptyFactory}, {bodyOptional});");
        }
        else if (bodyParam is not null && (routeParams.Length > 0 || queryParams.Length > 0 || headerParams.Length > 0))
        {
            // Body + route/query/header params
            var bodyOptional = bodyParam.IsOptional.ToString().ToLowerInvariant();
            var emptyFactory = GetEmptyBodyFactoryExpr(bodyParam.TypeName);
            sb.AppendLine($"        var jsonTypeInfo = CapabilityEndpointJsonTypeInfoResolver.Resolve<{bodyParam.TypeName}>(context)");
            sb.AppendLine($"            ?? throw new InvalidOperationException(");
            sb.AppendLine($"                \"No JsonTypeInfo registered for {bodyParam.TypeName}. Add [JsonSerializable(typeof({bodyParam.TypeName}))] to your JsonSerializerContext.\");");
            sb.AppendLine($"        var body = await CapabilityEndpointBodyReader.ReadBodyAsync<{bodyParam.TypeName}>(");
            sb.AppendLine($"            context, jsonTypeInfo, {emptyFactory}, {bodyOptional});");
            sb.AppendLine();

            // Two-phase: pre-declare query locals outside initializer, then construct envelope
            var bodyQueryParams = action.Parameters
                .Where(p => p.Source == "Query" && (p.IsQueryObject || p.IsOptional))
                .ToList();

            if (bodyQueryParams.Count > 0)
            {
                // Phase 1: declare locals for query objects and optional scalars
                foreach (var param in bodyQueryParams)
                {
                    var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                    var localVarName = Camelize(propertyName);

                    if (param.IsQueryObject)
                    {
                        sb.AppendLine($"        var {localVarName} = new {param.TypeName}();");
                        foreach (var qp in param.QueryProperties)
                        {
                            var valueVar = NextQvVar();
                            var parseExpr = GetTypedParseExpression(qp.TypeName, valueVar);
                            sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(qp.Name)}\", out var {valueVar}))");
                            sb.AppendLine($"            {localVarName}.{qp.Name} = {parseExpr};");
                        }
                    }
                    else
                    {
                        var valueVar = NextQvVar();
                        var parseExpr = GetTypedParseExpression(param.TypeName, valueVar);
                        sb.AppendLine($"        var {localVarName} = default({param.TypeName});");
                        sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(param.Name)}\", out var {valueVar}))");
                        sb.AppendLine($"            {localVarName} = {parseExpr};");
                    }
                }

                // Phase 2: construct envelope referencing pre-declared locals
                sb.AppendLine($"        return new {action.EnvelopeTypeName}");
                sb.AppendLine("        {");
                foreach (var param in action.Parameters)
                {
                    if (param.Source == "CancellationToken") continue;
                    var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                    var localVarName = Camelize(propertyName);

                    if (param.Source == "Body")
                    {
                        sb.AppendLine($"            {propertyName} = body,");
                    }
                    else if (param.Source == "Route")
                    {
                        sb.AppendLine($"            {propertyName} = {GenerateTypedParseCall("Route", param.Name, param.TypeName)},");
                    }
                    else if (param.Source == "Query" && (param.IsQueryObject || param.IsOptional))
                    {
                        sb.AppendLine($"            {propertyName} = {localVarName},");
                    }
                    else if (param.Source == "Query")
                    {
                        var sanitizeSuffix = SanitizeTypeName(param.TypeName);
                        sb.AppendLine($"            {propertyName} = ParseQueryValue_{sanitizeSuffix}(context, \"{Escape(param.Name)}\"),");
                    }
                    else if (param.Source == "Header")
                    {
                        var httpHeaderName = param.HeaderName ?? param.Name;
                        var trimQuotes = param.Name == "expectedStamp";
                        sb.AppendLine(trimQuotes
                            ? $"            {propertyName} = context.Request.Headers[\"{Escape(httpHeaderName)}\"].FirstOrDefault()?.Trim('\"'),"
                            : $"            {propertyName} = GenerateHeaderBinding(\"{Escape(httpHeaderName)}\", context),");
                    }
                }
                sb.AppendLine("        };");
            }
            else
            {
                // All non-body params are route/required-query/header — simple initializer
                sb.AppendLine($"        return new {action.EnvelopeTypeName}");
                sb.AppendLine("        {");
                foreach (var param in action.Parameters)
                {
                    if (param.Source == "CancellationToken") continue;
                    var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);

                    if (param.Source == "Body")
                    {
                        sb.AppendLine($"            {propertyName} = body,");
                    }
                    else if (param.Source == "Route")
                    {
                        sb.AppendLine($"            {propertyName} = {GenerateTypedParseCall("Route", param.Name, param.TypeName)},");
                    }
                    else if (param.Source == "Query")
                    {
                        var sanitizeSuffix = SanitizeTypeName(param.TypeName);
                        sb.AppendLine($"            {propertyName} = ParseQueryValue_{sanitizeSuffix}(context, \"{Escape(param.Name)}\"),");
                    }
                    else if (param.Source == "Header")
                    {
                        var httpHeaderName = param.HeaderName ?? param.Name;
                        var trimQuotes = param.Name == "expectedStamp";
                        sb.AppendLine(trimQuotes
                            ? $"            {propertyName} = context.Request.Headers[\"{Escape(httpHeaderName)}\"].FirstOrDefault()?.Trim('\"'),"
                            : $"            {propertyName} = GenerateHeaderBinding(\"{Escape(httpHeaderName)}\", context),");
                    }
                }
                sb.AppendLine("        };");
            }
        }
        else if (routeParams.Length > 0 || queryParams.Length > 0 || headerParams.Length > 0)
        {
            // Only route/query/header params (no body)
            var nonCancellationParams = action.Parameters.Where(p => p.Source != "CancellationToken").ToArray();
            if (nonCancellationParams.Length == 1)
            {
                // Single scalar — typed parse and return directly
                var single = nonCancellationParams[0];
                if (single.IsQueryObject)
                {
                    // Single query object — construct with defaults, then assign only present query values
                    // This preserves DTO default values (e.g., PageSize = 10) when query string omits them
                    sb.AppendLine($"        var input = new {single.TypeName}();");
                    foreach (var qp in single.QueryProperties)
                    {
                        var valueVar = NextQvVar();
                        var parseExpr = GetTypedParseExpression(qp.TypeName, valueVar);
                        sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(qp.Name)}\", out var {valueVar}))");
                        sb.AppendLine($"            input.{qp.Name} = {parseExpr};");
                    }
                    sb.AppendLine("        return input;");
                }
                else
                {
                    // Single scalar param — route/header always required, query may be optional
                    if (single.Source == "Query" && single.IsOptional)
                    {
                        var valueVar = NextQvVar();
                        var parseExpr = GetTypedParseExpression(single.TypeName, valueVar);
                        sb.AppendLine($"        {single.TypeName} {single.Name} = default({single.TypeName});");
                        sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(single.Name)}\", out var {valueVar}))");
                        sb.AppendLine($"            {single.Name} = {parseExpr};");
                        sb.AppendLine($"        return {single.Name};");
                    }
                    else
                    {
                        sb.AppendLine($"        return {GenerateTypedParseCall(single.Source, single.Name, single.TypeName, single.HeaderName)};");
                    }
                }
            }
            else
            {
                // Multi-param no body — two-phase generation:
                // Phase 1: declare local variables outside object initializer (query objects + optional scalars need if-statements)
                // Phase 2: construct envelope referencing those locals
                var needsPreDeclaration = action.Parameters
                    .Where(p => p.Source != "CancellationToken")
                    .Any(p => p.Source == "Query" && (p.IsQueryObject || p.IsOptional));

                if (needsPreDeclaration)
                {
                    // Phase 1: declare locals for query objects and optional scalars
                    foreach (var param in action.Parameters)
                    {
                        if (param.Source == "CancellationToken") continue;
                        var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                        var localVarName = Camelize(propertyName);

                        if (param.Source == "Query" && param.IsQueryObject)
                        {
                            sb.AppendLine($"        var {localVarName} = new {param.TypeName}();");
                            foreach (var qp in param.QueryProperties)
                            {
                                var valueVar = NextQvVar();
                                var parseExpr = GetTypedParseExpression(qp.TypeName, valueVar);
                                sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(qp.Name)}\", out var {valueVar}))");
                                sb.AppendLine($"            {localVarName}.{qp.Name} = {parseExpr};");
                            }
                        }
                        else if (param.Source == "Query" && param.IsOptional)
                        {
                            var valueVar = NextQvVar();
                            var parseExpr = GetTypedParseExpression(param.TypeName, valueVar);
                            sb.AppendLine($"        var {localVarName} = default({param.TypeName});");
                            sb.AppendLine($"        if (TryGetQueryString(context, \"{Escape(param.Name)}\", out var {valueVar}))");
                            sb.AppendLine($"            {localVarName} = {parseExpr};");
                        }
                    }

                    // Phase 2: construct envelope referencing pre-declared locals
                    sb.AppendLine($"        return new {action.EnvelopeTypeName}");
                    sb.AppendLine("        {");
                    foreach (var param in action.Parameters)
                    {
                        if (param.Source == "CancellationToken") continue;
                        var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                        var localVarName = Camelize(propertyName);

                        if (param.Source == "Route")
                        {
                            sb.AppendLine($"            {propertyName} = {GenerateTypedParseCall("Route", param.Name, param.TypeName)},");
                        }
                        else if (param.Source == "Query" && (param.IsQueryObject || param.IsOptional))
                        {
                            sb.AppendLine($"            {propertyName} = {localVarName},");
                        }
                        else if (param.Source == "Query")
                        {
                            // Required scalar query — can use ParseQueryValue directly in initializer
                            var sanitizeSuffix = SanitizeTypeName(param.TypeName);
                            sb.AppendLine($"            {propertyName} = ParseQueryValue_{sanitizeSuffix}(context, \"{Escape(param.Name)}\"),");
                        }
                        else if (param.Source == "Header")
                        {
                            var httpHeaderName = param.HeaderName ?? param.Name;
                            var trimQuotes = param.Name == "expectedStamp";
                            sb.AppendLine(trimQuotes
                                ? $"            {propertyName} = context.Request.Headers[\"{Escape(httpHeaderName)}\"].FirstOrDefault()?.Trim('\"'),"
                                : $"            {propertyName} = GenerateHeaderBinding(\"{Escape(httpHeaderName)}\", context),");
                        }
                    }
                    sb.AppendLine("        };");
                }
                else
                {
                    // All params are route/required-query/header — can use simple initializer
                    sb.AppendLine($"        return new {action.EnvelopeTypeName}");
                    sb.AppendLine("        {");
                    foreach (var param in action.Parameters)
                    {
                        if (param.Source == "CancellationToken") continue;
                        var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);

                        if (param.Source == "Route")
                        {
                            sb.AppendLine($"            {propertyName} = {GenerateTypedParseCall("Route", param.Name, param.TypeName)},");
                        }
                        else if (param.Source == "Query")
                        {
                            var sanitizeSuffix = SanitizeTypeName(param.TypeName);
                            sb.AppendLine($"            {propertyName} = ParseQueryValue_{sanitizeSuffix}(context, \"{Escape(param.Name)}\"),");
                        }
                        else if (param.Source == "Header")
                        {
                            var httpHeaderName = param.HeaderName ?? param.Name;
                            var trimQuotes = param.Name == "expectedStamp";
                            sb.AppendLine(trimQuotes
                                ? $"            {propertyName} = context.Request.Headers[\"{Escape(httpHeaderName)}\"].FirstOrDefault()?.Trim('\"'),"
                                : $"            {propertyName} = GenerateHeaderBinding(\"{Escape(httpHeaderName)}\", context),");
                        }
                    }
                    sb.AppendLine("        };");
                }
            }
        }
        else
        {
            // No inputs — return null for no-parameter methods
            sb.AppendLine("        return null;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Returns the emptyBodyFactory expression for a body type.
    /// Arrays use Array.Empty&lt;T&gt;(), other types use new T().
    /// Nullable reference types (e.g., CreateBookDto?) strip the ? suffix
    /// since <c>new T?()</c> is not valid C# — the factory creates a non-null instance.
    /// </summary>
    private static string GetEmptyBodyFactoryExpr(string typeName)
    {
        // Strip nullable reference type suffix — new T?() is illegal C#
        var cleanType = typeName.EndsWith("?")
            ? typeName.Substring(0, typeName.Length - 1)
            : typeName;

        if (cleanType.EndsWith("[]"))
        {
            var elementType = cleanType.Substring(0, cleanType.Length - 2);
            return $"static () => System.Array.Empty<{elementType}>()";
        }
        return $"static () => new {cleanType}()";
    }

    /// <summary>
    /// Generates a typed parse call for a route/query parameter.
    /// AoT-safe: each type gets a direct parse method call, no reflection.
    /// </summary>
    private static string GenerateTypedParseCall(string source, string paramName, string typeName, string? headerName = null)
    {
        var extractValue = source == "Route"
            ? $"ParseRouteValue_{SanitizeTypeName(typeName)}(context, \"{Escape(paramName)}\")"
            : source == "Header"
                ? (paramName == "expectedStamp"
                    ? $"context.Request.Headers[\"{Escape(headerName ?? paramName)}\"].FirstOrDefault()?.Trim('\"')"
                    : $"GenerateHeaderBinding(\"{Escape(headerName ?? paramName)}\", context)")
                : $"ParseQueryValue_{SanitizeTypeName(typeName)}(context, \"{Escape(paramName)}\")";
        return extractValue;
    }

    /// <summary>
    /// Emits typed parse helper methods — one pair (Route + Query) per distinct scalar type.
    /// AoT-safe: no Type.GetType, no Enum.Parse(Type, ...), no runtime type dispatch.
    /// </summary>
    private static void EmitTypedParseHelpers(StringBuilder sb, CompatibilityServiceModel service)
    {
        // Collect all distinct scalar parameter types (route + query only, not query objects)
        var scalarTypes = service.Actions
            .SelectMany(a => a.Parameters)
            .Where(p => p.Source is "Route" or "Query" && !p.IsQueryObject)
            .Select(p => p.TypeName)
            .Distinct()
            .ToArray();

        // Also collect scalar property types from query objects
        var queryPropTypes = service.Actions
            .SelectMany(a => a.Parameters)
            .Where(p => p.IsQueryObject)
            .SelectMany(p => p.QueryProperties)
            .Select(qp => qp.TypeName)
            .Distinct()
            .ToArray();

        var allScalarTypes = scalarTypes.Concat(queryPropTypes).Distinct().ToArray();

        // Check if any action has header parameters (excluding expectedStamp which uses inline binding)
        var hasNonExpectedStampHeaders = service.Actions
            .SelectMany(a => a.Parameters)
            .Any(p => p.Source == "Header" && p.Name != "expectedStamp");

        if (allScalarTypes.Length == 0 && !hasNonExpectedStampHeaders) return;

        sb.AppendLine("    // Typed parse helpers — AoT-safe, no reflection");
        sb.AppendLine();

        // Emit TryGetQueryString helper (always needed for query object optional property binding)
        var hasQueryParams = service.Actions
            .SelectMany(a => a.Parameters)
            .Any(p => p.Source == "Query");
        if (hasQueryParams)
        {
            sb.AppendLine("    private static bool TryGetQueryString(HttpContext context, string key, out string? value)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (context.Request.Query.TryGetValue(key, out var values) && values.Count > 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            var str = values.ToString();");
            sb.AppendLine("            if (!string.IsNullOrWhiteSpace(str))");
            sb.AppendLine("            {");
            sb.AppendLine("                value = str;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        value = null;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Emit header binding helper (once) — only if there are non-expectedStamp header params
        if (hasNonExpectedStampHeaders)
        {
            sb.AppendLine("    private static string? GenerateHeaderBinding(string headerName, HttpContext context)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (context.Request.Headers.TryGetValue(headerName, out var values) && values.Count > 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            return values.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine("        return null;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var typeName in allScalarTypes)
        {
            var sanitizeSuffix = SanitizeTypeName(typeName);
            var parseExpr = GetTypedParseExpression(typeName, "str");

            // Route value parser (always required — route matching guarantees presence)
            sb.AppendLine($"    private static {typeName} ParseRouteValue_{sanitizeSuffix}(HttpContext context, string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (context.Request.RouteValues.TryGetValue(key, out var value) && value is not null)");
            sb.AppendLine("        {");
            sb.AppendLine("            var str = value.ToString() ?? string.Empty;");
            sb.AppendLine($"            return {parseExpr};");
            sb.AppendLine("        }");
            sb.AppendLine("        throw new InvalidOperationException($\"Required route value '{key}' is missing.\");");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Query value parser — required (missing/blank → throws)
            sb.AppendLine($"    private static {typeName} ParseQueryValue_{sanitizeSuffix}(HttpContext context, string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (context.Request.Query.TryGetValue(key, out var values) && values.Count > 0)");
            sb.AppendLine("        {");
            sb.AppendLine("            var str = values.ToString();");
            sb.AppendLine("            if (!string.IsNullOrWhiteSpace(str))");
            sb.AppendLine("            {");
            sb.AppendLine($"                return {parseExpr};");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        throw new InvalidOperationException($\"Required query parameter '{key}' is missing.\");");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Returns a typed parse expression for a given type name.
    /// AoT-safe: all types resolved at compile time, no reflection.
    /// </summary>
    private static string GetTypedParseExpression(string typeName, string valueVar)
    {
        // Strip nullable suffix for matching
        var coreType = typeName.EndsWith("?") ? typeName.Substring(0, typeName.Length - 1) : typeName;
        var shortName = ExtractShortName(coreType);

        return shortName switch
        {
            "String" => valueVar,
            "Boolean" => $"bool.Parse({valueVar})",
            "Guid" => $"Guid.Parse({valueVar})",
            // Numeric types use InvariantCulture — matches legacy DynamicApiAotSourceGenerator
            "Int32" => $"int.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Int64" => $"long.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Int16" => $"short.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "UInt16" => $"ushort.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "UInt32" => $"uint.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "UInt64" => $"ulong.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Byte" => $"byte.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "SByte" => $"sbyte.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Double" => $"double.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Single" => $"float.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "Decimal" => $"decimal.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "DateTime" => $"DateTime.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "DateTimeOffset" => $"DateTimeOffset.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            "TimeSpan" => $"TimeSpan.Parse({valueVar}, System.Globalization.CultureInfo.InvariantCulture)",
            // Enums: ignoreCase matches legacy DynamicApiAotSourceGenerator
            _ when IsLikelyEnum(coreType) => $"({coreType})Enum.Parse(typeof({coreType}), {valueVar}, true)",
            // Non-scalar, non-enum types should not reach here;
            // they are handled as query objects via IsQueryObject expansion.
            _ => $"throw new System.NotSupportedException(\"Parameter type '{coreType}' is not a supported scalar and has no known parse method. Consider using a query object DTO.\")",
        };
    }

    private static bool IsLikelyEnum(string typeName)
    {
        // Simple heuristic: user-defined types with dots are likely enums
        // if they don't match known framework types.
        var shortName = ExtractShortName(typeName);
        return shortName switch
        {
            "String" or "Int32" or "Int64" or "Int16" or "UInt16" or "UInt32" or "UInt64"
                or "Byte" or "SByte" or "Boolean" or "Double" or "Single" or "Decimal"
                or "Guid" or "DateTime" or "DateTimeOffset" or "TimeSpan" => false,
            _ => typeName.Contains("."),
        };
    }

    private static string ExtractShortName(string fullyQualifiedName)
    {
        var lastDot = fullyQualifiedName.LastIndexOf('.');
        if (lastDot >= 0 && lastDot < fullyQualifiedName.Length - 1)
            return fullyQualifiedName.Substring(lastDot + 1);
        return fullyQualifiedName;
    }

    private static string SanitizeTypeName(string typeName)
    {
        // Strip nullable, remove global:: prefix, then replace dots/brackets for valid C# identifier
        var core = typeName.EndsWith("?") ? typeName.Substring(0, typeName.Length - 1) : typeName;
        if (core.StartsWith("global::")) core = core.Substring(8);
        return core.Replace(".", "_").Replace("[", "_").Replace("]", "_").Replace("+", "_");
    }

    private static string MapHttpMethodEnum(string httpMethod) => httpMethod switch
    {
        "GET" => "CapabilityEndpointHttpMethod.Get",
        "POST" => "CapabilityEndpointHttpMethod.Post",
        "PUT" => "CapabilityEndpointHttpMethod.Put",
        "PATCH" => "CapabilityEndpointHttpMethod.Patch",
        "DELETE" => "CapabilityEndpointHttpMethod.Delete",
        _ => "CapabilityEndpointHttpMethod.None"
    };

    private static string MapSuccessStatusCode(string httpMethod) => httpMethod switch
    {
        "POST" => "201",
        "DELETE" => "204",
        _ => "200"
    };

    private static string CapitalizeFirst(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private static string Camelize(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    private static string SanitizeMethodName(string name)
        => System.Text.RegularExpressions.Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
