using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AppServiceCompatibilityGenerator;

/// <summary>
/// Emits ICapabilityContextAwareHandlerInvoker implementations that resolve
/// the original CrestService via DI (context.ServiceProvider) and delegate
/// the call through to the AppService method.
///
/// Registration uses CapabilityHandlerResolverProvider.Register() for
/// additive (non-overwriting) handler registration.
/// </summary>
internal static class AppServiceCompatibilityInvokerEmitter
{
    public static string Emit(CompatibilityServiceModel service)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CrestCreates.Capability.Abstractions;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Generated;");
        sb.AppendLine();

        // Generate one invoker class per action
        foreach (var action in service.Actions)
        {
            var invokerClassName = $"{service.ServiceName}_{action.ActionName}_CompatibilityInvoker";

            sb.AppendLine($"internal sealed class {invokerClassName} : ICapabilityContextAwareHandlerInvoker");
            sb.AppendLine("{");
            sb.AppendLine("    public async Task<object?> InvokeAsync(CapabilityExecutionContext context, CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var service = context.ServiceProvider.GetRequiredService<{service.InterfaceTypeName}>();");

            // Build argument suffix: append ct only if original method declares CancellationToken
            var ctSuffix = action.HasCancellationToken ? "ct" : string.Empty;

            if (action.IsSingleParam)
            {
                // Single Body parameter: cast input directly
                sb.AppendLine($"        var typedInput = ({action.InputTypeName})context.Input!;");
                var methodArgs = action.HasCancellationToken ? "typedInput, ct" : "typedInput";
                sb.AppendLine($"        {(action.IsVoidReturn ? "" : "var result = ")}await service.{action.ServiceMethodName}({methodArgs}).ConfigureAwait(false);");
            }
            else if (action.IsSingleScalarParam)
            {
                // Single Route/Query/Header parameter: cast input directly to scalar type
                var singleScalar = action.Parameters.First(p => p.Source != "CancellationToken");
                sb.AppendLine($"        var typedInput = ({singleScalar.TypeName})context.Input!;");
                var methodArgs = action.HasCancellationToken ? "typedInput, ct" : "typedInput";
                sb.AppendLine($"        {(action.IsVoidReturn ? "" : "var result = ")}await service.{action.ServiceMethodName}({methodArgs}).ConfigureAwait(false);");
            }
            else if (action.Parameters.All(p => p.Source == "CancellationToken"))
            {
                // No input parameters — call directly (only ct if declared)
                var methodArgs = action.HasCancellationToken ? "ct" : string.Empty;
                sb.AppendLine($"        {(action.IsVoidReturn ? "" : "var result = ")}await service.{action.ServiceMethodName}({methodArgs}).ConfigureAwait(false);");
            }
            else
            {
                // Multi-parameter: cast input to envelope, unpack fields
                sb.AppendLine($"        var envelope = ({action.EnvelopeTypeName})context.Input!;");

                // Build argument list from envelope fields and optional cancellation token
                var nonCancellationParams = action.Parameters
                    .Where(p => p.Source != "CancellationToken")
                    .ToArray();

                if (nonCancellationParams.Length > 0)
                {
                    var args = new System.Collections.Generic.List<string>();
                    foreach (var param in nonCancellationParams)
                    {
                        var propertyName = param.PascalName ?? CapitalizeFirst(param.Name);
                        args.Add($"envelope.{propertyName}");
                    }
                    if (action.HasCancellationToken) args.Add("ct");

                    sb.AppendLine($"        {(action.IsVoidReturn ? "" : "var result = ")}await service.{action.ServiceMethodName}({string.Join(", ", args)}).ConfigureAwait(false);");
                }
                else
                {
                    var methodArgs = action.HasCancellationToken ? "ct" : string.Empty;
                    sb.AppendLine($"        {(action.IsVoidReturn ? "" : "var result = ")}await service.{action.ServiceMethodName}({methodArgs}).ConfigureAwait(false);");
                }
            }

            if (action.IsVoidReturn)
            {
                sb.AppendLine("        return null;");
            }
            else
            {
                sb.AppendLine("        return result;");
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public Task<object?> InvokeAsync(object? input, CancellationToken ct)");
            sb.AppendLine("        => throw new InvalidOperationException(");
            sb.AppendLine("            \"Compatibility invoker requires CapabilityExecutionContext. \" +");
            sb.AppendLine("            \"Use the ICapabilityContextAwareHandlerInvoker overload.\");");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // ModuleInitializer for registration
        sb.AppendLine($"internal static class GeneratedAppServiceCompatibilityInvokersBootstrapper_{service.SanitizedIdentifier}");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");

        foreach (var action in service.Actions)
        {
            var invokerClassName = $"{service.ServiceName}_{action.ActionName}_CompatibilityInvoker";
            sb.AppendLine($"        CapabilityHandlerResolverProvider.Register(\"{Escape(action.CapabilityId)}\", new {invokerClassName}());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CapitalizeFirst(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        return char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
