using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AgentDraftContractGenerator;

internal sealed class AgentDraftContractProjectionWriter
{
    public string Write(ContractModel model)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);

        WriteFromDomain(sb, model);
        WriteCreate(sb, model);
        WriteMerge(sb, model);
        WriteTryValidatePayload(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ──────────────────────────────────────────────────────────────
    //  Header
    // ──────────────────────────────────────────────────────────────

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using CrestCreates.Metadata;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine("using CrestCreates.DescriptorDraft.Abstractions;");
        sb.AppendLine("using CrestCreates.Agent.DraftContracts.Dto;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Agent.DraftContracts.Projection;");
        sb.AppendLine();
        sb.AppendLine("public static class AgentDraftPayloadProjection");
        sb.AppendLine("{");
    }

    // ──────────────────────────────────────────────────────────────
    //  FromDomain
    // ──────────────────────────────────────────────────────────────

    private void WriteFromDomain(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    // ── FromDomain ──");
        sb.AppendLine();
        WriteFromDomainMain(sb, model);
        foreach (var kind in model.Kinds)
            WriteFromDomainKind(sb, kind);
    }

    private static void WriteFromDomainMain(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static AgentDraftContractResult<AgentDraftPayloadDto> FromDomain(DescriptorDraftPayload payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (payload is null)");
        sb.AppendLine("            return AgentDraftContractResult<AgentDraftPayloadDto>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.NullPayload, Message = \"Payload is null.\" });");
        sb.AppendLine();
        sb.AppendLine("        return payload switch");
        sb.AppendLine("        {");

        foreach (var kind in model.Kinds)
        {
            var payloadTypeName = $"{kind.KindName}DescriptorDraftPayload";
            sb.AppendLine($"            {payloadTypeName} p => FromDomain_{kind.KindName}(p),");
        }

        sb.AppendLine("            _ => AgentDraftContractResult<AgentDraftPayloadDto>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.UnsupportedKind, Message = \"Unsupported payload type: \" + payload.GetType().Name + \".\" }),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void WriteFromDomainKind(StringBuilder sb, ContractKindSpec kind)
    {
        var dtoName = $"Agent{kind.KindName}DraftPayloadDto";
        var payloadTypeName = $"{kind.KindName}DescriptorDraftPayload";

        sb.AppendLine($"    private static AgentDraftContractResult<AgentDraftPayloadDto> FromDomain_{kind.KindName}({payloadTypeName} payload)");
        sb.AppendLine("    {");
        sb.AppendLine("        var d = payload.Descriptor;");
        sb.AppendLine();

        // Editable fields only
        var editableFields = kind.Fields
            .Where(f => f.Classification == FieldClassification.EditableScalar
                     || f.Classification == FieldClassification.EditableReference)
            .OrderBy(f => f.ContractName, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine($"        var kindDto = new {dtoName}");
        sb.AppendLine("        {");

        foreach (var field in editableFields)
        {
            var expr = GetFromDomainExpression(field, "d");
            sb.AppendLine($"            {field.ContractName} = {expr},");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        return AgentDraftContractResult<AgentDraftPayloadDto>.Success(new AgentDraftPayloadDto");
        sb.AppendLine("        {");
        sb.AppendLine($"            Discriminator = DescriptorKind.{kind.KindName},");
        sb.AppendLine($"            {kind.KindName} = kindDto,");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetFromDomainExpression(ContractFieldSpec field, string descriptorVar)
    {
        var cat = CategorizeField(field);
        var access = $"{descriptorVar}.{field.PropertyName}";

        return cat switch
        {
            FieldCategory.StringToNullable or FieldCategory.IntToNullable
                or FieldCategory.BoolToNullable or FieldCategory.EnumToEnum
                or FieldCategory.FallbackNullable => access,

            FieldCategory.TimeSpanToString => $"{access}?.ToString()",

            FieldCategory.VersionedRefToRef =>
                field.IsNullable
                    ? $"{access}.HasValue ? new DescriptorRef({GetRefNamespace(field)}, {access}.Value.Id, {access}.Value.Version) : null"
                    : $"new DescriptorRef({GetRefNamespace(field)}, {access}.Id, {access}.Version)",

            FieldCategory.EventRefCollectionToRefArray => $"{access}?.Select(e => new DescriptorRef(e.Namespace, e.Id, e.Version)).ToArray()",

            _ => access,
        };
    }

    // ──────────────────────────────────────────────────────────────
    //  Create
    // ──────────────────────────────────────────────────────────────

    private void WriteCreate(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    // ── Create ──");
        sb.AppendLine();
        WriteCreateMain(sb, model);
        foreach (var kind in model.Kinds)
            WriteCreateKind(sb, kind);
    }

    private static void WriteCreateMain(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static AgentDraftContractResult<DescriptorDraftPayload> Create(AgentDraftPayloadDto dto)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (dto is null)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.NullPayload, Message = \"Payload is null.\" });");
        sb.AppendLine();
        sb.AppendLine("        var (isValid, error) = TryValidatePayload(dto);");
        sb.AppendLine("        if (!isValid)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(error!);");
        sb.AppendLine();
        sb.AppendLine("        return dto.Discriminator switch");
        sb.AppendLine("        {");

        foreach (var kind in model.Kinds)
        {
            sb.AppendLine($"            DescriptorKind.{kind.KindName} => Create_{kind.KindName}(dto.{kind.KindName}!),");
        }

        sb.AppendLine("            _ => AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.UnsupportedKind, Message = $\"Unsupported descriptor kind: {dto.Discriminator}.\" }),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void WriteCreateKind(StringBuilder sb, ContractKindSpec kind)
    {
        var dtoName = $"Agent{kind.KindName}DraftPayloadDto";
        var payloadTypeName = $"{kind.KindName}DescriptorDraftPayload";
        var descriptorTypeFqn = kind.DescriptorType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"    private static AgentDraftContractResult<DescriptorDraftPayload> Create_{kind.KindName}({dtoName} dto)");
        sb.AppendLine("    {");

        // Validate RequiredOnCreate
        var requiredFields = kind.Fields
            .Where(f => f.IsRequiredOnCreate)
            .ToList();

        foreach (var rf in requiredFields)
        {
            sb.AppendLine($"        if (dto.{rf.ContractName} is null)");
            sb.AppendLine($"            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError {{ Code = AgentDraftContractErrorCodes.MissingRequiredOnCreate, Message = \"Field '{rf.ContractName}' is required on create.\" }});");
        }

        if (requiredFields.Count > 0)
            sb.AppendLine();

        // Check for CreateUnsupported
        var unsupportedCreate = kind.Fields
            .Where(f => f.Classification == FieldClassification.Preserve
                     && f.PreserveCreateStrategy == PreserveStrategy.CreateUnsupported)
            .ToList();

        if (unsupportedCreate.Count > 0)
        {
            foreach (var uf in unsupportedCreate)
            {
                sb.AppendLine($"        // Field '{uf.PropertyName}' is CreateUnsupported: {uf.PreserveReason}");
            }
            sb.AppendLine($"        return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError {{ Code = AgentDraftContractErrorCodes.CreateUnsupported, Message = \"Creation of {kind.KindName} drafts is not supported because one or more required fields cannot be initialized through the agent contract.\" }});");
            sb.AppendLine("    }");
            sb.AppendLine();
            return;
        }

        sb.AppendLine($"        var descriptor = new {descriptorTypeFqn}");
        sb.AppendLine("        {");

        // Editable scalar + reference fields
        foreach (var field in kind.Fields)
        {
            if (field.Classification == FieldClassification.EditableScalar
                || field.Classification == FieldClassification.EditableReference)
            {
                var expr = GetCreateExpression(field, "dto");
                sb.AppendLine($"            {field.PropertyName} = {expr},");
            }
            else if (field.Classification == FieldClassification.Preserve)
            {
                var expr = GetPreserveCreateExpression(field);
                sb.AppendLine($"            {field.PropertyName} = {expr},");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"        var payload = new {payloadTypeName}(descriptor);");
        sb.AppendLine($"        return AgentDraftContractResult<DescriptorDraftPayload>.Success(payload);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetCreateExpression(ContractFieldSpec field, string dtoVar)
    {
        var cat = CategorizeField(field);
        var access = $"{dtoVar}.{field.ContractName}";

        return cat switch
        {
            FieldCategory.StringToNullable => $"{access} ?? string.Empty",

            FieldCategory.IntToNullable => $"{access} ?? 0",

            FieldCategory.BoolToNullable => $"{access} ?? false",

            FieldCategory.TimeSpanToString =>
                $"!string.IsNullOrEmpty({access}) && System.TimeSpan.TryParse({access}, out var ts_{EscapeVarName(field.PropertyName)}) ? ts_{EscapeVarName(field.PropertyName)} : null",

            FieldCategory.EnumToEnum =>
                field.IsNullable ? $"{access} ?? default" : access,

            FieldCategory.VersionedRefToRef =>
                $"{access}.HasValue ? new {GetVersionedRefTypeName(field)}({access}.Value.Id, {access}.Value.Version ?? 1) : {(field.IsNullable ? "null" : "default")}",

            FieldCategory.EventRefCollectionToRefArray =>
                $"({access} ?? Array.Empty<DescriptorRef>()).Select(r => new EventRef(r.Namespace, r.Id, r.Version)).ToArray()",

            FieldCategory.FallbackNullable =>
                field.IsNullable ? access : $"{access} ?? default!",

            _ => access,
        };
    }

    private static string GetPreserveCreateExpression(ContractFieldSpec field)
    {
        var strategy = field.PreserveCreateStrategy;
        var domainType = field.PropertyType;

        return strategy switch
        {
            PreserveStrategy.CreateDefault => GetDefaultExpression(domainType),
            PreserveStrategy.KnownDomainDefault => GetDefaultExpression(domainType),
            PreserveStrategy.CreateUnsupported => "default!",
            _ => GetDefaultExpression(domainType),
        };
    }

    private static string GetDefaultExpression(ITypeSymbol type)
    {
        // Unwrap Nullable<T>
        var underlying = type;
        if (type is INamedTypeSymbol nullableNamed
            && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && nullableNamed.TypeArguments.Length == 1)
        {
            underlying = nullableNamed.TypeArguments[0];
            return "null";
        }

        if (type.SpecialType == SpecialType.System_String || type.NullableAnnotation == NullableAnnotation.Annotated)
            return "default!";

        if (IsCollectionType(type))
            return $"System.Array.Empty<{GetElementTypeFqn(type)}>()";

        return "default";
    }

    // ──────────────────────────────────────────────────────────────
    //  Merge
    // ──────────────────────────────────────────────────────────────

    private void WriteMerge(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    // ── Merge ──");
        sb.AppendLine();
        WriteMergeMain(sb, model);
        foreach (var kind in model.Kinds)
            WriteMergeKind(sb, kind);
    }

    private static void WriteMergeMain(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static AgentDraftContractResult<DescriptorDraftPayload> Merge(AgentDraftPayloadPatchDto patch, DescriptorDraftPayload existing)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (patch is null)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.NullPayload, Message = \"Patch is null.\" });");
        sb.AppendLine("        if (existing is null)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.NullPayload, Message = \"Existing payload is null.\" });");
        sb.AppendLine();

        // Validate one-of on patch
        sb.AppendLine("        // Validate patch discriminator matches exactly one populated branch");
        sb.AppendLine("        int populated = 0;");

        foreach (var kind in model.Kinds)
            sb.AppendLine($"        if (patch.{kind.KindName} is not null) populated++;");

        sb.AppendLine("        if (populated == 0)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.DiscriminatorMismatch, Message = \"Patch discriminator is set but no matching payload branch is populated.\" });");
        sb.AppendLine("        if (populated > 1)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.DiscriminatorMismatch, Message = \"Multiple patch branches are populated. Only one is allowed.\" });");
        sb.AppendLine();

        sb.AppendLine("        return patch.Discriminator switch");
        sb.AppendLine("        {");

        foreach (var kind in model.Kinds)
        {
            var payloadTypeName = $"{kind.KindName}DescriptorDraftPayload";
            sb.AppendLine($"            DescriptorKind.{kind.KindName} => existing is {payloadTypeName} ep ? Merge_{kind.KindName}(patch.{kind.KindName}!, ep) : AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError {{ Code = AgentDraftContractErrorCodes.DiscriminatorMismatch, Message = \"Existing payload kind does not match patch discriminator.\" }}),");
        }

        sb.AppendLine("            _ => AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.UnsupportedKind, Message = $\"Unsupported descriptor kind: {patch.Discriminator}.\" }),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void WriteMergeKind(StringBuilder sb, ContractKindSpec kind)
    {
        var changedFieldEnum = $"Agent{kind.KindName}DraftChangedField";
        var descriptorTypeFqn = kind.DescriptorType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var payloadTypeName = $"{kind.KindName}DescriptorDraftPayload";
        var patchDtoName = $"Agent{kind.KindName}DraftPayloadPatchDto";

        sb.AppendLine($"    private static AgentDraftContractResult<DescriptorDraftPayload> Merge_{kind.KindName}({patchDtoName} patch, {payloadTypeName} existingPayload)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Validate ChangedFields is non-empty");
        sb.AppendLine($"        if (patch.ChangedFields == {changedFieldEnum}.None)");
        sb.AppendLine("            return AgentDraftContractResult<DescriptorDraftPayload>.Failure(new AgentDraftContractError { Code = AgentDraftContractErrorCodes.EmptyChangedFields, Message = \"ChangedFields is empty. At least one field must be specified for merge.\" });");
        sb.AppendLine();
        sb.AppendLine("        var cf = patch.ChangedFields;");
        sb.AppendLine("        var existing = existingPayload.Descriptor;");
        sb.AppendLine("        var dto = patch.Payload;");
        sb.AppendLine();

        sb.AppendLine($"        var merged = new {descriptorTypeFqn}");
        sb.AppendLine("        {");

        foreach (var field in kind.Fields)
        {
            if (field.Classification == FieldClassification.Preserve)
            {
                // Always copy from existing, regardless of ChangedFields
                sb.AppendLine($"            {field.PropertyName} = existing.{field.PropertyName},");
            }
            else if (field.Classification == FieldClassification.EditableScalar
                  || field.Classification == FieldClassification.EditableReference)
            {
                var expr = GetMergeExpression(field, changedFieldEnum);
                sb.AppendLine($"            {field.PropertyName} = {expr},");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine($"        var payload = new {payloadTypeName}(merged);");
        sb.AppendLine($"        return AgentDraftContractResult<DescriptorDraftPayload>.Success(payload);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string GetMergeExpression(ContractFieldSpec field, string changedFieldEnum)
    {
        var cat = CategorizeField(field);
        var flagCheck = $"cf.HasFlag({changedFieldEnum}.{field.ContractName})";
        var patchAccess = $"dto.{field.ContractName}";
        var existingAccess = $"existing.{field.PropertyName}";

        return cat switch
        {
            FieldCategory.StringToNullable =>
                $"{flagCheck} ? ({patchAccess} ?? string.Empty) : {existingAccess}",

            FieldCategory.IntToNullable =>
                $"{flagCheck} ? ({patchAccess} ?? 0) : {existingAccess}",

            FieldCategory.BoolToNullable =>
                $"{flagCheck} ? ({patchAccess} ?? false) : {existingAccess}",

            FieldCategory.TimeSpanToString =>
                $"{flagCheck} ? (!string.IsNullOrEmpty({patchAccess}) && System.TimeSpan.TryParse({patchAccess}, out var ts_{EscapeVarName(field.PropertyName)}) ? ts_{EscapeVarName(field.PropertyName)} : null) : {existingAccess}",

            FieldCategory.EnumToEnum =>
                $"{flagCheck} ? ({(field.IsNullable ? $"{patchAccess} ?? default" : patchAccess)}) : {existingAccess}",

            FieldCategory.VersionedRefToRef =>
                $"{flagCheck} ? ({patchAccess}.HasValue ? new {GetVersionedRefTypeName(field)}({patchAccess}.Value.Id, {patchAccess}.Value.Version ?? 1) : {(field.IsNullable ? "null" : "default")}) : {existingAccess}",

            FieldCategory.EventRefCollectionToRefArray =>
                $"{flagCheck} ? ({patchAccess} is not null ? {patchAccess}.Select(r => new EventRef(r.Namespace, r.Id, r.Version)).ToArray() : System.Array.Empty<EventRef>()) : {existingAccess}",

            FieldCategory.FallbackNullable =>
                $"{flagCheck} ? ({patchAccess} ?? default!) : {existingAccess}",

            _ => $"{flagCheck} ? {patchAccess} : {existingAccess}",
        };
    }

    // ──────────────────────────────────────────────────────────────
    //  TryValidatePayload
    // ──────────────────────────────────────────────────────────────

    private void WriteTryValidatePayload(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    // ── TryValidatePayload ──");
        sb.AppendLine();
        sb.AppendLine("    public static (bool IsValid, AgentDraftContractError? Error) TryValidatePayload(AgentDraftPayloadDto dto)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (dto is null)");
        sb.AppendLine("            return (false, new AgentDraftContractError { Code = AgentDraftContractErrorCodes.NullPayload, Message = \"Payload is null.\" });");
        sb.AppendLine();
        sb.AppendLine("        int populated = 0;");

        foreach (var kind in model.Kinds)
            sb.AppendLine($"        if (dto.{kind.KindName} is not null) populated++;");

        sb.AppendLine();
        sb.AppendLine("        if (populated == 0)");
        sb.AppendLine("            return (false, new AgentDraftContractError { Code = AgentDraftContractErrorCodes.DiscriminatorMismatch, Message = \"Discriminator is set but no matching payload branch is populated.\" });");
        sb.AppendLine();
        sb.AppendLine("        if (populated > 1)");
        sb.AppendLine("            return (false, new AgentDraftContractError { Code = AgentDraftContractErrorCodes.DiscriminatorMismatch, Message = \"Multiple payload branches are populated. Only one is allowed.\" });");
        sb.AppendLine();
        sb.AppendLine("        return (true, null);");
        sb.AppendLine("    }");
    }

    // ──────────────────────────────────────────────────────────────
    //  Field type categorization
    // ──────────────────────────────────────────────────────────────

    private enum FieldCategory
    {
        StringToNullable,
        IntToNullable,
        BoolToNullable,
        TimeSpanToString,
        EnumToEnum,
        VersionedRefToRef,
        EventRefCollectionToRefArray,
        FallbackNullable,
    }

    private static FieldCategory CategorizeField(ContractFieldSpec field)
    {
        var type = field.PropertyType;

        // Unwrap Nullable<T> to get underlying type
        var underlyingType = type;
        if (type is INamedTypeSymbol nullableNamed
            && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && nullableNamed.TypeArguments.Length == 1)
        {
            underlyingType = nullableNamed.TypeArguments[0];
        }

        // string
        if (underlyingType.SpecialType == SpecialType.System_String)
            return FieldCategory.StringToNullable;

        // int
        if (underlyingType.SpecialType == SpecialType.System_Int32)
            return FieldCategory.IntToNullable;

        // bool
        if (underlyingType.SpecialType == SpecialType.System_Boolean)
            return FieldCategory.BoolToNullable;

        // TimeSpan
        if (underlyingType is INamedTypeSymbol ts
            && !ts.IsGenericType
            && ts.MetadataName == "TimeSpan"
            && ts.ContainingNamespace?.ToDisplayString() == "System")
        {
            return FieldCategory.TimeSpanToString;
        }

        // VersionedDescriptorRef<T>
        if (underlyingType is INamedTypeSymbol named && named.IsGenericType)
        {
            var originalDef = named.OriginalDefinition;
            if (originalDef.Name == "VersionedDescriptorRef"
                && originalDef.ContainingNamespace?.ToDisplayString() == "CrestCreates.Metadata.Abstractions")
            {
                return FieldCategory.VersionedRefToRef;
            }

            // IReadOnlyList<EventRef>
            if (originalDef.Name == "IReadOnlyList"
                && originalDef.ContainingNamespace?.ToDisplayString() == "System.Collections.Generic"
                && named.TypeArguments.Length == 1
                && named.TypeArguments[0] is INamedTypeSymbol argType
                && argType.Name == "EventRef"
                && argType.ContainingNamespace?.ToDisplayString() == "CrestCreates.Metadata")
            {
                return FieldCategory.EventRefCollectionToRefArray;
            }
        }

        // Enum types
        if (underlyingType.TypeKind == TypeKind.Enum)
            return FieldCategory.EnumToEnum;

        return FieldCategory.FallbackNullable;
    }

    /// <summary>
    /// Extracts the fully-qualified type name of the type argument from VersionedDescriptorRef&lt;T&gt;.
    /// </summary>
    private static string GetVersionedRefTypeName(ContractFieldSpec field)
    {
        var type = field.PropertyType;
        // Unwrap Nullable<T>
        var underlyingType = type;
        if (type is INamedTypeSymbol nullableNamed
            && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && nullableNamed.TypeArguments.Length == 1)
        {
            underlyingType = nullableNamed.TypeArguments[0];
        }

        if (underlyingType is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length >= 1)
        {
            return named.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return underlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    /// <summary>
    /// Determines the namespace string to emit for DescriptorRef creation from a VersionedDescriptorRef.
    /// Maps descriptor types to their Namespace constant (lowercase kind).
    /// </summary>
    private static string GetRefNamespace(ContractFieldSpec field)
    {
        var type = field.PropertyType;
        // Unwrap Nullable<T>
        var underlyingType = type;
        if (type is INamedTypeSymbol nullableNamed
            && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && nullableNamed.TypeArguments.Length == 1)
        {
            underlyingType = nullableNamed.TypeArguments[0];
        }

        // Get the type argument of VersionedDescriptorRef<T>
        if (underlyingType is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Length >= 1)
        {
            var typeArg = named.TypeArguments[0];

            // Known descriptor type → namespace mappings
            var typeName = typeArg.Name;

            if (typeName == "SchemaDescriptor")
                return "\"schema\"";

            if (typeName == "IInteractionDescriptor" || typeName == "FormDescriptor")
                return "\"form\"";

            if (typeName == "CapabilityDescriptor")
                return "\"capability\"";

            if (typeName == "WorkflowDescriptor")
                return "\"workflow\"";

            if (typeName == "HumanTaskDescriptor")
                return "\"humantask\"";

            if (typeName == "EventDescriptor")
                return "\"event\"";

            // Fallback: lowercase the descriptor kind (strip "Descriptor" suffix)
            if (typeName.EndsWith("Descriptor", StringComparison.Ordinal))
            {
                var kind = typeName.Substring(0, typeName.Length - "Descriptor".Length);
                return $"\"{kind.ToLowerInvariant()}\"";
            }
        }

        return "\"unknown\"";
    }

    // ──────────────────────────────────────────────────────────────
    //  Utility helpers
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Escapes a property name for use as a C# local variable.
    /// Currently a no-op, but reserved for future collision avoidance.
    /// </summary>
    private static string EscapeVarName(string propertyName)
    {
        // Sanitize: replace any characters unsafe for C# identifiers (should not be needed for property names)
        return propertyName.Replace(".", "_").Replace("<", "_").Replace(">", "_");
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String)
            return false;

        if (type is IArrayTypeSymbol)
            return true;

        if (type is INamedTypeSymbol namedType)
        {
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType ==
                    SpecialType.System_Collections_Generic_IEnumerable_T)
                    return true;
            }
        }

        return false;
    }

    private static string GetElementTypeFqn(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol arrayType)
            return arrayType.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        if (type is INamedTypeSymbol namedType)
        {
            // Look for IEnumerable<T> to get the element type
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.OriginalDefinition.SpecialType ==
                    SpecialType.System_Collections_Generic_IEnumerable_T
                    && iface.TypeArguments.Length == 1)
                {
                    return iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }
            }

            // If the type itself is generic with one type arg, use that
            if (namedType.TypeArguments.Length == 1)
                return namedType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return "object";
    }
}
