using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AgentDraftContractGenerator;

internal sealed class AgentDraftContractManifestWriter
{
    private static readonly SymbolDisplayFormat FullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    public string Write(ContractModel model)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Agent.DraftContracts;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedAgentDraftPayloadContractManifest");
        sb.AppendLine("{");

        // ContractTypes
        WriteContractTypes(sb, model);

        // EditableScalarFieldTypes
        WriteEditableScalarFieldTypes(sb, model);

        // SupportedKinds
        WriteSupportedKinds(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteContractTypes(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static IReadOnlySet<Type> ContractTypes { get; } = new HashSet<Type>");
        sb.AppendLine("    {");

        foreach (var kind in model.Kinds)
        {
            var kindName = kind.KindName;
            sb.AppendLine($"        typeof(Dto.Agent{kindName}DraftPayloadDto),");
            sb.AppendLine($"        typeof(Dto.Agent{kindName}DraftPayloadPatchDto),");
            sb.AppendLine($"        typeof(Dto.Agent{kindName}DraftChangedField),");
        }

        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void WriteEditableScalarFieldTypes(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static IReadOnlySet<Type> EditableScalarFieldTypes { get; } = new HashSet<Type>");
        sb.AppendLine("    {");
        sb.AppendLine("        // Primitives");
        sb.AppendLine("        typeof(string),");
        sb.AppendLine("        typeof(int),");
        sb.AppendLine("        typeof(bool),");

        // Collect unique EditableScalar types (excluding primitives already emitted)
        var scalarTypes = new HashSet<string>();
        foreach (var kind in model.Kinds)
        {
            foreach (var field in kind.Fields)
            {
                if (field.Classification != FieldClassification.EditableScalar)
                    continue;

                var typeOfString = GetTypeOfString(field.PropertyType);
                // Skip primitives we already emitted
                if (typeOfString == "typeof(string)" ||
                    typeOfString == "typeof(int)" ||
                    typeOfString == "typeof(bool)")
                    continue;

                scalarTypes.Add(typeOfString);
            }
        }

        if (scalarTypes.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Enum / custom types from contract specs");

            // Sort for determinism
            foreach (var entry in scalarTypes.OrderBy(s => s, StringComparer.Ordinal))
            {
                sb.AppendLine($"        {entry},");
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void WriteSupportedKinds(StringBuilder sb, ContractModel model)
    {
        sb.AppendLine("    public static IReadOnlySet<DescriptorKind> SupportedKinds { get; } = new HashSet<DescriptorKind>");
        sb.AppendLine("    {");

        foreach (var kind in model.Kinds)
        {
            sb.AppendLine($"        DescriptorKind.{kind.KindName},");
        }

        sb.AppendLine("    };");
    }

    /// <summary>
    /// Converts an <see cref="ITypeSymbol"/> to a C# <c>typeof(X)</c> expression string.
    /// Handles Nullable&lt;T&gt; unwrapping, C# keyword types, and fully-qualified names.
    /// </summary>
    private static string GetTypeOfString(ITypeSymbol type)
    {
        // Unwrap Nullable<T> to the underlying value type
        if (type is INamedTypeSymbol namedType &&
            namedType.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T)
        {
            type = namedType.TypeArguments[0];
        }

        // C# keyword types
        switch (type.SpecialType)
        {
            case SpecialType.System_String: return "typeof(string)";
            case SpecialType.System_Int32: return "typeof(int)";
            case SpecialType.System_Boolean: return "typeof(bool)";
            case SpecialType.System_Int64: return "typeof(long)";
            case SpecialType.System_Single: return "typeof(float)";
            case SpecialType.System_Double: return "typeof(double)";
            case SpecialType.System_Decimal: return "typeof(decimal)";
            case SpecialType.System_Byte: return "typeof(byte)";
            case SpecialType.System_SByte: return "typeof(sbyte)";
            case SpecialType.System_Int16: return "typeof(short)";
            case SpecialType.System_UInt16: return "typeof(ushort)";
            case SpecialType.System_UInt32: return "typeof(uint)";
            case SpecialType.System_UInt64: return "typeof(ulong)";
            case SpecialType.System_Char: return "typeof(char)";
            case SpecialType.System_Object: return "typeof(object)";
            default:
                // Fully-qualified name (global::Namespace.Type)
                var fullName = type.ToDisplayString(FullyQualifiedFormat);
                return $"typeof({fullName})";
        }
    }
}
