using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.AgentDraftContractGenerator;

internal sealed class AgentDraftContractDtoWriter
{
    public string WritePayloadDtos(ContractModel model)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        // Per-kind payload DTOs
        foreach (var kind in model.Kinds)
        {
            WritePayloadDto(sb, kind);
            sb.AppendLine();
        }

        // One-of wrapper
        WritePayloadOneOfWrapper(sb, model.Kinds);

        return sb.ToString();
    }

    public string WritePatchDtos(ContractModel model)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        // Per-kind patch DTOs
        foreach (var kind in model.Kinds)
        {
            WritePatchDto(sb, kind);
            sb.AppendLine();
        }

        // One-of wrapper
        WritePatchOneOfWrapper(sb, model.Kinds);

        return sb.ToString();
    }

    public string WriteChangedFieldEnums(ContractModel model)
    {
        var sb = new StringBuilder();

        WriteHeader(sb);

        // Per-kind changed field enums
        for (int i = 0; i < model.Kinds.Count; i++)
        {
            WriteChangedFieldEnum(sb, model.Kinds[i]);
            if (i < model.Kinds.Count - 1)
                sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using CrestCreates.Metadata.Abstractions;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.Agent.DraftContracts.Dto;");
        sb.AppendLine();
    }

    private void WritePayloadDto(StringBuilder sb, ContractKindSpec kind)
    {
        var dtoName = $"Agent{kind.KindName}DraftPayloadDto";
        sb.AppendLine($"public sealed record {dtoName}");
        sb.AppendLine("{");

        var editableFields = kind.Fields
            .Where(f => f.Classification == FieldClassification.EditableScalar
                     || f.Classification == FieldClassification.EditableReference)
            .OrderBy(f => f.ContractName, StringComparer.Ordinal)
            .ToList();

        foreach (var field in editableFields)
        {
            var dtoType = MapToDtoType(field.PropertyType, field.IsNullable, field.IsCollection);
            var isNullable = dtoType.EndsWith("?", StringComparison.Ordinal);
            var requiredModifier = isNullable ? "" : "required ";

            sb.AppendLine($"    public {requiredModifier}{dtoType} {field.ContractName} {{ get; init; }}");
        }

        sb.AppendLine("}");
    }

    private static void WritePayloadOneOfWrapper(StringBuilder sb, IReadOnlyList<ContractKindSpec> kinds)
    {
        sb.AppendLine("public sealed record AgentDraftPayloadDto");
        sb.AppendLine("{");
        sb.AppendLine("    public required DescriptorKind Discriminator { get; init; }");

        foreach (var kind in kinds)
        {
            sb.AppendLine($"    public Agent{kind.KindName}DraftPayloadDto? {kind.KindName} {{ get; init; }}");
        }

        sb.AppendLine("}");
    }

    private void WritePatchDto(StringBuilder sb, ContractKindSpec kind)
    {
        var dtoName = $"Agent{kind.KindName}DraftPayloadPatchDto";
        sb.AppendLine($"public sealed record {dtoName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public required Agent{kind.KindName}DraftPayloadDto Payload {{ get; init; }}");
        sb.AppendLine($"    public required Agent{kind.KindName}DraftChangedField ChangedFields {{ get; init; }}");
        sb.AppendLine("}");
    }

    private static void WritePatchOneOfWrapper(StringBuilder sb, IReadOnlyList<ContractKindSpec> kinds)
    {
        sb.AppendLine("public sealed record AgentDraftPayloadPatchDto");
        sb.AppendLine("{");
        sb.AppendLine("    public required DescriptorKind Discriminator { get; init; }");

        foreach (var kind in kinds)
        {
            sb.AppendLine($"    public Agent{kind.KindName}DraftPayloadPatchDto? {kind.KindName} {{ get; init; }}");
        }

        sb.AppendLine("}");
    }

    private static void WriteChangedFieldEnum(StringBuilder sb, ContractKindSpec kind)
    {
        var enumName = $"Agent{kind.KindName}DraftChangedField";

        var editableFields = kind.Fields
            .Where(f => f.Classification == FieldClassification.EditableScalar
                     || f.Classification == FieldClassification.EditableReference)
            .OrderBy(f => f.ContractName, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("[Flags]");
        sb.AppendLine($"public enum {enumName}");
        sb.AppendLine("{");
        sb.AppendLine("    None = 0,");

        int flagValue = 1;
        for (int i = 0; i < editableFields.Count; i++)
        {
            var field = editableFields[i];
            sb.AppendLine($"    {field.ContractName} = {flagValue},");
            if (i < editableFields.Count - 1)
                flagValue *= 2;
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Maps a CLR type to its DTO type string.
    /// Returns a fully-qualified type name for the generated DTO property.
    /// For nullable value types, appends "?"; for reference types, appends "?".
    /// Enum types respect the original <paramref name="isNullable"/> — non-nullable enums
    /// remain non-nullable in the DTO (caller must use <c>required</c>).
    /// </summary>
    private static string MapToDtoType(ITypeSymbol type, bool isNullable, bool isCollection)
    {
        // Unwrap Nullable<T> to get the underlying type.
        // Nullable<T> wraps value types like TimeSpan?, VersionedDescriptorRef<T>?, enum?.
        var underlyingType = type;
        if (type is INamedTypeSymbol nullableNamed
            && nullableNamed.ConstructedFrom?.SpecialType == SpecialType.System_Nullable_T
            && nullableNamed.TypeArguments.Length == 1)
        {
            underlyingType = nullableNamed.TypeArguments[0];
        }

        // string → string?
        if (underlyingType.SpecialType == SpecialType.System_String)
            return "string?";

        // int → int?
        if (underlyingType.SpecialType == SpecialType.System_Int32)
            return "int?";

        // bool → bool?
        if (underlyingType.SpecialType == SpecialType.System_Boolean)
            return "bool?";

        // TimeSpan / TimeSpan? → string? (ISO 8601 duration)
        if (underlyingType is INamedTypeSymbol ts
            && !ts.IsGenericType
            && ts.MetadataName == "TimeSpan"
            && ts.ContainingNamespace?.ToDisplayString() == "System")
        {
            return "string?";
        }

            // VersionedDescriptorRef<T> → DescriptorRef?
            if (underlyingType is INamedTypeSymbol named && named.IsGenericType)
            {
                var originalDef = named.OriginalDefinition;
                // Use Name (not MetadataName) — MetadataName includes arity backtick for generics
                if (originalDef.Name == "VersionedDescriptorRef"
                    && originalDef.ContainingNamespace?.ToDisplayString() == "CrestCreates.Metadata.Abstractions")
                {
                    return "global::CrestCreates.Metadata.Abstractions.DescriptorRef?";
                }

                // IReadOnlyList<EventRef> → DescriptorRef[]?
                // EventRef lives in CrestCreates.Metadata (same namespace as CapabilityDescriptor).
                if (originalDef.Name == "IReadOnlyList"
                    && originalDef.ContainingNamespace?.ToDisplayString() == "System.Collections.Generic"
                    && named.TypeArguments.Length == 1
                    && named.TypeArguments[0] is INamedTypeSymbol argType
                    && argType.Name == "EventRef"
                    && argType.ContainingNamespace?.ToDisplayString() == "CrestCreates.Metadata")
                {
                    return "global::CrestCreates.Metadata.Abstractions.DescriptorRef[]?";
                }
        }

        // DescriptorRef (non-generic) → DescriptorRef?
        if (underlyingType is INamedTypeSymbol dr
            && !dr.IsGenericType
            && dr.MetadataName == "DescriptorRef"
            && dr.ContainingNamespace?.ToDisplayString() == "CrestCreates.Metadata.Abstractions")
        {
            return "global::CrestCreates.Metadata.Abstractions.DescriptorRef?";
        }

        // Enum types — nullable only if original is nullable
        // FullyQualifiedFormat already includes the "global::" prefix.
        if (underlyingType.TypeKind == TypeKind.Enum)
        {
            var fqn = underlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return isNullable ? $"{fqn}?" : fqn;
        }

        // All other types are nullable in DTO
        var fqnDefault = underlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"{fqnDefault}?";
    }
}
