namespace CrestCreates.Agent.Tools.Tests.Architecture;

/// <summary>
/// Typed manifest of every Case ID and normative test name from the Phase 9b+
/// Plan §7 ledger. Concrete [Fact] wrappers are added when their owning Slice
/// starts Red; there are no permanently skipped tests. The final Boundary test
/// parses this manifest so removing or renaming a Case ID fails CI.
/// </summary>
public static class AgentToolPreDispatchCaseManifest
{
    public static readonly IReadOnlyList<CaseEntry> AllCases =
    [
        new("H01", "Identical_PreDispatchRetry_Should_Return_SameAuditId", 2),
        new("H02", "Identical_PreDispatchRetry_Should_Return_SameAuditId", 2),
        new("H03", "Accepted_ResponseLoss_Should_Be_Reconciled_By_AttemptIdentity", 3),
        new("H04", "Accepted_BindResponseLoss_Should_Be_Reconciled_From_Gate", 3),
        new("H05", "Dispatch_Should_Require_ExactAcceptedReceipt", 3),
        new("H06", "Restarted_Reconciler_Should_Not_AutoDispatch", 4),
        new("H07", "Authoritative_Missing_Should_Close_Only_UnrecordedAttempt", 4),
        new("H08", "Reconciled_Checkpoint_Should_Not_Consume_Or_Release_BudgetTwice", 4),
        new("H09", "Budget_ResponseLoss_Should_Recover_ReservationByAttemptIdentity", 3),
        new("H10", "ReservationBind_ResponseLoss_Should_Recover_ReadyState", 3),

        new("B01", "Concurrent_IdenticalCheckpoint_Should_Have_OneAcceptance", 2),
        new("B02", "Different_Attempt_Should_Not_Be_Treated_As_Duplicate", 2),
        new("B03", "TenantScoped_Identity_Should_Not_Cross_Host_Or_Tenant", 2),
        new("B04", "Optional_SchemaContracts_Should_RoundTrip_Without_Defaults", 2),
        new("B05", "NotRequired_Approval_Should_Produce_ValidCheckpoint", 2),
        new("B06", "Pending_Checkpoint_Should_Block_LeaseExpiryReplacement", 3),
        new("B07", "Accepted_Checkpoint_Should_Block_LeaseExpiryReplacement", 3),
        new("B08", "Released_Reservation_Should_Not_Be_ReleasedTwice", 4),
        new("B09", "Retention_AtMinimumWindow_Should_RemainQueryable", 6),
        new("B10", "Cleanup_AfterTerminalWindows_Should_RetainTerminalReceipt", 6),
        new("B11", "Lookup_Should_Return_Detached_CompleteCheckpoint", 2),
        new("B12", "Repeated_Reconciliation_Should_Return_SameTerminalReceipt", 4),
        new("B13", "Ready_Checkpoint_Should_Block_LeaseExpiryReplacement", 3),
        new("B14", "LeaseRenewal_Should_Not_Change_FrozenCheckpointIdentity", 3),
        new("B15", "Known_BudgetDenial_Should_Abandon_Attempt_WithStableReceipt", 3),
        new("B16", "Cleanup_Should_Not_Remove_PreDispatchReadyState", 6),
        new("B17", "Acquire_AfterBudgetDenial_Should_Create_NewAttempt", 3),
        new("B18", "StillPending_Observation_Should_Progress_To_Released", 4),

        new("F01", "Conflicting_FullCheckpoint_Should_Be_Rejected_And_Preserve_First", 2),
        new("F02", "Changed_ToolCapabilityOrSchemaContract_Should_Conflict", 2),
        new("F03", "Changed_EffectiveGovernance_Should_Conflict", 2),
        new("F04", "Changed_LeaseIdentityOrTime_Should_Conflict", 2),
        new("F05", "Changed_ApprovalClaim_Should_Conflict", 2),
        new("F06", "Changed_BudgetFacts_Should_Conflict", 2),
        new("F07", "Malformed_WriteResult_Should_FailClosed", 3),
        new("F08", "Unconfirmed_Checkpoint_Should_Not_Dispatch_Or_Abandon", 3),
        new("F09", "Unavailable_Lookup_Should_Not_Be_Treated_As_Missing", 3),
        new("F10", "PendingFence_Should_Survive_ProcessRestart", 5),
        new("F11", "DurableCheckpoint_Should_Survive_ProcessRestart", 5),
        new("F12", "AcceptedFence_Should_Survive_ProcessRestart", 5),
        new("F13", "Stale_FencingToken_Should_Not_Dispatch", 3),
        new("F14", "CommittedBudget_WithDispatchFalse_Should_Conflict", 4),
        new("F15", "IndeterminateBudget_Should_RemainStillPending", 4),
        new("F16", "PostDispatchUnknown_Should_Remain_Indeterminate", 4),
        new("F17", "Concurrent_Reconcilers_Should_Have_One_CasWinner", 4),
        new("F18", "Cleanup_Should_Not_Remove_LiveReconciliationState", 6),
        new("F19", "TooShort_Retention_Should_Fail_Startup", 6),
        new("F20", "Migration_Should_Reject_IncompatibleCheckpointSchema", 5),
        new("F21", "Cancellation_AtCrashWindow_Should_Not_ClaimMissingOrRollback", 5),
        new("F22", "AccountabilityFailure_Should_Not_Change_ReconciliationResult", 6),
        new("F23", "Lookup_Should_Return_Detached_CompleteCheckpoint", 2),
        new("F24", "Missing_RequiredPersistedField_Should_FailClosed", 5),
        new("F25", "Unavailable_BudgetLookup_Should_RemainFenced", 3),
        new("F26", "Malformed_BudgetDenial_Should_RemainFenced", 3),
        new("F27", "Ready_WithAuthoritativeBudgetMissing_Should_Conflict", 4),
        new("F28", "Accepted_WithAuthoritativeBudgetMissing_Should_Conflict", 4),
        new("F29", "Conflicting_BudgetDenialReceipt_Should_Be_Rejected", 3),
        new("F30", "StillPending_Should_Not_Create_TerminalReceipt", 4),

        new("C01", "Invoker_GovernanceComposition_Should_Produce_OneCoherentDecision", 3),
        new("C02", "Immediate_ExactRecovery_Should_Dispatch_AtMostOnce", 3),
        new("C03", "Restarted_Reconciler_Should_Not_AutoDispatch", 4),
        new("C04", "DurableCheckpoint_Should_Survive_ProcessRestart", 5),
        new("C05", "CrashWindow_Should_Match_NormativeRecoveryState", 5),
        new("C06", "AccountabilityProjection_Should_Not_Replace_GovernanceControl", 6),
        new("C07", "InMemory_PreDispatch_Should_Pass_SharedSemanticContractCases", 2),
        new("C08", "AgentToolDurableContracts_Should_Not_Expose_NpgsqlTypes", 1),
        new("C09", "AgentToolPreDispatch_Should_Use_GeneratedJsonOnly", 5),
        new("C10", "PostgreSql_PreDispatch_Should_Run_In_NativeAot_Binary", 7),
        new("C11", "Reserve_Gate_Checkpoint_ResponseLoss_Should_RecoverOriginalReceipts", 3),
        new("C12", "PostgreSql_AgentToolParticipants_Should_Pass_ExistingPhase8fContracts", 5),
    ];

    public static readonly IReadOnlyList<string> NormativeTestNames =
    [
        "Identical_PreDispatchRetry_Should_Return_SameAuditId",
        "Accepted_ResponseLoss_Should_Be_Reconciled_By_AttemptIdentity",
        "Accepted_BindResponseLoss_Should_Be_Reconciled_From_Gate",
        "Dispatch_Should_Require_ExactAcceptedReceipt",
        "Immediate_ExactRecovery_Should_Dispatch_AtMostOnce",
        "Restarted_Reconciler_Should_Not_AutoDispatch",
        "Authoritative_Missing_Should_Close_Only_UnrecordedAttempt",
        "Reconciled_Checkpoint_Should_Not_Consume_Or_Release_BudgetTwice",
        "Repeated_Reconciliation_Should_Return_SameTerminalReceipt",
        "Budget_ResponseLoss_Should_Recover_ReservationByAttemptIdentity",
        "ReservationBind_ResponseLoss_Should_Recover_ReadyState",
        "Concurrent_IdenticalCheckpoint_Should_Have_OneAcceptance",
        "Different_Attempt_Should_Not_Be_Treated_As_Duplicate",
        "TenantScoped_Identity_Should_Not_Cross_Host_Or_Tenant",
        "Optional_SchemaContracts_Should_RoundTrip_Without_Defaults",
        "NotRequired_Approval_Should_Produce_ValidCheckpoint",
        "Pending_Checkpoint_Should_Block_LeaseExpiryReplacement",
        "Accepted_Checkpoint_Should_Block_LeaseExpiryReplacement",
        "Released_Reservation_Should_Not_Be_ReleasedTwice",
        "Retention_AtMinimumWindow_Should_RemainQueryable",
        "Cleanup_AfterTerminalWindows_Should_RetainTerminalReceipt",
        "Lookup_Should_Return_Detached_CompleteCheckpoint",
        "Ready_Checkpoint_Should_Block_LeaseExpiryReplacement",
        "LeaseRenewal_Should_Not_Change_FrozenCheckpointIdentity",
        "Known_BudgetDenial_Should_Abandon_Attempt_WithStableReceipt",
        "Repeated_BudgetDenial_Should_Return_SameAbandonedReceipt",
        "Cleanup_Should_Not_Remove_PreDispatchReadyState",
        "Acquire_AfterBudgetDenial_Should_Create_NewAttempt",
        "StillPending_Observation_Should_Progress_To_Released",
        "Conflicting_FullCheckpoint_Should_Be_Rejected_And_Preserve_First",
        "Changed_ToolCapabilityOrSchemaContract_Should_Conflict",
        "Changed_EffectiveGovernance_Should_Conflict",
        "Changed_LeaseIdentityOrTime_Should_Conflict",
        "Changed_ApprovalClaim_Should_Conflict",
        "Changed_BudgetFacts_Should_Conflict",
        "Malformed_WriteResult_Should_FailClosed",
        "Unconfirmed_Checkpoint_Should_Not_Dispatch_Or_Abandon",
        "Unavailable_Lookup_Should_Not_Be_Treated_As_Missing",
        "PendingFence_Should_Survive_ProcessRestart",
        "DurableCheckpoint_Should_Survive_ProcessRestart",
        "AcceptedFence_Should_Survive_ProcessRestart",
        "Stale_FencingToken_Should_Not_Dispatch",
        "CommittedBudget_WithDispatchFalse_Should_Conflict",
        "IndeterminateBudget_Should_RemainStillPending",
        "PostDispatchUnknown_Should_Remain_Indeterminate",
        "Concurrent_Reconcilers_Should_Have_One_CasWinner",
        "Cleanup_Should_Not_Remove_LiveReconciliationState",
        "TooShort_Retention_Should_Fail_Startup",
        "Migration_Should_Reject_IncompatibleCheckpointSchema",
        "Cancellation_AtCrashWindow_Should_Not_ClaimMissingOrRollback",
        "AccountabilityFailure_Should_Not_Change_ReconciliationResult",
        "Missing_RequiredPersistedField_Should_FailClosed",
        "Unavailable_BudgetLookup_Should_RemainFenced",
        "Malformed_BudgetDenial_Should_RemainFenced",
        "Ready_WithAuthoritativeBudgetMissing_Should_Conflict",
        "Accepted_WithAuthoritativeBudgetMissing_Should_Conflict",
        "Conflicting_BudgetDenialReceipt_Should_Be_Rejected",
        "StillPending_Should_Not_Create_TerminalReceipt",
        "Invoker_GovernanceComposition_Should_Produce_OneCoherentDecision",
        "InMemory_PreDispatch_Should_Pass_SharedSemanticContractCases",
        "AgentToolDurableContracts_Should_Not_Expose_NpgsqlTypes",
        "RuntimeProjects_Should_Not_Reference_AgentToolPostgreSqlProvider",
        "AgentToolPreDispatch_Should_Use_GeneratedJsonOnly",
        "PostgreSql_PreDispatch_Should_Run_In_NativeAot_Binary",
        "Reserve_Gate_Checkpoint_ResponseLoss_Should_RecoverOriginalReceipts",
        "PostgreSql_AgentToolParticipants_Should_Pass_ExistingPhase8fContracts",
        "PostgreSql_Registration_Order_Should_Not_Produce_MixedParticipants",
        "Recovery_Should_Validate_FullLeaseFencingReservationApprovalAndGovernance",
    ];

    public sealed record CaseEntry(string Id, string PrimaryTest, int OwningSlice);
}
