using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.BackgroundJobsGenerator;

[Generator]
public class BackgroundJobsSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var backgroundJobsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetBackgroundJobInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(backgroundJobsProvider.Collect(), GenerateBackgroundJobCode);
    }

    private static BackgroundJobInfo? GetBackgroundJobInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is null) return null;

        var backgroundJobAttribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "BackgroundJobAttribute");
        if (backgroundJobAttribute is null) return null;

        var name = classDeclaration.Identifier.Text;
        var cronExpression = "";
        var enableAuthorization = false;

        foreach (var namedArg in backgroundJobAttribute.NamedArguments)
        {
            if (namedArg.Key == "Name" && namedArg.Value.Value is string nameValue)
            {
                name = nameValue;
            }
            else if (namedArg.Key == "CronExpression" && namedArg.Value.Value is string cronValue)
            {
                cronExpression = cronValue;
            }
            else if (namedArg.Key == "EnableAuthorization" && namedArg.Value.Value is bool authValue)
            {
                enableAuthorization = authValue;
            }
        }

        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var fullName = symbol.ToDisplayString();

        return new BackgroundJobInfo(
            symbol.Name,
            namespaceName,
            fullName,
            name,
            cronExpression,
            enableAuthorization);
    }

    private static void GenerateBackgroundJobCode(SourceProductionContext context, ImmutableArray<BackgroundJobInfo?> jobs)
    {
        var validJobs = jobs.Where(j => j is not null).Cast<BackgroundJobInfo>().ToList();
        if (validJobs.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using CrestCreates.BackgroundJobs.Services;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.BackgroundJobs;");
        sb.AppendLine("{");
        sb.AppendLine("    public static class BackgroundJobExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddBackgroundJobs(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var job in validJobs)
        {
            sb.AppendLine($"            services.AddTransient<{job.FullName}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("BackgroundJobsExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class BackgroundJobInfo
    {
        public BackgroundJobInfo(string name, string namespaceName, string fullName, string jobName, string cronExpression, bool enableAuthorization)
        {
            Name = name;
            NamespaceName = namespaceName;
            FullName = fullName;
            JobName = jobName;
            CronExpression = cronExpression;
            EnableAuthorization = enableAuthorization;
        }

        public string Name { get; }
        public string NamespaceName { get; }
        public string FullName { get; }
        public string JobName { get; }
        public string CronExpression { get; }
        public bool EnableAuthorization { get; }
    }
}