using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CrestCreates.CodeGenerator.QueryExtensionsGenerator
{
    [Generator]
    public class QueryExtensionsSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entityClasses = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsEntityCandidate(node),
                    transform: static (ctx, _) => GetEntityClass(ctx))
                .Where(static x => x is not null)
                .Collect();

            context.RegisterSourceOutput(entityClasses, ExecuteGeneration);
        }

        private static bool IsEntityCandidate(SyntaxNode node)
        {
            return node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0;
        }

        private static INamedTypeSymbol? GetEntityClass(GeneratorSyntaxContext context)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (symbol != null && HasGenerateEntityOrQueryAttribute(symbol))
            {
                return symbol;
            }

            return null;
        }

        private static bool HasGenerateEntityOrQueryAttribute(INamedTypeSymbol symbol)
        {
            return symbol.GetAttributes().Any(attr =>
                attr.AttributeClass != null && (
                    attr.AttributeClass.Name == "GenerateQueryBuilderAttribute" ||
                    attr.AttributeClass.Name == "GenerateQueryBuilder" ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".GenerateQueryBuilderAttribute") ||
                    attr.AttributeClass.ToDisplayString().EndsWith(".GenerateQueryBuilder")
                ));
        }

        private void ExecuteGeneration(SourceProductionContext context, ImmutableArray<INamedTypeSymbol?> entityClasses)
        {
            if (entityClasses.IsDefaultOrEmpty) return;

            var processedEntities = new HashSet<string>();

            foreach (var entityClass in entityClasses)
            {
                if (entityClass == null) continue;

                var entityFullName = entityClass.ToDisplayString();
                if (processedEntities.Contains(entityFullName)) continue;

                processedEntities.Add(entityFullName);

                try
                {
                    GenerateQueryExtensions(context, entityClass);
                }
                catch (Exception ex)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("CCQE001", "QueryExtensions generation error",
                            $"Error generating query extensions for {entityFullName}: {ex.Message}",
                            "CodeGeneration", DiagnosticSeverity.Warning, true),
                        Location.None));
                }
            }
        }

        private void GenerateQueryExtensions(SourceProductionContext context, INamedTypeSymbol entityClass)
        {
            var entityName = entityClass.Name;
            var namespaceName = entityClass.ContainingNamespace.ToDisplayString();
            var properties = GetQueryableProperties(entityClass);

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Linq;");
            builder.AppendLine("using System.Linq.Expressions;");
            builder.AppendLine($"using {namespaceName};");
            builder.AppendLine();
            builder.AppendLine($"namespace {namespaceName}.QueryExtensions");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {entityName} 查询扩展方法");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public static class {entityName}QueryExtensions");
            builder.AppendLine("    {");

            // 生成 Where 方法（等值过滤）
            foreach (var prop in properties)
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 过滤（等值）");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}(this IQueryable<{entityName}> query, {propType} value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var predicate = Expression.Equal(property, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            // 生成字符串属性的方法
            foreach (var prop in properties.Where(p => IsStringType(p.Type)))
            {
                var propName = prop.Name;

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 模糊查询（包含）");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}Contains(this IQueryable<{entityName}> query, string value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var containsMethod = typeof(string).GetMethod(\"Contains\", new[] {{ typeof(string) }});");
                builder.AppendLine($"            if (containsMethod == null) return query;");
                builder.AppendLine($"            var predicate = Expression.Call(property, containsMethod, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 开头匹配");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}StartsWith(this IQueryable<{entityName}> query, string value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var startsWithMethod = typeof(string).GetMethod(\"StartsWith\", new[] {{ typeof(string) }});");
                builder.AppendLine($"            if (startsWithMethod == null) return query;");
                builder.AppendLine($"            var predicate = Expression.Call(property, startsWithMethod, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 结尾匹配");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}EndsWith(this IQueryable<{entityName}> query, string value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var endsWithMethod = typeof(string).GetMethod(\"EndsWith\", new[] {{ typeof(string) }});");
                builder.AppendLine($"            if (endsWithMethod == null) return query;");
                builder.AppendLine($"            var predicate = Expression.Call(property, endsWithMethod, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            // 生成数值/日期属性的方法
            foreach (var prop in properties.Where(p => IsNumericOrDateType(p.Type)))
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 大于过滤");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}GreaterThan(this IQueryable<{entityName}> query, {propType} value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var predicate = Expression.GreaterThan(property, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 小于过滤");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}LessThan(this IQueryable<{entityName}> query, {propType} value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var constant = Expression.Constant(value);");
                builder.AppendLine($"            var predicate = Expression.LessThan(property, constant);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 范围过滤");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> Where{propName}Between(this IQueryable<{entityName}> query, {propType} fromValue, {propType} toValue)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var fromConstant = Expression.Constant(fromValue);");
                builder.AppendLine($"            var toConstant = Expression.Constant(toValue);");
                builder.AppendLine($"            var lowerPredicate = Expression.GreaterThanOrEqual(property, fromConstant);");
                builder.AppendLine($"            var upperPredicate = Expression.LessThanOrEqual(property, toConstant);");
                builder.AppendLine($"            var predicate = Expression.AndAlso(lowerPredicate, upperPredicate);");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, bool>>(predicate, parameter);");
                builder.AppendLine("            return query.Where(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            // 生成 OrderBy 方法
            foreach (var prop in properties)
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 升序排序");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> OrderBy{propName}(this IQueryable<{entityName}> query)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, {propType}>>(property, parameter);");
                builder.AppendLine("            return query.OrderBy(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            // 生成 OrderByDescending 方法
            foreach (var prop in properties)
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString();

                builder.AppendLine($"        /// <summary>");
                builder.AppendLine($"        /// 按 {propName} 降序排序");
                builder.AppendLine($"        /// </summary>");
                builder.AppendLine($"        public static IQueryable<{entityName}> OrderBy{propName}Descending(this IQueryable<{entityName}> query)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var parameter = Expression.Parameter(typeof({entityName}), \"e\");");
                builder.AppendLine($"            var property = Expression.Property(parameter, \"{propName}\");");
                builder.AppendLine($"            var lambda = Expression.Lambda<Func<{entityName}, {propType}>>(property, parameter);");
                builder.AppendLine("            return query.OrderByDescending(lambda);");
                builder.AppendLine("        }");
                builder.AppendLine();
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");

            context.AddSource($"{entityName}QueryExtensions.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
        }

        private List<IPropertySymbol> GetQueryableProperties(INamedTypeSymbol entityClass)
        {
            return entityClass.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                           !p.IsStatic &&
                           p.CanBeReferencedByName &&
                           p.Name != "Id" &&
                           !IsNavigationProperty(p))
                .ToList();
        }

        private bool IsNavigationProperty(IPropertySymbol property)
        {
            var type = property.Type;

            if (type is INamedTypeSymbol namedType)
            {
                if (namedType.IsGenericType)
                {
                    var genericTypeName = namedType.ConstructedFrom.ToDisplayString();
                    if (genericTypeName.StartsWith("System.Collections") ||
                        genericTypeName.StartsWith("System.Collections.Generic"))
                    {
                        return true;
                    }
                }

                if (namedType.TypeKind == TypeKind.Class &&
                    !namedType.IsValueType &&
                    namedType.SpecialType == SpecialType.None &&
                    !IsPrimitiveType(namedType))
                {
                    return true;
                }
            }

            return false;
        }

        private bool IsPrimitiveType(INamedTypeSymbol type)
        {
            var primitiveTypes = new[]
            {
                SpecialType.System_Boolean,
                SpecialType.System_Char,
                SpecialType.System_SByte,
                SpecialType.System_Byte,
                SpecialType.System_Int16,
                SpecialType.System_UInt16,
                SpecialType.System_Int32,
                SpecialType.System_UInt32,
                SpecialType.System_Int64,
                SpecialType.System_UInt64,
                SpecialType.System_Decimal,
                SpecialType.System_Single,
                SpecialType.System_Double,
                SpecialType.System_String,
                SpecialType.System_DateTime
            };

            return primitiveTypes.Contains(type.SpecialType) || type.Name == "Guid";
        }

        private bool IsStringType(ITypeSymbol type)
        {
            return type.SpecialType == SpecialType.System_String;
        }

        private bool IsNumericOrDateType(ITypeSymbol type)
        {
            var numericTypes = new[]
            {
                SpecialType.System_Int16,
                SpecialType.System_Int32,
                SpecialType.System_Int64,
                SpecialType.System_UInt16,
                SpecialType.System_UInt32,
                SpecialType.System_UInt64,
                SpecialType.System_Decimal,
                SpecialType.System_Single,
                SpecialType.System_Double,
                SpecialType.System_Byte,
                SpecialType.System_SByte,
                SpecialType.System_DateTime
            };

            return numericTypes.Contains(type.SpecialType);
        }
    }
}
