using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace CrestCreates.CodeGenerator.HealthCheckGenerator;

[Generator]
public class HealthCheckSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var healthChecksProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHealthCheckInfo(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(healthChecksProvider.Collect(), GenerateHealthCheckCode);
    }

    private static HealthCheckInfo? GetHealthCheckInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
        if (symbol is null) return null;

        var healthCheckAttribute = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "HealthCheckAttribute");
        if (healthCheckAttribute is null) return null;

        var name = classDeclaration.Identifier.Text;
        var tags = new List<string>();
        var description = "";

        foreach (var namedArg in healthCheckAttribute.NamedArguments)
        {
            if (namedArg.Key == "Name" && namedArg.Value.Value is string nameValue)
            {
                name = nameValue;
            }
            else if (namedArg.Key == "Tags" && namedArg.Value.Value is IEnumerable<object> tagValues)
            {
                tags.AddRange(tagValues.Select(t => t.ToString()));
            }
            else if (namedArg.Key == "Description" && namedArg.Value.Value is string descValue)
            {
                description = descValue;
            }
        }

        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var fullName = symbol.ToDisplayString();
        var typeName = symbol.Name;

        return new HealthCheckInfo(
            typeName,
            namespaceName,
            fullName,
            name,
            tags.ToArray(),
            description);
    }

    private static void GenerateHealthCheckCode(SourceProductionContext context, ImmutableArray<HealthCheckInfo?> healthChecks)
    {
        var validHealthChecks = healthChecks.Where(h => h is not null).Cast<HealthCheckInfo>().ToList();
        if (validHealthChecks.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace CrestCreates.HealthCheck;");
        sb.AppendLine("{");
        sb.AppendLine("    public static class HealthCheckServiceCollectionExtensions");
        sb.AppendLine("    {");

        foreach (var healthCheck in validHealthChecks)
        {
            sb.AppendLine($"        public static IServiceCollection Add{healthCheck.TypeName}(this IServiceCollection services)");
            sb.AppendLine("        {");
            sb.AppendLine($"            services.AddSingleton<{healthCheck.FullName}>();");
            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("HealthCheckExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private class HealthCheckInfo
    {
        public HealthCheckInfo(string typeName, string namespaceName, string fullName, string name, string[] tags, string description)
        {
            TypeName = typeName;
            NamespaceName = namespaceName;
            FullName = fullName;
            Name = name;
            Tags = tags;
            Description = description;
        }

        public string TypeName { get; }
        public string NamespaceName { get; }
        public string FullName { get; }
        public string Name { get; }
        public string[] Tags { get; }
        public string Description { get; }
    }
}