<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CrestCreates.Data.Core\CrestCreates.Data.Core.csproj" />
    <ProjectReference Include="..\CrestCreates.Data.Abstractions\CrestCreates.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Domain\CrestCreates.Domain.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.Infrastructure\CrestCreates.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.MultiTenancy.Abstract\CrestCreates.MultiTenancy.Abstract.csproj" />
    <ProjectReference Include="..\..\Framework\CrestCreates.DataFilter\CrestCreates.DataFilter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FreeSql" />
    <PackageReference Include="FreeSql.DbContext" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CrestCreates.Data.FreeSql</RootNamespace>
  </PropertyGroup>

</Project>
