<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../Tooling/CrestCreates.BuildTasks/CrestCreates.Modules.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rougamo.Extensions.DependencyInjection.Microsoft" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CrestCreates.AuditLogging.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CrestCreates.AuditLogging.Abstractions/CrestCreates.AuditLogging.Abstractions.csproj" />
    <ProjectReference Include="../../../Framework/Infrastructure/CrestCreates.Authorization.Abstractions/CrestCreates.Authorization.Abstractions.csproj" />
    <ProjectReference Include="../../../Framework/Ddd/CrestCreates.Domain/CrestCreates.Domain.csproj" />
    <ProjectReference Include="../../../Framework/Modularity/CrestCreates.Modularity/CrestCreates.Modularity.csproj" />
    <ProjectReference Include="../../../Framework/Infrastructure/CrestCreates.MultiTenancy.Abstract/CrestCreates.MultiTenancy.Abstract.csproj" />
  </ItemGroup>

</Project>
