using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using CrestCreates.Modularity;
using CrestCreates.SourceGenerator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CrestCreates.SourceGenerator;

// 模块信息记录类，用于生成模块注册代码
public class ModuleInfo
{
    public string TypeName { get; }
    public string ClassName { get; }
    public List<string> Dependencies { get; }

    public ModuleInfo(string typeName, string className, List<string> dependencies)
    {
        TypeName = typeName;
        ClassName = className;
        Dependencies = dependencies;
    }
}

[Generator]
public class ModuleRegistrarGenerator : CommonIncrementalGenerator
{
    protected override string GeneratorName => "ModuleRegistrarGenerator";
    protected override string ClassAttributeName => nameof(ModuleAttribute);
    protected override string GeneratedClassName => "GeneratedModuleRegistrar";
    protected override string GetAttributeSource()
    {
        // ModuleAttribute 已经在 CrestCreates.Modularity 命名空间中定义，不需要生成
        return string.Empty;
    }

    protected override ClassAnalysisInfo? AnalyzeClass(GeneratorSyntaxContext context)
    {
        // 确保我们处理的是类声明
        if (context.Node is not ClassDeclarationSyntax classDeclaration)
        {
            return null;
        }

        // 获取语义模型，以便我们能访问符号信息
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (classSymbol == null)
        {
            return null;
        }

        // 查找类上的ModuleAttribute特性
        var moduleAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == ClassAttributeName ||
                                   attr.AttributeClass?.Name == ClassAttributeName.Replace("Attribute", ""));

        // 如果没有找到特性，直接返回
        if (moduleAttribute == null)
        {
            return null;
        }

        // 获取模块的依赖项（如果有的话）
        var dependencyTypes = new List<string>();
        if (moduleAttribute.ConstructorArguments.Any())
        {
            var dependencies = moduleAttribute.ConstructorArguments.First();
            if (dependencies.Kind == TypedConstantKind.Array && dependencies.Values.Any())
            {
                foreach (var dep in dependencies.Values)
                {
                    if (dep.Value is ITypeSymbol typeSymbol)
                    {
                        dependencyTypes.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                    }
                }
            }
        }

        // 检查是否实现了ICrestCreatesModule接口
        var implementsICrestCreatesModule = classSymbol.AllInterfaces.Any(i => i.Name == "ICrestCreatesModule");

        // 获取所有实现的接口
        var implementedInterfaces = classSymbol.AllInterfaces
            .Select(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToList();

        // 创建服务特性信息
        var serviceAttributes = new List<ServiceAttributeInfo>
        {
            new ServiceAttributeInfo(
                classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                "Singleton",
                true,
                false
            )
        };

        // 创建分析结果
        return new ClassAnalysisInfo(
            classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            classSymbol.Name,
            implementsICrestCreatesModule, // 如果实现了ICrestCreatesModule接口，则标记为服务
            ["Module"],
            new ServiceDescriptorInfo(
                classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                classSymbol.Name,
                classSymbol.ContainingNamespace.ToDisplayString(),
                serviceAttributes,
                null,
                null,
                implementedInterfaces
            )
        );
    }

    protected override bool FilterClass(ClassAnalysisInfo? info)
    {
        if (info == null)
        {
            return false;
        }

        // 过滤出标记了Module特性且实现了ICrestCreatesModule接口的类
        return info.AttributeNames.Contains("Module");
    }

    protected override string GenerateDebugInfo()
    {
        return GenerateDefaultDebugInfo("CrestCreates.Generated.Modules");
    }

    protected override void GenerateDebugReport(Compilation compilation, ImmutableArray<ClassAnalysisInfo?> classes, SourceProductionContext context)
    {
        var validClasses = classes.Where(c => c != null).Cast<ClassAnalysisInfo>().ToList();
        var moduleClasses = validClasses.Where(c => c.AttributeNames.Contains("Module")).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Debug report for module registrar generator");
        sb.AppendLine();
        sb.AppendLine("/*");
        sb.AppendLine($"Total classes analyzed: {validClasses.Count}");
        sb.AppendLine($"Module classes found: {moduleClasses.Count}");
        sb.AppendLine();
        sb.AppendLine("Module classes:");

        foreach (var moduleClass in moduleClasses)
        {
            sb.AppendLine($"  - {moduleClass.ClassName} ({moduleClass.FullName})");
            sb.AppendLine($"    Has Service Attributes: {moduleClass.HasServiceAttributes}");
            sb.AppendLine($"    Attributes: {string.Join(", ", moduleClass.AttributeNames)}");

            if (moduleClass.ServiceInfo?.ImplementedInterfaces != null)
            {
                sb.AppendLine($"    Implemented Interfaces: {string.Join(", ", moduleClass.ServiceInfo.ImplementedInterfaces)}");
            }
        }

        sb.AppendLine("*/");

        context.AddSource($"{GeneratorName}DebugReport.g.cs", sb.ToString());
    }
    protected override void Execute(Compilation compilation, ImmutableArray<ClassAnalysisInfo> classes, SourceProductionContext context)
    {
        if (!classes.Any())
        {
            return;
        }

        var moduleInfos = classes.Select(c => new ModuleInfo(
            c.FullName,
            c.ClassName,
            GetModuleDependencies(c, compilation)
        )).ToList();

        var source = GenerateModuleRegistrarCode(moduleInfos);
        context.AddSource($"{GeneratedClassName}.g.cs", source);
    }
    // This overload is redundant and not used; removed to avoid errors.
    private List<string> GetModuleDependencies(ClassAnalysisInfo classInfo, Compilation compilation)
    {
        if (classInfo.ServiceInfo == null)
        {
            return [];
        }

        var dependencyTypes = new List<string>();

        // 获取模块的依赖项
        var classSymbol = compilation.GetTypeByMetadataName(classInfo.FullName);
        if (classSymbol == null)
        {
            return dependencyTypes;
        }
        // 查找类上的ModuleAttribute特性
        var moduleAttribute = classSymbol.GetAttributes()
            .FirstOrDefault(attr => attr.AttributeClass?.Name == ClassAttributeName ||
                                    attr.AttributeClass?.Name == ClassAttributeName.Replace("Attribute", ""));

        // 从特性构造函数参数中提取依赖类型
        if (moduleAttribute == null || !moduleAttribute.ConstructorArguments.Any())
        {
            return dependencyTypes;
        }
        var dependencies = moduleAttribute.ConstructorArguments.First();
        if (dependencies.Kind != TypedConstantKind.Array || !dependencies.Values.Any())
        {
            return dependencyTypes;
        }
        foreach (var dep in dependencies.Values)
        {
            if (dep.Value is ITypeSymbol typeSymbol)
            {
                dependencyTypes.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }
        }

        return dependencyTypes;
    }    /// <summary>
         /// 改进的拓扑排序方法，用于处理模块依赖关系
         /// </summary>
    private static List<ModuleInfo> SortModulesByDependencies(List<ModuleInfo> modules)
    {
        // 创建模块名称到模块信息的映射
        var moduleMap = modules.ToDictionary(m => m.TypeName);
        
        // 创建已访问的模块跟踪和记录已完成排序的模块
        var visited = new Dictionary<string, bool>();
        var temporaryMarked = new HashSet<string>(); // 用于检测循环依赖
        var result = new List<ModuleInfo>();
        
        // 首先确保所有依赖项都是有效的（在moduleMap中存在）
        foreach (var module in modules)
        {
            var validDependencies = new List<string>();
            foreach (var dep in module.Dependencies)
            {
                if (moduleMap.ContainsKey(dep))
                {
                    validDependencies.Add(dep);
                }
                else
                {
                    // 记录无效依赖项，这些依赖可能是外部模块或者拼写错误
                    System.Diagnostics.Debug.WriteLine($"Warning: Module {module.TypeName} depends on {dep}, but it's not found in registered modules");
                }
            }
            
            // 更新模块的依赖项列表，只保留有效的依赖
            if (module.Dependencies.Count != validDependencies.Count)
            {
                module.Dependencies.Clear();
                module.Dependencies.AddRange(validDependencies);
            }
        }

        // 对每个模块进行深度优先搜索
        foreach (var module in modules)
        {
            if (!visited.ContainsKey(module.TypeName) && !temporaryMarked.Contains(module.TypeName))
            {
                VisitModuleEnhanced(module, moduleMap, visited, temporaryMarked, result);
            }
        }

        return result;
    }

    /// <summary>
    /// 增强版的拓扑排序递归辅助方法，支持循环依赖检测
    /// </summary>
    private static void VisitModuleEnhanced(ModuleInfo module,
        Dictionary<string, ModuleInfo> moduleMap,
        Dictionary<string, bool> visited,
        HashSet<string> temporaryMarked,
        List<ModuleInfo> result)
    {
        // 如果已经在结果列表中，直接返回
        if (result.Contains(module))
        {
            return;
        }
        
        // 检查是否有循环依赖
        if (!temporaryMarked.Add(module.TypeName))
        {
            // 发现循环依赖，但为了不中断流程，我们记录警告并继续
            throw new InvalidOperationException($"Circular dependency detected for module {module.TypeName}. Please review the module dependencies.");
        }
        
        // 临时标记为正在访问

        // 先访问所有依赖项
        foreach (var dependency in module.Dependencies)
        {
            // 如果依赖项存在于模块映射中且尚未被访问
            if (moduleMap.TryGetValue(dependency, out var dependencyModule) && 
                !result.Contains(dependencyModule))
            {
                VisitModuleEnhanced(dependencyModule, moduleMap, visited, temporaryMarked, result);
            }
        }
        
        // 移除临时标记
        temporaryMarked.Remove(module.TypeName);
        
        // 标记为已完成访问
        visited[module.TypeName] = true;
        
        // 将模块添加到结果中（如果尚未添加）
        if (!result.Contains(module))
        {
            result.Add(module);
        }
    }    private string GenerateModuleRegistrarCode(List<ModuleInfo> moduleInfos)
    {
        // 对模块按照依赖关系进行排序
        var sortedModules = SortModulesByDependencies(moduleInfos);

        var sb = new StringBuilder();

        // 添加标准的文件头
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file contains auto-generated code for module registration");
        sb.AppendLine("// Do not modify this file directly");
        sb.AppendLine();
        // 添加必要的 using 语句
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using CrestCreates.Modularity;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();        // 创建类的命名空间和类头
        sb.AppendLine("namespace CrestCreates.Generated.Modules");
        sb.AppendLine("{");

        // 生成 ModuleRegistrar 类
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 自动生成的模块注册器");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class GeneratedModuleRegistrar");
        sb.AppendLine("    {");

        // 添加模块类型列表
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 所有已注册模块的类型");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static readonly Type[] ModuleTypes = new Type[]");
        sb.AppendLine("        {");

        // 添加每个模块类型，使用排序后的模块列表
        foreach (var module in sortedModules)
        {
            sb.AppendLine($"            typeof({module.TypeName}),");
        }

        sb.AppendLine("        };");
        sb.AppendLine();

        // 添加获取模块实例的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 从服务提供程序获取所有模块实例");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IEnumerable<ICrestCreatesModule> GetModules(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            foreach (var moduleType in ModuleTypes)");
        sb.AppendLine("            {");
        sb.AppendLine("                yield return (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加配置服务的扩展方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 注册所有模块");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddModules(this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 注册所有模块类型到服务容器");
        sb.AppendLine("            foreach (var moduleType in ModuleTypes)");
        sb.AppendLine("            {");
        sb.AppendLine("                services.AddSingleton(moduleType);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加配置模块的扩展方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 配置所有模块的服务");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection ConfigureModules(this IServiceCollection services)");
        sb.AppendLine("        {");
        sb.AppendLine("            var serviceProvider = services.BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = false });");
        sb.AppendLine();
        sb.AppendLine("            // 按模块间的依赖关系顺序配置服务");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                module?.ConfigureServices(services);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
          // 添加过滤版本的配置模块方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 配置符合条件的模块的服务");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection ConfigureModules(this IServiceCollection services, Func<Type, bool> filter)");
        sb.AppendLine("        {");
        sb.AppendLine("            var serviceProvider = services.BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = false });");
        sb.AppendLine();
        sb.AppendLine("            // 按模块间的依赖关系顺序配置服务");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Where(filter))");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                module?.ConfigureServices(services);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加执行应用程序初始化前操作的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 执行所有模块的应用程序初始化前操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void PreAppInitialize(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPreApplicationInitialization preInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    preInitModule.OnPreApplicationInitialization();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加执行应用程序初始化前操作的异步方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步执行所有模块的应用程序初始化前操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task PreAppInitializeAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPreApplicationInitialization preInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await preInitModule.OnPreApplicationInitializationAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加初始化模块的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 初始化所有模块");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void InitializeModules(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序初始化");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                module?.Initialize(serviceProvider);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加执行应用程序初始化后操作的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 执行所有模块的应用程序初始化后操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void PostAppInitialize(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPostApplicationInitialization postInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    postInitModule.OnPostApplicationInitialization();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加执行应用程序初始化后操作的异步方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步执行所有模块的应用程序初始化后操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task PostAppInitializeAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPostApplicationInitialization postInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await postInitModule.OnPostApplicationInitializationAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加执行应用程序关闭前操作的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 执行所有模块的应用程序关闭前操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void PreAppShutdown(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭前操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPreApplicationShutdown preShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    preShutdownModule.OnPreApplicationShutdown();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加执行应用程序关闭前操作的异步方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步执行所有模块的应用程序关闭前操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task PreAppShutdownAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭前操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPreApplicationShutdown preShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await preShutdownModule.OnPreApplicationShutdownAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加关闭模块的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 关闭所有模块");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void ShutdownModules(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序关闭模块");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                module?.Shutdown(serviceProvider);");
        sb.AppendLine("            }");        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加执行应用程序关闭后操作的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 执行所有模块的应用程序关闭后操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void PostAppShutdown(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭后操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPostApplicationShutdown postShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    postShutdownModule.OnPostApplicationShutdown();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");        sb.AppendLine("        }");
        sb.AppendLine();

        // 添加执行应用程序关闭后操作的异步方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步执行所有模块的应用程序关闭后操作");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task PostAppShutdownAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭后操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                if (module is IOnPostApplicationShutdown postShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await postShutdownModule.OnPostApplicationShutdownAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加初始化模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 完整初始化所有模块，包括前置钩子、初始化和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void InitializeModulesWithLifecycleHooks(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 1. 执行应用程序初始化前操作");
        sb.AppendLine("            PreAppInitialize(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 2. 初始化模块");
        sb.AppendLine("            InitializeModules(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 3. 执行应用程序初始化后操作");
        sb.AppendLine("            PostAppInitialize(serviceProvider);");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加异步初始化模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步完整初始化所有模块，包括前置钩子、初始化和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task InitializeModulesWithLifecycleHooksAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 1. 执行应用程序初始化前操作");
        sb.AppendLine("            await PreAppInitializeAsync(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 2. 初始化模块");
        sb.AppendLine("            InitializeModules(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 3. 执行应用程序初始化后操作");
        sb.AppendLine("            await PostAppInitializeAsync(serviceProvider);");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加关闭模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 完整关闭所有模块，包括前置钩子、关闭和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void ShutdownModulesWithLifecycleHooks(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 1. 执行应用程序关闭前操作");
        sb.AppendLine("            PreAppShutdown(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 2. 关闭模块");
        sb.AppendLine("            ShutdownModules(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 3. 执行应用程序关闭后操作");
        sb.AppendLine("            PostAppShutdown(serviceProvider);");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加异步关闭模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步完整关闭所有模块，包括前置钩子、关闭和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task ShutdownModulesWithLifecycleHooksAsync(IServiceProvider serviceProvider)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 1. 执行应用程序关闭前操作");
        sb.AppendLine("            await PreAppShutdownAsync(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 2. 关闭模块");
        sb.AppendLine("            ShutdownModules(serviceProvider);");
        sb.AppendLine();
        sb.AppendLine("            // 3. 执行应用程序关闭后操作");
        sb.AppendLine("            await PostAppShutdownAsync(serviceProvider);");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加过滤版本的初始化模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 完整初始化符合条件的模块，包括前置钩子、初始化和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void InitializeModulesWithLifecycleHooks(IServiceProvider serviceProvider, Func<Type, bool> filter)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Where(filter))");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                // 1. 执行初始化前操作");
        sb.AppendLine("                if (module is IOnPreApplicationInitialization preInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    preInitModule.OnPreApplicationInitialization();");
        sb.AppendLine("                }");
        sb.AppendLine("                // 2. 初始化");
        sb.AppendLine("                module?.Initialize(serviceProvider);");
        sb.AppendLine("                // 3. 执行初始化后操作");
        sb.AppendLine("                if (module is IOnPostApplicationInitialization postInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    postInitModule.OnPostApplicationInitialization();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加过滤版本的异步初始化模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步完整初始化符合条件的模块，包括前置钩子、初始化和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task InitializeModulesWithLifecycleHooksAsync(IServiceProvider serviceProvider, Func<Type, bool> filter)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按模块间的依赖关系顺序执行");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Where(filter))");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                // 1. 执行初始化前操作");
        sb.AppendLine("                if (module is IOnPreApplicationInitialization preInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await preInitModule.OnPreApplicationInitializationAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("                // 2. 初始化");
        sb.AppendLine("                module?.Initialize(serviceProvider);");
        sb.AppendLine("                // 3. 执行初始化后操作");
        sb.AppendLine("                if (module is IOnPostApplicationInitialization postInitModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await postInitModule.OnPostApplicationInitializationAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();        // 添加过滤版本的关闭模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 完整关闭符合条件的模块，包括前置钩子、关闭和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void ShutdownModulesWithLifecycleHooks(IServiceProvider serviceProvider, Func<Type, bool> filter)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Where(filter).Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                // 1. 执行关闭前操作");
        sb.AppendLine("                if (module is IOnPreApplicationShutdown preShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    preShutdownModule.OnPreApplicationShutdown();");
        sb.AppendLine("                }");
        sb.AppendLine("                // 2. 关闭");
        sb.AppendLine("                module?.Shutdown(serviceProvider);");
        sb.AppendLine("                // 3. 执行关闭后操作");
        sb.AppendLine("                if (module is IOnPostApplicationShutdown postShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    postShutdownModule.OnPostApplicationShutdown();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 添加过滤版本的异步关闭模块及其生命周期钩子的综合方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 异步完整关闭符合条件的模块，包括前置钩子、关闭和后置钩子");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static async Task ShutdownModulesWithLifecycleHooksAsync(IServiceProvider serviceProvider, Func<Type, bool> filter)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 按与初始化相反的顺序执行关闭操作");
        sb.AppendLine("            foreach (var moduleType in GetModuleLoadingOrder().Where(filter).Reverse())");
        sb.AppendLine("            {");
        sb.AppendLine("                var module = (ICrestCreatesModule)serviceProvider.GetService(moduleType);");
        sb.AppendLine("                // 1. 执行关闭前操作");
        sb.AppendLine("                if (module is IOnPreApplicationShutdown preShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await preShutdownModule.OnPreApplicationShutdownAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("                // 2. 关闭");
        sb.AppendLine("                module?.Shutdown(serviceProvider);");
        sb.AppendLine("                // 3. 执行关闭后操作");
        sb.AppendLine("                if (module is IOnPostApplicationShutdown postShutdownModule)");
        sb.AppendLine("                {");
        sb.AppendLine("                    await postShutdownModule.OnPostApplicationShutdownAsync();");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();// 添加获取模块加载顺序的方法
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取考虑依赖关系的模块加载顺序");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static IEnumerable<Type> GetModuleLoadingOrder()");
        sb.AppendLine("        {");
        sb.AppendLine("            // 使用拓扑排序来确保依赖项先于依赖它们的模块加载");
        sb.AppendLine("            var sortedModules = new List<Type>();");
        sb.AppendLine("            var visited = new Dictionary<Type, bool>();");
        sb.AppendLine("            var temporaryMarked = new HashSet<Type>(); // 用于检测循环依赖");
        sb.AppendLine("            ");
        sb.AppendLine("            foreach (var moduleType in ModuleTypes)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!visited.ContainsKey(moduleType) && !temporaryMarked.Contains(moduleType))");
        sb.AppendLine("                {");
        sb.AppendLine("                    TopologicalSortVisit(moduleType, visited, temporaryMarked, sortedModules);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            return sortedModules;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 拓扑排序的递归访问方法");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static void TopologicalSortVisit(Type moduleType, Dictionary<Type, bool> visited, HashSet<Type> temporaryMarked, List<Type> sortedModules)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 如果已经在结果列表中，直接返回");
        sb.AppendLine("            if (sortedModules.Contains(moduleType))");
        sb.AppendLine("            {");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 检查是否有循环依赖");
        sb.AppendLine("            if (temporaryMarked.Contains(moduleType))");
        sb.AppendLine("            {");
        sb.AppendLine("                // 发现循环依赖，记录警告并继续");
        sb.AppendLine("                System.Diagnostics.Debug.WriteLine($\"Warning: Circular dependency detected for module {moduleType.FullName}\");");
        sb.AppendLine("                return;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // 临时标记为正在访问");
        sb.AppendLine("            temporaryMarked.Add(moduleType);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 获取模块的依赖项");
        sb.AppendLine("            var dependencies = GetModuleDependencies(moduleType);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 先访问所有依赖项");
        sb.AppendLine("            foreach (var dependency in dependencies)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!sortedModules.Contains(dependency))");
        sb.AppendLine("                {");
        sb.AppendLine("                    TopologicalSortVisit(dependency, visited, temporaryMarked, sortedModules);");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            // 移除临时标记");
        sb.AppendLine("            temporaryMarked.Remove(moduleType);");
        sb.AppendLine("            ");
        sb.AppendLine("            // 标记为已访问完成");
        sb.AppendLine("            visited[moduleType] = true;");
        sb.AppendLine("            ");
        sb.AppendLine("            // 添加到结果列表（如果尚未添加）");
        sb.AppendLine("            if (!sortedModules.Contains(moduleType))");
        sb.AppendLine("            {");
        sb.AppendLine("                sortedModules.Add(moduleType);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 获取模块类型的依赖项");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        private static IEnumerable<Type> GetModuleDependencies(Type moduleType)");
        sb.AppendLine("        {");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                // 获取ModuleAttribute");
        sb.AppendLine("                var moduleAttr = moduleType.GetCustomAttributes(typeof(ModuleAttribute), false).FirstOrDefault() as ModuleAttribute;");
        sb.AppendLine("                if (moduleAttr != null && moduleAttr.Dependencies != null)");
        sb.AppendLine("                {");
        sb.AppendLine("                    // 过滤出有效的依赖项（在已注册模块中存在的）");
        sb.AppendLine("                    var validDependencies = new List<Type>();");
        sb.AppendLine("                    foreach (var dependency in moduleAttr.Dependencies)");
        sb.AppendLine("                    {");
        sb.AppendLine("                        if (ModuleTypes.Contains(dependency))");
        sb.AppendLine("                        {");
        sb.AppendLine("                            validDependencies.Add(dependency);");
        sb.AppendLine("                        }");
        sb.AppendLine("                        else");
        sb.AppendLine("                        {");
        sb.AppendLine("                            // 记录未找到的依赖项，可能是未注册的模块或者拼写错误");
        sb.AppendLine("                            System.Diagnostics.Debug.WriteLine($\"Warning: Module {moduleType.Name} depends on {dependency.Name}, but it's not found in registered modules\");");
        sb.AppendLine("                        }");
        sb.AppendLine("                    }");
        sb.AppendLine("                    ");
        sb.AppendLine("                    // 如果有效的依赖项列表不为空，则返回");
        sb.AppendLine("                    if (validDependencies.Any())");
        sb.AppendLine("                    {");
        sb.AppendLine("                        // 记录依赖关系，便于调试");
        sb.AppendLine("                        System.Diagnostics.Debug.WriteLine($\"Module {moduleType.Name} depends on: {string.Join(\", \", validDependencies.Select(d => d.Name))}\");");
        sb.AppendLine("                        return validDependencies;");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception ex)");
        sb.AppendLine("            {");
        sb.AppendLine("                // 如果在获取依赖项过程中发生异常，记录错误日志");
        sb.AppendLine("                System.Diagnostics.Debug.WriteLine($\"Error getting dependencies for module {moduleType.Name}: {ex.Message}\");");
        sb.AppendLine("            }");
        sb.AppendLine("            ");
        sb.AppendLine("            return Array.Empty<Type>();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }    // Initialize 方法已在基类 CommonIncrementalGenerator 中实现
}