using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using CrestCreates.DependencyInjection;
using CrestCreates.SourceGenerator.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CrestCreates.SourceGenerator
{
    /// <summary>
    /// 服务注册生成器
    /// </summary>
    [Generator]
    public class ServiceRegistrationGenerator : CommonIncrementalGenerator
    {
        /// <summary>
        /// 获取生成器名称
        /// </summary>
        protected override string GeneratorName => "ServiceRegistrationGenerator";

        /// <summary>
        /// 获取生成的属性名称
        /// </summary>
        protected override string ClassAttributeName => ServiceRegistrationConstDefine.GeneratedServiceRegistrarAttributeName;

        /// <summary>
        /// 获取生成的类名
        /// </summary>
        protected override string GeneratedClassName => ServiceRegistrationConstDefine.GeneratedServiceRegistrarName;

        /// <summary>
        /// 获取生成的属性源代码
        /// </summary>
        protected override string GetAttributeSource()
        {
            return $$"""
                     // <auto-generated/>
                     #nullable enable
                     using System;

                     namespace CrestCreates.SourceGenerator
                     {
                         [AttributeUsage(AttributeTargets.Assembly)]
                         internal sealed class {{ClassAttributeName}} : Attribute
                         {
                             public Type RegistrarType { get; }
                             
                             public {{ClassAttributeName}}(Type registrarType)
                             {
                                 RegistrarType = registrarType;
                             }
                         }
                     }
                     
                     """;
        }

        /// <summary>
        /// 过滤出有服务属性的类
        /// </summary>
        protected override bool FilterClass(ClassAnalysisInfo? info)
        {
            return info?.HasServiceAttributes ?? false;
        }        /// <summary>
                 /// 分析类是否满足生成条件
                 /// </summary>
        protected override ClassAnalysisInfo? AnalyzeClass(GeneratorSyntaxContext context)
        {
            if (context.Node is not ClassDeclarationSyntax classDeclaration)
                return null;

            var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);
            if (classSymbol == null)
                return null;

            var attributes = classSymbol.GetAttributes();
            var serviceAttributes = new List<string>();
            var hasServiceAttributes = false;

            foreach (var attr in attributes)
            {
                var attrName = attr.AttributeClass?.Name ?? "Unknown";
                serviceAttributes.Add(attrName);

                if (IsServiceAttributeClass(attr.AttributeClass))
                {
                    hasServiceAttributes = true;
                }
            }

            return new ClassAnalysisInfo(
                classSymbol.ToDisplayString(),
                classSymbol.Name,
                hasServiceAttributes,
                serviceAttributes,
                hasServiceAttributes ? GetServiceInfo(context) : null
            );
        }
        private bool IsServiceAttributeClass(INamedTypeSymbol? attributeClass)
        {
            if (attributeClass == null) return false;

            // 直接检查已知的服务属性
            if (attributeClass.Name is nameof(SingletonAttribute) or nameof(ScopedAttribute)
                or nameof(TransientAttribute))
                return true;

            // 检查是否继承自ServiceAttribute
            var current = attributeClass.BaseType;
            while (current != null)
            {
                if (current.Name == nameof(ServiceAttribute))
                    return true;
                current = current.BaseType;
            }

            return false;
        }/// <summary>
         /// 生成调试信息
         /// </summary>
        protected override string GenerateDebugInfo()
        {
            return """
                   // <auto-generated/>
                   // This file contains debug information for the service registration generator

                   using System;

                   namespace MyFramework.DI.Generated.Debug
                   {
                       public static class GeneratorDebugInfo
                       {
                           public static readonly string GeneratedAt = DateTimeOffset.Now.ToString();
                           public static readonly string Message = "Service registration generator is working";
                       }
                   }
                   """;
        }        /// <summary>
                 /// 生成调试报告
                 /// </summary>
        protected override void GenerateDebugReport(Compilation compilation, ImmutableArray<ClassAnalysisInfo?> classes,
            SourceProductionContext context)
        {
            var validClasses = classes.Where(c => c != null).Cast<ClassAnalysisInfo>().ToList();
            var serviceClasses = validClasses.Where(c => c.HasServiceAttributes).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Debug report for service registration generator");
            sb.AppendLine();
            sb.AppendLine("/*");
            sb.AppendLine($"Total classes analyzed: {validClasses.Count}");
            sb.AppendLine($"Classes with service attributes: {serviceClasses.Count}");
            sb.AppendLine();
            sb.AppendLine("Classes with service attributes:");

            foreach (var serviceClass in serviceClasses)
            {
                sb.AppendLine($"  - {serviceClass.ClassName}");
                sb.AppendLine($"    Attributes: {string.Join(", ", serviceClass.AttributeNames)}");
            }

            sb.AppendLine();
            sb.AppendLine("All classes:");
            foreach (var cls in validClasses)
            {
                sb.AppendLine($"  - {cls.ClassName} (Attributes: {string.Join(", ", cls.AttributeNames)})");
            }

            sb.AppendLine("*/");

            context.AddSource($"{GeneratorName}DebugReport.g.cs", sb.ToString());
        }
        private ServiceDescriptorInfo? GetServiceInfo(GeneratorSyntaxContext context)
        {
            if (context.Node is not ClassDeclarationSyntax classDeclaration)
                return null;

            var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

            if (classSymbol is null || classSymbol.IsAbstract)
                return null;

            if (classSymbol is not INamedTypeSymbol namedTypeSymbol)
            {
                return null;
            }

            // 检查是否被标记为忽略
            if (HasIgnoreAttribute(namedTypeSymbol))
                return null;

            // 获取所有服务属性（包括继承的）
            var serviceAttributes = GetAllServiceAttributes(namedTypeSymbol);
            if (!serviceAttributes.Any())
                return null;

            var constructors = GetValidConstructors(namedTypeSymbol);
            var primaryConstructor = SelectPrimaryConstructor(constructors);

            return new ServiceDescriptorInfo(
                classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                classSymbol.Name,
                classSymbol.ContainingNamespace.ToDisplayString(),
                serviceAttributes,
                primaryConstructor,
                GetImplementedInterfaces(namedTypeSymbol)
            );
        }
        private bool HasIgnoreAttribute(INamedTypeSymbol classSymbol)
        {
            return classSymbol.GetAttributes()
                .Any(attr => attr.AttributeClass?.Name == nameof(IgnoreServiceAttribute));
        }

        private List<ServiceAttributeInfo> GetAllServiceAttributes(INamedTypeSymbol classSymbol)
        {
            var attributes = new List<ServiceAttributeInfo>();

            foreach (var attr in classSymbol.GetAttributes())
            {
                var serviceAttributeInfo = TryGetServiceAttributeInfo(attr, classSymbol);
                if (serviceAttributeInfo != null)
                {
                    attributes.Add(serviceAttributeInfo);
                }
            }

            return attributes;
        }
        private ServiceAttributeInfo? TryGetServiceAttributeInfo(AttributeData attr,
            INamedTypeSymbol classSymbol)
        {
            var attributeClass = attr.AttributeClass;
            if (attributeClass == null)
                return null;

            // 检查是否是服务属性或其派生类
            var lifetime = GetLifetimeFromAttributeClass(attributeClass);
            if (lifetime == null)
                return null;

            var serviceType = GetServiceTypeFromAttribute(attr, classSymbol);
            var registerAsInterfaces = GetBoolProperty(attr, "RegisterAsImplementedInterfaces");
            var replace = GetBoolProperty(attr, "Replace");

            return new ServiceAttributeInfo(
                serviceType,
                lifetime,
                registerAsInterfaces,
                replace
            );
        }
        private string? GetLifetimeFromAttributeClass(INamedTypeSymbol attributeClass)
        {
            // 检查具体的属性类型
            switch (attributeClass.Name)
            {
                case "SingletonAttribute":
                    return "Singleton";
                case "ScopedAttribute":
                    return "Scoped";
                case "TransientAttribute":
                    return "Transient";
                default:
                    // 检查是否继承自ServiceAttribute
                    var baseType = attributeClass.BaseType;
                    while (baseType != null)
                    {
                        if (baseType.Name == "ServiceAttribute")
                        {
                            // 这是一个自定义的服务属性，尝试获取Lifetime属性
                            return TryGetLifetimeFromCustomAttribute(attributeClass);
                        }

                        baseType = baseType.BaseType;
                    }

                    return null;
            }
        }

        private string? TryGetLifetimeFromCustomAttribute(INamedTypeSymbol attributeClass)
        {
            // 查找Lifetime属性
            var lifetimeProperty = attributeClass.GetMembers("Lifetime")
                .OfType<IPropertySymbol>()
                .FirstOrDefault();

            if (lifetimeProperty?.IsOverride == true)
            {
                // 这里需要更复杂的逻辑来获取重写的值
                // 简化处理，返回默认值
                return "Transient";
            }

            return null;
        }
        private string GetServiceTypeFromAttribute(AttributeData attr, INamedTypeSymbol implementationType)
        {
            // 检查构造函数参数
            if (attr.ConstructorArguments.Length > 0)
            {
                var firstArg = attr.ConstructorArguments[0];
                if (firstArg.Value is ITypeSymbol typeSymbol)
                {
                    return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                }
            }

            // 检查 ServiceType 属性
            var serviceTypeProperty = attr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == nameof(ServiceAttribute.ServiceType));

            if (serviceTypeProperty.Value.Value is ITypeSymbol serviceType)
            {
                return serviceType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            // 默认使用实现类型
            return implementationType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private bool GetBoolProperty(AttributeData attr, string propertyName)
        {
            var property = attr.NamedArguments
                .FirstOrDefault(kvp => kvp.Key == propertyName);

            return property.Value.Value is true;
        }

        private List<ConstructorInfo> GetValidConstructors(INamedTypeSymbol classSymbol)
        {
            return classSymbol.Constructors
                .Where(c => c is { DeclaredAccessibility: Accessibility.Public, IsStatic: false })
                .Select(c =>
                {
                    Debug.WriteLine($"Constructor: {c.Name}");
                    var paraInfo = c.Parameters.Select(p => new ParameterInfo(
                        p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        p.Name,
                        p.HasExplicitDefaultValue,
                        p.HasExplicitDefaultValue ? p.ExplicitDefaultValue?.ToString() : null
                    )).ToList();
                    return new ConstructorInfo(paraInfo);
                })
                .ToList();
        }

        private ConstructorInfo? SelectPrimaryConstructor(List<ConstructorInfo> constructors)
        {
            if (!constructors.Any())
            {
                return null;
            }

            // 选择参数最多的构造函数（DI 约定）
            return constructors.OrderByDescending(c => c.Parameters.Count).First();
        }

        private List<string> GetImplementedInterfaces(INamedTypeSymbol classSymbol)
        {
            return classSymbol.AllInterfaces
                .Where(i => i.DeclaredAccessibility == Accessibility.Public)
                .Select(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .ToList();
        }/// <summary>
         /// 执行代码生成
         /// </summary>
        protected override void Execute(Compilation compilation, ImmutableArray<ClassAnalysisInfo> services,
            SourceProductionContext context)
        {
            // Log(context, $"Processing {services.Count()} services");
            if (!services.Any())
            {
                return;
            }

            var assemblyName = compilation.AssemblyName ?? "GeneratedAssembly";
            var source = GenerateServiceRegistrar(services, assemblyName);

            context.AddSource($"ServiceRegistrar.g.cs", source);
        }

        private string GenerateServiceRegistrar(ImmutableArray<ClassAnalysisInfo> services,
            string assemblyName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine("using CrestCreates.DependencyInjection;");
            sb.AppendLine();


            // 生成命名空间
            var namespaceName = $"CrestCreates.Generated.{assemblyName.Replace(".", "_")}";
            // 通过Attribute引用生成程序集级别属性
            sb.AppendLine($"[assembly: CrestCreates.SourceGenerator.{ClassAttributeName}(typeof({namespaceName}.{GeneratedClassName}))]");
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();

            // 生成程序集级别属性
            sb.AppendLine($"internal sealed class {GeneratedClassName} : IServiceRegistrar");
            sb.AppendLine("{");
            sb.AppendLine("    public void RegisterServices(IServiceCollection services)");
            sb.AppendLine("    {");            // 生成服务注册代码
            foreach (var service in services)
            {
                GenerateServiceRegistration(sb, service);
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            // 生成工厂方法
            foreach (var service in services.Select(x => x.ServiceInfo)
                         .Where(s => s?.PrimaryConstructor?.Parameters.Any() == true))
            {
                if (service != null)
                {
                    GenerateFactoryMethod(sb, service);
                }
            }

            sb.AppendLine("}");
            sb.AppendLine();


            return sb.ToString();
        }
        private void GenerateServiceRegistration(StringBuilder sb, ClassAnalysisInfo service)
        {
            if (service.ServiceInfo != null)
            {
                var attributes = service.ServiceInfo.ServiceAttributes;
                foreach (var attr in attributes)
                {
                    if (attr.RegisterAsImplementedInterfaces)
                    {
                        // 注册为所有实现的接口
                        foreach (var interfaceType in service.ServiceInfo.ImplementedInterfaces)
                        {
                            GenerateSingleServiceRegistration(sb, service.ServiceInfo, attr, interfaceType);
                        }
                    }
                    else
                    {
                        // 注册为指定的服务类型
                        GenerateSingleServiceRegistration(sb, service.ServiceInfo, attr, attr.ServiceType);
                    }
                }
            }
        }
        private void GenerateSingleServiceRegistration(StringBuilder sb, ServiceDescriptorInfo service,
            ServiceAttributeInfo attr, string serviceType)
        {
            var method = attr.Replace ? "Replace" : "TryAdd";
            var hasParameters = service.PrimaryConstructor?.Parameters.Any() == true;

            if (hasParameters)
            {
                // 使用工厂方法
                var factoryMethodName = $"Create{service.ClassName}";
                sb.AppendLine(
                    $"        services.{method}{attr.Lifetime}(typeof({serviceType}), serviceProvider => {factoryMethodName}(serviceProvider));");
            }
            else
            {
                // 直接注册
                if (serviceType == service.FullTypeName)
                {
                    sb.AppendLine($"        services.{method}{attr.Lifetime}<{service.FullTypeName}>();");
                }
                else
                {
                    sb.AppendLine(
                        $"        services.{method}{attr.Lifetime}<{serviceType}, {service.FullTypeName}>();");
                }
            }
        }
        private void GenerateFactoryMethod(StringBuilder sb, ServiceDescriptorInfo service)
        {
            var methodName = $"Create{service.ClassName}";
            sb.AppendLine($"    private static {service.FullTypeName} {methodName}(IServiceProvider serviceProvider)");
            sb.AppendLine("    {");

            var constructor = service.PrimaryConstructor!;
            if (constructor.Parameters.Any())
            {
                // 生成参数获取代码
                foreach (var param in constructor.Parameters)
                {
                    if (param.HasDefaultValue)
                    {
                        sb.AppendLine(
                            $"        var {param.Name} = serviceProvider.GetService<{param.Type}>() ?? {param.DefaultValue};");
                    }
                    else
                    {
                        sb.AppendLine(
                            $"        var {param.Name} = serviceProvider.GetRequiredService<{param.Type}>();");
                    }
                }

                var parameterNames = string.Join(", ", constructor.Parameters.Select(p => p.Name));
                sb.AppendLine($"        return new {service.FullTypeName}({parameterNames});");
            }
            else
            {
                sb.AppendLine($"        return new {service.FullTypeName}();");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }
        private void Log(SourceProductionContext context, string message)
        {
            var diagnostic = Diagnostic.Create(
                new DiagnosticDescriptor(
                    "CREST0001",
                    "CrestCreates",
                    message,
                    "CrestCreates",
                    DiagnosticSeverity.Warning,
                    true,
                    message
                ),
                Location.None
            );
            context.ReportDiagnostic(diagnostic);
        }
    }

}